/*
 * Lumeer: Modern Data Definition and Processing Platform
 *
 * Copyright (C) since 2017 Answer Institute, s.r.o. and/or its affiliates.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export const icons: string[] = [
  'fa-address-book',
  'fa-address-card',
  'fa-adjust',
  'fa-alarm-clock',
  'fa-align-center',
  'fa-align-justify',
  'fa-align-left',
  'fa-align-right',
  'fa-allergies',
  'fa-ambulance',
  'fa-american-sign-language-interpreting',
  'fa-angle-double-down',
  'fa-angle-double-left',
  'fa-angle-double-right',
  'fa-angle-double-up',
  'fa-angle-down',
  'fa-angle-left',
  'fa-angle-right',
  'fa-angle-up',
  'fa-angry',
  'fa-anchor',
  'fa-archive',
  'fa-archway',
  'fa-arrow-alt-circle-down',
  'fa-arrow-alt-circle-left',
  'fa-arrow-alt-circle-right',
  'fa-arrow-alt-circle-up',
  'fa-arrow-alt-down',
  'fa-arrow-alt-from-bottom',
  'fa-arrow-alt-from-left',
  'fa-arrow-alt-from-right',
  'fa-arrow-alt-from-top',
  'fa-arrow-alt-left',
  'fa-arrow-alt-right',
  'fa-arrow-alt-square-down',
  'fa-arrow-alt-square-left',
  'fa-arrow-alt-square-right',
  'fa-arrow-alt-square-up',
  'fa-arrow-alt-to-bottom',
  'fa-arrow-alt-to-left',
  'fa-arrow-alt-to-right',
  'fa-arrow-alt-to-top',
  'fa-arrow-alt-up',
  'fa-arrow-circle-down',
  'fa-arrow-circle-left',
  'fa-arrow-circle-right',
  'fa-arrow-circle-up',
  'fa-arrow-down',
  'fa-arrow-from-bottom',
  'fa-arrow-from-left',
  'fa-arrow-from-right',
  'fa-arrow-from-top',
  'fa-arrow-left',
  'fa-arrow-right',
  'fa-arrows',
  'fa-arrows-alt',
  'fa-arrows-alt-h',
  'fa-arrows-alt-v',
  'fa-arrows-h',
  'fa-arrow-square-down',
  'fa-arrow-square-left',
  'fa-arrow-square-right',
  'fa-arrow-square-up',
  'fa-arrows-v',
  'fa-arrow-to-bottom',
  'fa-arrow-to-left',
  'fa-arrow-to-right',
  'fa-arrow-to-top',
  'fa-arrow-up',
  'fa-assistive-listening-systems',
  'fa-asterisk',
  'fa-at',
  'fa-atlas',
  'fa-audio-description',
  'fa-award',
  'fa-backspace',
  'fa-backward',
  'fa-badge',
  'fa-badge-check',
  'fa-balance-scale',
  'fa-balance-scale-left',
  'fa-balance-scale-right',
  'fa-ban',
  'fa-band-aid',
  'fa-barcode',
  'fa-barcode-alt',
  'fa-barcode-read',
  'fa-barcode-scan',
  'fa-bars',
  'fa-baseball',
  'fa-baseball-ball',
  'fa-basketball-ball',
  'fa-basketball-hoop',
  'fa-bath',
  'fa-battery-bolt',
  'fa-battery-empty',
  'fa-battery-full',
  'fa-battery-half',
  'fa-battery-quarter',
  'fa-battery-slash',
  'fa-battery-three-quarters',
  'fa-bed',
  'fa-beer',
  'fa-bell',
  'fa-bell-slash',
  'fa-bezier-curve',
  'fa-bicycle',
  'fa-binoculars',
  'fa-birthday-cake',
  'fa-blanket',
  'fa-blender',
  'fa-blind',
  'fa-bold',
  'fa-bolt',
  'fa-bomb',
  'fa-bong',
  'fa-book',
  'fa-book-heart',
  'fa-bookmark',
  'fa-book-open',
  'fa-bowling-ball',
  'fa-bowling-pins',
  'fa-box',
  'fa-box-alt',
  'fa-boxes',
  'fa-boxes-alt',
  'fa-box-fragile',
  'fa-box-full',
  'fa-box-heart',
  'fa-box-check',
  'fa-boxing-glove',
  'fa-box-open',
  'fa-box-up',
  'fa-box-usd',
  'fa-braille',
  'fa-briefcase',
  'fa-briefcase-medical',
  'fa-broadcast-tower',
  'fa-broom',
  'fa-browser',
  'fa-brush',
  'fa-bug',
  'fa-building',
  'fa-bullhorn',
  'fa-bullseye',
  'fa-burn',
  'fa-bus',
  'fa-bus-alt',
  'fa-calculator',
  'fa-calendar',
  'fa-calendar-alt',
  'fa-calendar-edit',
  'fa-calendar-exclamation',
  'fa-calendar-check',
  'fa-calendar-minus',
  'fa-calendar-plus',
  'fa-calendar-times',
  'fa-camera',
  'fa-camera-alt',
  'fa-camera-retro',
  'fa-cannabis',
  'fa-capsules',
  'fa-car',
  'fa-caret-circle-down',
  'fa-caret-circle-left',
  'fa-caret-circle-right',
  'fa-caret-circle-up',
  'fa-caret-down',
  'fa-caret-left',
  'fa-caret-right',
  'fa-caret-square-down',
  'fa-caret-square-left',
  'fa-caret-square-right',
  'fa-caret-square-up',
  'fa-caret-up',
  'fa-cart-arrow-down',
  'fa-cart-plus',
  'fa-certificate',
  'fa-circle',
  'fa-circle-notch',
  'fa-clipboard',
  'fa-clipboard-check',
  'fa-clipboard-list',
  'fa-clock',
  'fa-clone',
  'fa-closed-captioning',
  'fa-cloud',
  'fa-cloud-download',
  'fa-cloud-download-alt',
  'fa-cloud-upload',
  'fa-cloud-upload-alt',
  'fa-club',
  'fa-cocktail',
  'fa-code',
  'fa-code-branch',
  'fa-code-commit',
  'fa-code-merge',
  'fa-coffee',
  'fa-cog',
  'fa-cogs',
  'fa-coins',
  'fa-columns',
  'fa-comment',
  'fa-comment-alt',
  'fa-comment-alt-dots',
  'fa-comment-alt-edit',
  'fa-comment-alt-exclamation',
  'fa-comment-alt-check',
  'fa-comment-alt-lines',
  'fa-comment-alt-minus',
  'fa-comment-alt-plus',
  'fa-comment-alt-slash',
  'fa-comment-alt-smile',
  'fa-comment-alt-times',
  'fa-comment-dots',
  'fa-comment-edit',
  'fa-comment-exclamation',
  'fa-comment-check',
  'fa-comment-lines',
  'fa-comment-minus',
  'fa-comment-plus',
  'fa-comments',
  'fa-comments-alt',
  'fa-comment-slash',
  'fa-comment-smile',
  'fa-comment-times',
  'fa-compact-disc',
  'fa-compass',
  'fa-compress',
  'fa-compress-alt',
  'fa-compress-wide',
  'fa-concierge-bell',
  'fa-container-storage',
  'fa-conveyor-belt',
  'fa-conveyor-belt-alt',
  'fa-cookie',
  'fa-cookie-bite',
  'fa-copy',
  'fa-copyright',
  'fa-couch',
  'fa-credit-card',
  'fa-credit-card-blank',
  'fa-credit-card-front',
  'fa-cricket',
  'fa-crop',
  'fa-crop-alt',
  'fa-crosshairs',
  'fa-crow',
  'fa-crown',
  'fa-cube',
  'fa-cubes',
  'fa-curling',
  'fa-cut',
  'fa-database',
  'fa-deaf',
  'fa-desktop',
  'fa-desktop-alt',
  'fa-diagnoses',
  'fa-diamond',
  'fa-dice',
  'fa-dice-five',
  'fa-dice-four',
  'fa-dice-one',
  'fa-dice-six',
  'fa-dice-three',
  'fa-dice-two',
  'fa-digital-tachograph',
  'fa-divide',
  'fa-dizzy',
  'fa-dna',
  'fa-dollar-sign',
  'fa-dolly',
  'fa-dolly-empty',
  'fa-dolly-flatbed',
  'fa-dolly-flatbed-alt',
  'fa-dolly-flatbed-empty',
  'fa-donate',
  'fa-door-closed',
  'fa-door-open',
  'fa-dot-circle',
  'fa-dove',
  'fa-download',
  'fa-drafting-compass',
  'fa-drum',
  'fa-drum-steelpan',
  'fa-dumbbell',
  'fa-edit',
  'fa-eject',
  'fa-ellipsis-h',
  'fa-ellipsis-h-alt',
  'fa-ellipsis-v',
  'fa-ellipsis-v-alt',
  'fa-envelope',
  'fa-envelope-open',
  'fa-envelope-square',
  'fa-equals',
  'fa-eraser',
  'fa-euro-sign',
  'fa-exclamation',
  'fa-exclamation-circle',
  'fa-exclamation-square',
  'fa-exclamation-triangle',
  'fa-exchange',
  'fa-exchange-alt',
  'fa-expand',
  'fa-expand-alt',
  'fa-expand-arrows',
  'fa-expand-arrows-alt',
  'fa-expand-wide',
  'fa-external-link',
  'fa-external-link-alt',
  'fa-external-link-square',
  'fa-external-link-square-alt',
  'fa-eye',
  'fa-eye-dropper',
  'fa-eye-slash',
  'fa-fast-backward',
  'fa-fast-forward',
  'fa-fax',
  'fa-feather',
  'fa-feather-alt',
  'fa-female',
  'fa-field-hockey',
  'fa-fighter-jet',
  'fa-file',
  'fa-file-alt',
  'fa-file-archive',
  'fa-file-audio',
  'fa-file-code',
  'fa-file-contract',
  'fa-file-download',
  'fa-file-edit',
  'fa-file-excel',
  'fa-file-exclamation',
  'fa-file-export',
  'fa-file-check',
  'fa-file-image',
  'fa-file-import',
  'fa-file-invoice',
  'fa-file-invoice-dollar',
  'fa-file-medical',
  'fa-file-medical-alt',
  'fa-file-minus',
  'fa-file-pdf',
  'fa-file-plus',
  'fa-file-powerpoint',
  'fa-file-prescription',
  'fa-file-signature',
  'fa-file-times',
  'fa-file-upload',
  'fa-file-video',
  'fa-file-word',
  'fa-fill',
  'fa-fill-drip',
  'fa-film',
  'fa-film-alt',
  'fa-filter',
  'fa-fingerprint',
  'fa-fire',
  'fa-fire-extinguisher',
  'fa-first-aid',
  'fa-fish',
  'fa-flag',
  'fa-flag-checkered',
  'fa-flask',
  'fa-flushed',
  'fa-folder',
  'fa-folder-open',
  'fa-font',
  'fa-football-ball',
  'fa-football-helmet',
  'fa-forklift',
  'fa-forward',
  'fa-fragile',
  'fa-frog',
  'fa-frown',
  'fa-frown-open',
  'fa-futbol',
  'fa-gamepad',
  'fa-gas-pump',
  'fa-gavel',
  'fa-gem',
  'fa-genderless',
  'fa-gift',
  'fa-glasses',
  'fa-glass-martini',
  'fa-glass-martini-alt',
  'fa-globe',
  'fa-globe-africa',
  'fa-globe-americas',
  'fa-globe-asia',
  'fa-golf-ball',
  'fa-golf-club',
  'fa-graduation-cap',
  'fa-greater-than',
  'fa-greater-than-equal',
  'fa-grimace',
  'fa-grin',
  'fa-grin-alt',
  'fa-grin-beam',
  'fa-grin-beam-sweat',
  'fa-grin-hearts',
  'fa-grin-squint',
  'fa-grin-squint-tears',
  'fa-grin-stars',
  'fa-grin-tears',
  'fa-grin-tongue',
  'fa-grin-tongue-squint',
  'fa-grin-tongue-wink',
  'fa-grin-wink',
  'fa-grip-horizontal',
  'fa-grip-vertical',
  'fa-hand-heart',
  'fa-hand-holding',
  'fa-hand-holding-box',
  'fa-hand-holding-heart',
  'fa-hand-holding-seedling',
  'fa-hand-holding-usd',
  'fa-hand-holding-water',
  'fa-hand-lizard',
  'fa-hand-paper',
  'fa-hand-peace',
  'fa-hand-point-down',
  'fa-hand-pointer',
  'fa-hand-point-left',
  'fa-hand-point-right',
  'fa-hand-point-up',
  'fa-hand-receiving',
  'fa-hand-rock',
  'fa-hands',
  'fa-hand-scissors',
  'fa-handshake',
  'fa-handshake-alt',
  'fa-hands-heart',
  'fa-hands-helping',
  'fa-hand-spock',
  'fa-hands-usd',
  'fa-hashtag',
  'fa-hdd',
  'fa-heading',
  'fa-headphones',
  'fa-headphones-alt',
  'fa-headset',
  'fa-heart',
  'fa-heartbeat',
  'fa-heart-circle',
  'fa-heart-square',
  'fa-helicopter',
  'fa-hexagon',
  'fa-highlighter',
  'fa-history',
  'fa-hockey-puck',
  'fa-hockey-sticks',
  'fa-home',
  'fa-home-heart',
  'fa-hospital',
  'fa-hospital-alt',
  'fa-hospital-symbol',
  'fa-hotel',
  'fa-hot-tub',
  'fa-hourglass',
  'fa-hourglass-end',
  'fa-hourglass-half',
  'fa-hourglass-start',
  'fa-h-square',
  'fa-h1',
  'fa-h2',
  'fa-h3',
  'fa-chalkboard',
  'fa-chalkboard-teacher',
  'fa-chart-area',
  'fa-chart-bar',
  'fa-chart-line',
  'fa-chart-pie',
  'fa-check',
  'fa-check-circle',
  'fa-check-double',
  'fa-check-square',
  'fa-chess',
  'fa-chess-bishop',
  'fa-chess-bishop-alt',
  'fa-chess-board',
  'fa-chess-clock',
  'fa-chess-clock-alt',
  'fa-chess-king',
  'fa-chess-king-alt',
  'fa-chess-knight',
  'fa-chess-knight-alt',
  'fa-chess-pawn',
  'fa-chess-pawn-alt',
  'fa-chess-queen',
  'fa-chess-queen-alt',
  'fa-chess-rook',
  'fa-chess-rook-alt',
  'fa-chevron-circle-down',
  'fa-chevron-circle-left',
  'fa-chevron-circle-right',
  'fa-chevron-circle-up',
  'fa-chevron-double-down',
  'fa-chevron-double-left',
  'fa-chevron-double-right',
  'fa-chevron-double-up',
  'fa-chevron-down',
  'fa-chevron-left',
  'fa-chevron-right',
  'fa-chevron-square-down',
  'fa-chevron-square-left',
  'fa-chevron-square-right',
  'fa-chevron-square-up',
  'fa-chevron-up',
  'fa-child',
  'fa-church',
  'fa-i-cursor',
  'fa-id-badge',
  'fa-id-card',
  'fa-id-card-alt',
  'fa-image',
  'fa-images',
  'fa-inbox',
  'fa-inbox-in',
  'fa-inbox-out',
  'fa-indent',
  'fa-industry',
  'fa-industry-alt',
  'fa-infinity',
  'fa-info',
  'fa-info-circle',
  'fa-info-square',
  'fa-inventory',
  'fa-italic',
  'fa-jack-o-lantern',
  'fa-joint',
  'fa-key',
  'fa-keyboard',
  'fa-kiss',
  'fa-kiss-beam',
  'fa-kiss-wink-heart',
  'fa-kiwi-bird',
  'fa-lamp',
  'fa-language',
  'fa-laptop',
  'fa-laugh',
  'fa-laugh-beam',
  'fa-laugh-squint',
  'fa-laugh-wink',
  'fa-leaf',
  'fa-leaf-heart',
  'fa-lemon',
  'fa-less-than',
  'fa-less-than-equal',
  'fa-level-down',
  'fa-level-down-alt',
  'fa-level-up',
  'fa-level-up-alt',
  'fa-life-ring',
  'fa-lightbulb',
  'fa-link',
  'fa-lira-sign',
  'fa-list',
  'fa-list-alt',
  'fa-list-ol',
  'fa-list-ul',
  'fa-location-arrow',
  'fa-lock',
  'fa-lock-alt',
  'fa-lock-open',
  'fa-lock-open-alt',
  'fa-long-arrow-alt-down',
  'fa-long-arrow-alt-left',
  'fa-long-arrow-alt-right',
  'fa-long-arrow-alt-up',
  'fa-long-arrow-down',
  'fa-long-arrow-left',
  'fa-long-arrow-right',
  'fa-long-arrow-up',
  'fa-loveseat',
  'fa-low-vision',
  'fa-luggage-cart',
  'fa-luchador',
  'fa-magic',
  'fa-magnet',
  'fa-male',
  'fa-map',
  'fa-map-marked',
  'fa-map-marked-alt',
  'fa-map-marker',
  'fa-map-marker-alt',
  'fa-map-pin',
  'fa-map-signs',
  'fa-marker',
  'fa-mars',
  'fa-mars-double',
  'fa-mars-stroke',
  'fa-mars-stroke-h',
  'fa-mars-stroke-v',
  'fa-medal',
  'fa-medkit',
  'fa-meh',
  'fa-meh-blank',
  'fa-meh-rolling-eyes',
  'fa-memory',
  'fa-mercury',
  'fa-microchip',
  'fa-microphone',
  'fa-microphone-alt',
  'fa-microphone-alt-slash',
  'fa-microphone-slash',
  'fa-minus',
  'fa-minus-circle',
  'fa-minus-hexagon',
  'fa-minus-octagon',
  'fa-minus-square',
  'fa-mobile',
  'fa-mobile-alt',
  'fa-mobile-android',
  'fa-mobile-android-alt',
  'fa-money-bill',
  'fa-money-bill-alt',
  'fa-money-bill-wave',
  'fa-money-bill-wave-alt',
  'fa-money-check',
  'fa-money-check-alt',
  'fa-monument',
  'fa-moon',
  'fa-mortar-pestle',
  'fa-motorcycle',
  'fa-mouse-pointer',
  'fa-music',
  'fa-neuter',
  'fa-newspaper',
  'fa-not-equal',
  'fa-notes-medical',
  'fa-object-group',
  'fa-object-ungroup',
  'fa-octagon',
  'fa-outdent',
  'fa-paint-brush',
  'fa-paint-brush-alt',
  'fa-paint-roller',
  'fa-palette',
  'fa-pallet',
  'fa-pallet-alt',
  'fa-paperclip',
  'fa-paper-plane',
  'fa-paragraph',
  'fa-parachute-box',
  'fa-parking',
  'fa-passport',
  'fa-paste',
  'fa-pause',
  'fa-pause-circle',
  'fa-paw',
  'fa-pen',
  'fa-pen-alt',
  'fa-pencil',
  'fa-pencil-alt',
  'fa-pencil-ruler',
  'fa-pen-fancy',
  'fa-pennant',
  'fa-pen-nib',
  'fa-pen-square',
  'fa-people-carry',
  'fa-percent',
  'fa-percentage',
  'fa-person-carry',
  'fa-person-dolly',
  'fa-person-dolly-empty',
  'fa-phone',
  'fa-phone-plus',
  'fa-phone-slash',
  'fa-phone-square',
  'fa-phone-volume',
  'fa-piggy-bank',
  'fa-pills',
  'fa-plane',
  'fa-plane-alt',
  'fa-plane-arrival',
  'fa-plane-departure',
  'fa-play',
  'fa-play-circle',
  'fa-plug',
  'fa-plus',
  'fa-plus-circle',
  'fa-plus-hexagon',
  'fa-plus-octagon',
  'fa-plus-square',
  'fa-podcast',
  'fa-poo',
  'fa-portrait',
  'fa-pound-sign',
  'fa-power-off',
  'fa-prescription',
  'fa-prescription-bottle',
  'fa-prescription-bottle-alt',
  'fa-print',
  'fa-procedures',
  'fa-project-diagram',
  'fa-puzzle-piece',
  'fa-qrcode',
  'fa-question',
  'fa-question-circle',
  'fa-question-square',
  'fa-quidditch',
  'fa-quote-left',
  'fa-quote-right',
  'fa-racquet',
  'fa-ramp-loading',
  'fa-random',
  'fa-receipt',
  'fa-rectangle-landscape',
  'fa-rectangle-portrait',
  'fa-rectangle-wide',
  'fa-recycle',
  'fa-redo',
  'fa-redo-alt',
  'fa-registered',
  'fa-repeat',
  'fa-repeat-alt',
  'fa-repeat-1',
  'fa-repeat-1-alt',
  'fa-reply',
  'fa-reply-all',
  'fa-retweet',
  'fa-retweet-alt',
  'fa-ribbon',
  'fa-road',
  'fa-robot',
  'fa-rocket',
  'fa-route',
  'fa-rss',
  'fa-rss-square',
  'fa-ruble-sign',
  'fa-ruler',
  'fa-ruler-combined',
  'fa-ruler-horizontal',
  'fa-ruler-vertical',
  'fa-rupee-sign',
  'fa-sad-cry',
  'fa-sad-tear',
  'fa-save',
  'fa-scanner',
  'fa-scanner-keyboard',
  'fa-scanner-touchscreen',
  'fa-screwdriver',
  'fa-scrubber',
  'fa-search',
  'fa-search-minus',
  'fa-search-plus',
  'fa-seedling',
  'fa-server',
  'fa-share',
  'fa-share-all',
  'fa-share-alt',
  'fa-share-alt-square',
  'fa-share-square',
  'fa-shekel-sign',
  'fa-shield',
  'fa-shield-alt',
  'fa-shield-check',
  'fa-ship',
  'fa-shipping-fast',
  'fa-shipping-timed',
  'fa-shoe-prints',
  'fa-shopping-bag',
  'fa-shopping-basket',
  'fa-shopping-cart',
  'fa-shower',
  'fa-shuttlecock',
  'fa-shuttle-van',
  'fa-school',
  'fa-sign',
  'fa-signal',
  'fa-signature',
  'fa-sign-in',
  'fa-sign-in-alt',
  'fa-sign-language',
  'fa-sign-out',
  'fa-sign-out-alt',
  'fa-sitemap',
  'fa-skull',
  'fa-sliders-h',
  'fa-sliders-h-square',
  'fa-sliders-v',
  'fa-sliders-v-square',
  'fa-smile',
  'fa-smile-beam',
  'fa-smile-plus',
  'fa-smile-wink',
  'fa-smoking',
  'fa-smoking-ban',
  'fa-snowflake',
  'fa-solar-panel',
  'fa-sort',
  'fa-sort-alpha-down',
  'fa-sort-alpha-up',
  'fa-sort-amount-down',
  'fa-sort-amount-up',
  'fa-sort-down',
  'fa-sort-numeric-down',
  'fa-sort-numeric-up',
  'fa-sort-up',
  'fa-spa',
  'fa-space-shuttle',
  'fa-spade',
  'fa-spinner',
  'fa-spinner-third',
  'fa-splotch',
  'fa-spray-can',
  'fa-square',
  'fa-square-full',
  'fa-stamp',
  'fa-star',
  'fa-star-exclamation',
  'fa-star-half',
  'fa-star-half-alt',
  'fa-step-backward',
  'fa-step-forward',
  'fa-stethoscope',
  'fa-sticky-note',
  'fa-stop',
  'fa-stop-circle',
  'fa-stopwatch',
  'fa-store',
  'fa-store-alt',
  'fa-stream',
  'fa-street-view',
  'fa-strikethrough',
  'fa-stroopwafel',
  'fa-subscript',
  'fa-subway',
  'fa-suitcase',
  'fa-suitcase-rolling',
  'fa-sun',
  'fa-superscript',
  'fa-surprise',
  'fa-swatchbook',
  'fa-swimmer',
  'fa-swimming-pool',
  'fa-sync',
  'fa-sync-alt',
  'fa-syringe',
  'fa-table',
  'fa-tablet',
  'fa-tablet-alt',
  'fa-tablet-android',
  'fa-tablet-android-alt',
  'fa-table-tennis',
  'fa-tablet-rugged',
  'fa-tablets',
  'fa-tag',
  'fa-tags',
  'fa-tachometer',
  'fa-tachometer-alt',
  'fa-tape',
  'fa-tasks',
  'fa-taxi',
  'fa-tennis-ball',
  'fa-terminal',
  'fa-text-height',
  'fa-text-width',
  'fa-th',
  'fa-thermometer',
  'fa-thermometer-empty',
  'fa-thermometer-full',
  'fa-thermometer-half',
  'fa-thermometer-quarter',
  'fa-thermometer-three-quarters',
  'fa-th-large',
  'fa-th-list',
  'fa-thumbs-down',
  'fa-thumbs-up',
  'fa-thumbtack',
  'fa-ticket',
  'fa-ticket-alt',
  'fa-times',
  'fa-times-circle',
  'fa-times-hexagon',
  'fa-times-octagon',
  'fa-times-square',
  'fa-tint',
  'fa-tint-slash',
  'fa-tired',
  'fa-toggle-off',
  'fa-toggle-on',
  'fa-toolbox',
  'fa-tooth',
  'fa-trademark',
  'fa-train',
  'fa-transgender',
  'fa-transgender-alt',
  'fa-trash',
  'fa-trash-alt',
  'fa-tree',
  'fa-tree-alt',
  'fa-triangle',
  'fa-trophy',
  'fa-trophy-alt',
  'fa-truck',
  'fa-truck-container',
  'fa-truck-couch',
  'fa-truck-loading',
  'fa-truck-moving',
  'fa-truck-ramp',
  'fa-tshirt',
  'fa-tty',
  'fa-tv',
  'fa-tv-retro',
  'fa-umbrella',
  'fa-umbrella-beach',
  'fa-underline',
  'fa-undo',
  'fa-undo-alt',
  'fa-universal-access',
  'fa-university',
  'fa-unlink',
  'fa-unlock',
  'fa-unlock-alt',
  'fa-upload',
  'fa-usd-circle',
  'fa-usd-square',
  'fa-user',
  'fa-user-alt',
  'fa-user-alt-slash',
  'fa-user-astronaut',
  'fa-user-circle',
  'fa-user-clock',
  'fa-user-cog',
  'fa-user-edit',
  'fa-user-friends',
  'fa-user-graduate',
  'fa-user-check',
  'fa-user-lock',
  'fa-user-md',
  'fa-user-minus',
  'fa-user-ninja',
  'fa-user-plus',
  'fa-users',
  'fa-users-cog',
  'fa-user-secret',
  'fa-user-shield',
  'fa-user-slash',
  'fa-user-tag',
  'fa-user-tie',
  'fa-user-times',
  'fa-utensil-fork',
  'fa-utensil-knife',
  'fa-utensils',
  'fa-utensils-alt',
  'fa-utensil-spoon',
  'fa-vector-square',
  'fa-venus',
  'fa-venus-double',
  'fa-venus-mars',
  'fa-vial',
  'fa-vials',
  'fa-video',
  'fa-video-plus',
  'fa-video-slash',
  'fa-volleyball-ball',
  'fa-volume-down',
  'fa-volume-mute',
  'fa-volume-off',
  'fa-volume-up',
  'fa-walking',
  'fa-wallet',
  'fa-warehouse',
  'fa-warehouse-alt',
  'fa-watch',
  'fa-weight',
  'fa-weight-hanging',
  'fa-wheelchair',
  'fa-whistle',
  'fa-wifi',
  'fa-window',
  'fa-window-alt',
  'fa-window-close',
  'fa-window-maximize',
  'fa-window-minimize',
  'fa-window-restore',
  'fa-wine-glass',
  'fa-wine-glass-alt',
  'fa-won-sign',
  'fa-wrench',
  'fa-x-ray',
  'fa-yen-sign'
];

export const solid: string[] = icons.map(color => `fas ${color}`);

export const regular: string[] = icons.map(color => `far ${color}`);

export const light: string[] = icons.map(color => `fal ${color}`);

export const brand: string[] = [
  'fab fa-accessible-icon',
  'fab fa-accusoft',
  'fab fa-adn',
  'fab fa-adversal',
  'fab fa-affiliatetheme',
  'fab fa-algolia',
  'fab fa-amazon',
  'fab fa-amazon-pay',
  'fab fa-amilia',
  'fab fa-android',
  'fab fa-angellist',
  'fab fa-angrycreative',
  'fab fa-angular',
  'fab fa-apper',
  'fab fa-apple',
  'fab fa-apple-pay',
  'fab fa-app-store',
  'fab fa-app-store-ios',
  'fab fa-asymmetrik',
  'fab fa-audible',
  'fab fa-autoprefixer',
  'fab fa-avianex',
  'fab fa-aviato',
  'fab fa-aws',
  'fab fa-bandcamp',
  'fab fa-behance',
  'fab fa-behance-square',
  'fab fa-bimobject',
  'fab fa-bitbucket',
  'fab fa-bitcoin',
  'fab fa-bity',
  'fab fa-blackberry',
  'fab fa-black-tie',
  'fab fa-blogger',
  'fab fa-blogger-b',
  'fab fa-bluetooth',
  'fab fa-bluetooth-b',
  'fab fa-btc',
  'fab fa-buromobelexperte',
  'fab fa-buysellads',
  'fab fa-cc-amazon-pay',
  'fab fa-cc-amex',
  'fab fa-cc-apple-pay',
  'fab fa-cc-diners-club',
  'fab fa-cc-discover',
  'fab fa-cc-jcb',
  'fab fa-cc-mastercard',
  'fab fa-cc-paypal',
  'fab fa-cc-stripe',
  'fab fa-cc-visa',
  'fab fa-centercode',
  'fab fa-cloudscale',
  'fab fa-cloudsmith',
  'fab fa-cloudversify',
  'fab fa-codepen',
  'fab fa-codiepie',
  'fab fa-connectdevelop',
  'fab fa-contao',
  'fab fa-cpanel',
  'fab fa-creative-commons',
  'fab fa-creative-commons-by',
  'fab fa-creative-commons-nc',
  'fab fa-creative-commons-nc-eu',
  'fab fa-creative-commons-nc-jp',
  'fab fa-creative-commons-nd',
  'fab fa-creative-commons-pd',
  'fab fa-creative-commons-pd-alt',
  'fab fa-creative-commons-remix',
  'fab fa-creative-commons-sa',
  'fab fa-creative-commons-sampling',
  'fab fa-creative-commons-sampling-plus',
  'fab fa-creative-commons-share',
  'fab fa-creative-commons-zero',
  'fab fa-css3',
  'fab fa-css3-alt',
  'fab fa-cuttlefish',
  'fab fa-d-and-d',
  'fab fa-dashcube',
  'fab fa-delicious',
  'fab fa-deploydog',
  'fab fa-deskpro',
  'fab fa-deviantart',
  'fab fa-digg',
  'fab fa-digital-ocean',
  'fab fa-discord',
  'fab fa-discourse',
  'fab fa-docker',
  'fab fa-dochub',
  'fab fa-draft2digital',
  'fab fa-dribbble',
  'fab fa-dribbble-square',
  'fab fa-dropbox',
  'fab fa-drupal',
  'fab fa-dyalog',
  'fab fa-earlybirds',
  'fab fa-ebay',
  'fab fa-edge',
  'fab fa-elementor',
  'fab fa-ember',
  'fab fa-empire',
  'fab fa-envira',
  'fab fa-erlang',
  'fab fa-ethereum',
  'fab fa-etsy',
  'fab fa-expeditedssl',
  'fab fa-facebook',
  'fab fa-facebook-f',
  'fab fa-facebook-messenger',
  'fab fa-facebook-square',
  'fab fa-firefox',
  'fab fa-firstdraft',
  'fab fa-first-order',
  'fab fa-first-order-alt',
  'fab fa-flickr',
  'fab fa-flipboard',
  'fab fa-fly',
  'fab fa-font-awesome',
  'fab fa-font-awesome-alt',
  'fab fa-font-awesome-flag',
  'fab fa-font-awesome-logo-full',
  'fab fa-fonticons',
  'fab fa-fonticons-fi',
  'fab fa-fort-awesome',
  'fab fa-fort-awesome-alt',
  'fab fa-forumbee',
  'fab fa-foursquare',
  'fab fa-freebsd',
  'fab fa-free-code-camp',
  'fab fa-fulcrum',
  'fab fa-galactic-republic',
  'fab fa-galactic-senate',
  'fab fa-get-pocket',
  'fab fa-gg',
  'fab fa-gg-circle',
  'fab fa-git',
  'fab fa-github',
  'fab fa-github-alt',
  'fab fa-github-square',
  'fab fa-gitkraken',
  'fab fa-gitlab',
  'fab fa-git-square',
  'fab fa-gitter',
  'fab fa-glide',
  'fab fa-glide-g',
  'fab fa-gofore',
  'fab fa-goodreads',
  'fab fa-goodreads-g',
  'fab fa-google',
  'fab fa-google-drive',
  'fab fa-google-play',
  'fab fa-google-plus',
  'fab fa-google-plus-g',
  'fab fa-google-plus-square',
  'fab fa-google-wallet',
  'fab fa-gratipay',
  'fab fa-grav',
  'fab fa-gripfire',
  'fab fa-grunt',
  'fab fa-gulp',
  'fab fa-hacker-news',
  'fab fa-hacker-news-square',
  'fab fa-hips',
  'fab fa-hire-a-helper',
  'fab fa-hooli',
  'fab fa-hornbill',
  'fab fa-hotjar',
  'fab fa-houzz',
  'fab fa-html5',
  'fab fa-hubspot',
  'fab fa-chrome',
  'fab fa-imdb',
  'fab fa-instagram',
  'fab fa-internet-explorer',
  'fab fa-ioxhost',
  'fab fa-itunes',
  'fab fa-itunes-note',
  'fab fa-java',
  'fab fa-jedi-order',
  'fab fa-jenkins',
  'fab fa-joget',
  'fab fa-joomla',
  'fab fa-js',
  'fab fa-jsfiddle',
  'fab fa-js-square',
  'fab fa-keybase',
  'fab fa-keycdn',
  'fab fa-kickstarter',
  'fab fa-kickstarter-k',
  'fab fa-korvue',
  'fab fa-laravel',
  'fab fa-lastfm',
  'fab fa-lastfm-square',
  'fab fa-leanpub',
  'fab fa-less',
  'fab fa-line',
  'fab fa-linkedin',
  'fab fa-linkedin-in',
  'fab fa-linode',
  'fab fa-linux',
  'fab fa-lyft',
  'fab fa-magento',
  'fab fa-mailchimp',
  'fab fa-mandalorian',
  'fab fa-mastodon',
  'fab fa-maxcdn',
  'fab fa-medapps',
  'fab fa-medium',
  'fab fa-medium-m',
  'fab fa-medrt',
  'fab fa-meetup',
  'fab fa-megaport',
  'fab fa-microsoft',
  'fab fa-mix',
  'fab fa-mixcloud',
  'fab fa-mizuni',
  'fab fa-modx',
  'fab fa-monero',
  'fab fa-napster',
  'fab fa-nimblr',
  'fab fa-nintendo-switch',
  'fab fa-node',
  'fab fa-node-js',
  'fab fa-npm',
  'fab fa-ns8',
  'fab fa-nutritionix',
  'fab fa-odnoklassniki',
  'fab fa-odnoklassniki-square',
  'fab fa-old-republic',
  'fab fa-opencart',
  'fab fa-openid',
  'fab fa-opera',
  'fab fa-optin-monster',
  'fab fa-osi',
  'fab fa-pagelines',
  'fab fa-page4',
  'fab fa-palfed',
  'fab fa-patreon',
  'fab fa-paypal',
  'fab fa-periscope',
  'fab fa-phabricator',
  'fab fa-phoenix-framework',
  'fab fa-phoenix-squadron',
  'fab fa-php',
  'fab fa-pied-piper',
  'fab fa-pied-piper-alt',
  'fab fa-pied-piper-hat',
  'fab fa-pied-piper-pp',
  'fab fa-pinterest',
  'fab fa-pinterest-p',
  'fab fa-pinterest-square',
  'fab fa-playstation',
  'fab fa-product-hunt',
  'fab fa-pushed',
  'fab fa-python',
  'fab fa-qq',
  'fab fa-quinscape',
  'fab fa-quora',
  'fab fa-ravelry',
  'fab fa-react',
  'fab fa-readme',
  'fab fa-rebel',
  'fab fa-reddit',
  'fab fa-reddit-alien',
  'fab fa-reddit-square',
  'fab fa-red-river',
  'fab fa-rendact',
  'fab fa-renren',
  'fab fa-replyd',
  'fab fa-researchgate',
  'fab fa-resolving',
  'fab fa-rev',
  'fab fa-rocketchat',
  'fab fa-rockrms',
  'fab fa-r-project',
  'fab fa-safari',
  'fab fa-sass',
  'fab fa-scribd',
  'fab fa-searchengin',
  'fab fa-sellcast',
  'fab fa-sellsy',
  'fab fa-servicestack',
  'fab fa-shirtsinbulk',
  'fab fa-shopware',
  'fab fa-schlix',
  'fab fa-simplybuilt',
  'fab fa-sistrix',
  'fab fa-sith',
  'fab fa-skyatlas',
  'fab fa-skype',
  'fab fa-slack',
  'fab fa-slack-hash',
  'fab fa-slideshare',
  'fab fa-snapchat',
  'fab fa-snapchat-ghost',
  'fab fa-snapchat-square',
  'fab fa-soundcloud',
  'fab fa-speakap',
  'fab fa-spotify',
  'fab fa-squarespace',
  'fab fa-stack-exchange',
  'fab fa-stack-overflow',
  'fab fa-staylinked',
  'fab fa-steam',
  'fab fa-steam-square',
  'fab fa-steam-symbol',
  'fab fa-sticker-mule',
  'fab fa-strava',
  'fab fa-stripe',
  'fab fa-stripe-s',
  'fab fa-studiovinari',
  'fab fa-stumbleupon',
  'fab fa-stumbleupon-circle',
  'fab fa-superpowers',
  'fab fa-supple',
  'fab fa-teamspeak',
  'fab fa-telegram',
  'fab fa-telegram-plane',
  'fab fa-tencent-weibo',
  'fab fa-themeco',
  'fab fa-themeisle',
  'fab fa-trade-federation',
  'fab fa-trello',
  'fab fa-tripadvisor',
  'fab fa-tumblr',
  'fab fa-tumblr-square',
  'fab fa-twitch',
  'fab fa-twitter',
  'fab fa-twitter-square',
  'fab fa-typo3',
  'fab fa-uber',
  'fab fa-uikit',
  'fab fa-uniregistry',
  'fab fa-untappd',
  'fab fa-usb',
  'fab fa-ussunnah',
  'fab fa-vaadin',
  'fab fa-viacoin',
  'fab fa-viadeo',
  'fab fa-viadeo-square',
  'fab fa-viber',
  'fab fa-vimeo',
  'fab fa-vimeo-square',
  'fab fa-vimeo-v',
  'fab fa-vine',
  'fab fa-vk',
  'fab fa-vnv',
  'fab fa-vuejs',
  'fab fa-weebly',
  'fab fa-weibo',
  'fab fa-weixin',
  'fab fa-whatsapp',
  'fab fa-whatsapp-square',
  'fab fa-whmcs',
  'fab fa-wikipedia-w',
  'fab fa-windows',
  'fab fa-wix',
  'fab fa-wolf-pack-battalion',
  'fab fa-wordpress',
  'fab fa-wordpress-simple',
  'fab fa-wpbeginner',
  'fab fa-wpexplorer',
  'fab fa-wpforms',
  'fab fa-xbox',
  'fab fa-xing',
  'fab fa-xing-square',
  'fab fa-yahoo',
  'fab fa-yandex',
  'fab fa-yandex-international',
  'fab fa-y-combinator',
  'fab fa-yelp',
  'fab fa-yoast',
  'fab fa-youtube',
  'fab fa-youtube-square',
  'fab fa-500px'
];

const iconsMeta = new Map<string, string[]>([
  ['500px', ['accessible-icon', 'accessibility', 'handicap', 'person', 'wheelchair', 'wheelchair-alt']],
  ['accusoft', ['accusoft']],
  ['address-book', ['address-book']],
  ['address-card', ['address-card']],
  ['adjust', ['adjust', 'contrast']],
  ['adn', ['adn']],
  ['adversal', ['adversal']],
  ['affiliatetheme', ['affiliatetheme']],
  ['alarm-clock', ['alarm-clock', 'date', 'late', 'timer', 'timestamp', 'watch']],
  ['algolia', ['algolia']],
  ['align-center', ['align-center', 'middle', 'text']],
  ['align-justify', ['align-justify', 'text']],
  ['align-left', ['align-left', 'text']],
  ['align-right', ['align-right', 'text']],
  ['allergies', ['allergies', 'freckles', 'hand', 'intolerances', 'pox', 'spots']],
  ['amazon', ['amazon']],
  ['amazon-pay', ['amazon-pay']],
  ['ambulance', ['ambulance', 'help', 'machine', 'support', 'vehicle']],
  ['american-sign-language-interpreting', ['american-sign-language-interpreting']],
  ['amilia', ['amilia']],
  ['anchor', ['anchor', 'link']],
  ['android', ['android', 'robot']],
  ['angellist', ['angellist']],
  ['angle-double-down', ['angle-double-down', 'arrows']],
  ['angle-double-left', ['angle-double-left', 'arrows', 'back', 'laquo', 'previous', 'quote']],
  ['angle-double-right', ['angle-double-right', 'arrows', 'forward', 'next', 'quote', 'raquo']],
  ['angle-double-up', ['angle-double-up', 'arrows']],
  ['angle-down', ['angle-down', 'arrow']],
  ['angle-left', ['angle-left', 'arrow', 'back', 'previous']],
  ['angle-right', ['angle-right', 'arrow', 'forward', 'next']],
  ['angle-up', ['angle-up', 'arrow']],
  ['angry', ['angry']],
  ['angrycreative', ['angrycreative']],
  ['angular', ['angular']],
  ['app-store', ['app-store']],
  ['app-store-ios', ['app-store-ios']],
  ['apper', ['apper']],
  ['apple', ['apple', 'food', 'fruit', 'osx']],
  ['apple-pay', ['apple-pay']],
  ['archive', ['archive', 'box', 'package', 'storage']],
  ['archway', ['archway', 'monument', 'road', 'street']],
  ['arrow-alt-circle-down', ['arrow-alt-circle-down', 'arrow-circle-o-down', 'download']],
  ['arrow-alt-circle-left', ['arrow-alt-circle-left', 'arrow-circle-o-left', 'back', 'previous']],
  ['arrow-alt-circle-right', ['arrow-alt-circle-right', 'arrow-circle-o-right', 'forward', 'next']],
  ['arrow-alt-circle-up', ['arrow-alt-circle-up', 'arrow-circle-o-up']],
  ['arrow-alt-down', ['arrow-alt-down']],
  ['arrow-alt-from-bottom', ['arrow-alt-from-bottom', 'download']],
  ['arrow-alt-from-left', ['arrow-alt-from-left', 'back', 'previous']],
  ['arrow-alt-from-right', ['arrow-alt-from-right', 'forward', 'next']],
  ['arrow-alt-from-top', ['arrow-alt-from-top']],
  ['arrow-alt-left', ['arrow-alt-left', 'back', 'previous']],
  ['arrow-alt-right', ['arrow-alt-right', 'forward', 'next']],
  ['arrow-alt-square-down', ['arrow-alt-square-down']],
  ['arrow-alt-square-left', ['arrow-alt-square-left', 'back', 'previous']],
  ['arrow-alt-square-right', ['arrow-alt-square-right', 'forward', 'next']],
  ['arrow-alt-square-up', ['arrow-alt-square-up']],
  ['arrow-alt-to-bottom', ['arrow-alt-to-bottom', 'download']],
  ['arrow-alt-to-left', ['arrow-alt-to-left', 'back', 'previous']],
  ['arrow-alt-to-right', ['arrow-alt-to-right', 'forward', 'next']],
  ['arrow-alt-to-top', ['arrow-alt-to-top']],
  ['arrow-alt-up', ['arrow-alt-up']],
  ['arrow-circle-down', ['arrow-circle-down', 'download']],
  ['arrow-circle-left', ['arrow-circle-left', 'back', 'previous']],
  ['arrow-circle-right', ['arrow-circle-right', 'forward', 'next']],
  ['arrow-circle-up', ['arrow-circle-up']],
  ['arrow-down', ['arrow-down', 'download']],
  ['arrow-from-bottom', ['arrow-from-bottom', 'download']],
  ['arrow-from-left', ['arrow-from-left', 'back', 'previous']],
  ['arrow-from-right', ['arrow-from-right', 'forward', 'next']],
  ['arrow-from-top', ['arrow-from-top']],
  ['arrow-left', ['arrow-left', 'back', 'previous']],
  ['arrow-right', ['arrow-right', 'forward', 'next']],
  ['arrow-square-down', ['arrow-square-down']],
  ['arrow-square-left', ['arrow-square-left', 'back', 'previous']],
  ['arrow-square-right', ['arrow-square-right', 'forward', 'next']],
  ['arrow-square-up', ['arrow-square-up']],
  ['arrow-to-bottom', ['arrow-to-bottom', 'download']],
  ['arrow-to-left', ['arrow-to-left', 'back', 'previous']],
  ['arrow-to-right', ['arrow-to-right', 'forward', 'next']],
  ['arrow-to-top', ['arrow-to-top']],
  ['arrow-up', ['arrow-up']],
  ['arrows', ['arrows', 'move', 'position', 'reorder', 'resize']],
  ['arrows-alt', ['arrows-alt', 'arrow', 'arrows', 'bigger', 'enlarge', 'expand', 'fullscreen', 'move', 'position', 'reorder', 'resize']],
  ['arrows-alt-h', ['arrows-alt-h', 'arrows-h', 'resize']],
  ['arrows-alt-v', ['arrows-alt-v', 'arrows-v', 'resize']],
  ['arrows-h', ['arrows-h', 'resize']],
  ['arrows-v', ['arrows-v', 'resize']],
  ['assistive-listening-systems', ['assistive-listening-systems']],
  ['asterisk', ['asterisk', 'details']],
  ['asymmetrik', ['asymmetrik']],
  ['at', ['at', 'e-mail', 'email']],
  ['atlas', ['atlas', 'book', 'geography', 'map', 'wayfinding']],
  ['audible', ['audible']],
  ['audio-description', ['audio-description']],
  ['autoprefixer', ['autoprefixer']],
  ['avianex', ['avianex']],
  ['aviato', ['aviato']],
  ['award', ['award']],
  ['aws', ['aws']],
  ['backspace', ['backspace', 'command', 'delete', 'keyboard', 'undo']],
  ['backward', ['backward', 'previous', 'rewind']],
  ['badge', ['badge']],
  ['badge-check', ['badge-check', 'accept', 'achievement', 'agree', 'award', 'confirm', 'correct', 'done', 'ok', 'security', 'select', 'success', 'winner',
    'yes']],
  ['balance-scale', ['balance-scale', 'balanced', 'justice', 'legal', 'measure', 'weight']],
  ['balance-scale-left', ['balance-scale-left', 'justice', 'legal', 'measure', 'unbalanced', 'weight']],
  ['balance-scale-right', ['balance-scale-right', 'justice', 'legal', 'measure', 'unbalanced', 'weight']],
  ['ban', ['ban', 'abort', 'ban', 'block', 'cancel', 'delete', 'hide', 'prohibit', 'remove', 'stop', 'trash']],
  ['band-aid', ['band-aid', 'bandage', 'boo boo', 'ouch']],
  ['bandcamp', ['bandcamp']],
  ['barcode', ['barcode', 'scan']],
  ['barcode-alt', ['barcode-alt']],
  ['barcode-read', ['barcode-read']],
  ['barcode-scan', ['barcode-scan']],
  ['bars', ['bars', 'checklist', 'drag', 'hamburger', 'list', 'menu', 'nav', 'navigation', 'ol', 'reorder', 'settings', 'todo', 'ul']],
  ['baseball', ['baseball']],
  ['baseball-ball', ['baseball-ball']],
  ['basketball-ball', ['basketball-ball']],
  ['basketball-hoop', ['basketball-hoop']],
  ['bath', ['bath']],
  ['battery-bolt', ['battery-bolt', 'power', 'status']],
  ['battery-empty', ['battery-empty', 'power', 'status']],
  ['battery-full', ['battery-full', 'power', 'status']],
  ['battery-half', ['battery-half', 'power', 'status']],
  ['battery-quarter', ['battery-quarter', 'power', 'status']],
  ['battery-slash', ['battery-slash', 'power', 'status']],
  ['battery-three-quarters', ['battery-three-quarters', 'power', 'status']],
  ['bed', ['bed', 'travel']],
  ['beer', ['beer', 'alcohol', 'bar', 'drink', 'liquor', 'mug', 'stein']],
  ['behance', ['behance']],
  ['behance-square', ['behance-square']],
  ['bell', ['bell', 'alert', 'notification', 'reminder']],
  ['bell-slash', ['bell-slash']],
  ['bezier-curve', ['bezier-curve', 'curves', 'illustrator', 'lines', 'path', 'vector']],
  ['bicycle', ['bicycle', 'bike', 'gears', 'transportation', 'vehicle']],
  ['bimobject', ['bimobject']],
  ['binoculars', ['binoculars']],
  ['birthday-cake', ['birthday-cake']],
  ['bitbucket', ['bitbucket', 'bitbucket-square', 'git']],
  ['bitcoin', ['bitcoin']],
  ['bity', ['bity']],
  ['black-tie', ['black-tie']],
  ['blackberry', ['blackberry']],
  ['blanket', ['blanket']],
  ['blender', ['blender']],
  ['blind', ['blind']],
  ['blogger', ['blogger']],
  ['blogger-b', ['blogger-b']],
  ['bluetooth', ['bluetooth']],
  ['bluetooth-b', ['bluetooth-b']],
  ['bold', ['bold']],
  ['bolt', ['bolt', 'electricity', 'lightning', 'weather', 'zap']],
  ['bomb', ['bomb']],
  ['bong', ['bong', 'aparatus', 'cannabis', 'marijuana', 'pipe', 'smoke', 'smoking']],
  ['book', ['book', 'documentation', 'read']],
  ['book-heart', ['book-heart']],
  ['book-open', ['book-open', 'notebook', 'open book', 'reading']],
  ['bookmark', ['bookmark', 'save']],
  ['bowling-ball', ['bowling-ball']],
  ['bowling-pins', ['bowling-pins']],
  ['box', ['box', 'package']],
  ['box-alt', ['box-alt']],
  ['box-check', ['box-check', 'accept', 'ackage', 'agree', 'confirm', 'correct', 'done', 'ok', 'select', 'success', 'todo', 'yes']],
  ['box-fragile', ['box-fragile', 'package']],
  ['box-full', ['box-full', 'package', 'packed']],
  ['box-heart', ['box-heart', 'care', 'package']],
  ['box-open', ['box-open']],
  ['box-up', ['box-up']],
  ['box-usd', ['box-usd', '$', 'dollar-sign', 'money', 'usd']],
  ['boxes', ['boxes']],
  ['boxes-alt', ['boxes-alt']],
  ['boxing-glove', ['boxing-glove']],
  ['braille', ['braille']],
  ['briefcase', ['briefcase', 'bag', 'business', 'luggage', 'office', 'work']],
  ['briefcase-medical', ['briefcase-medical', 'health briefcase']],
  ['broadcast-tower', ['broadcast-tower', 'airwaves', 'radio', 'waves']],
  ['broom', ['broom']],
  ['browser', ['browser', 'website']],
  ['brush', ['brush', 'bristles', 'color', 'painting']],
  ['btc', ['btc']],
  ['bug', ['bug', 'insect', 'report']],
  ['building', ['building', 'apartment', 'business', 'company', 'office', 'work']],
  ['bullhorn', ['bullhorn', 'announcement', 'broadcast', 'louder', 'megaphone', 'share']],
  ['bullseye', ['bullseye', 'target']],
  ['burn', ['burn', 'energy']],
  ['buromobelexperte', ['buromobelexperte']],
  ['bus', ['bus', 'machine', 'public transportation', 'transportation', 'vehicle']],
  ['bus-alt', ['bus-alt', 'machine', 'public transportation', 'transportation', 'vehicle']],
  ['buysellads', ['buysellads']],
  ['calculator', ['calculator']],
  ['calendar', ['calendar', 'calendar-o', 'date', 'event', 'schedule', 'time', 'when']],
  ['calendar-alt', ['calendar-alt', 'calendar', 'date', 'event', 'schedule', 'time', 'when']],
  ['calendar-check', ['calendar-check', 'accept', 'agree', 'appointment', 'confirm', 'correct', 'done', 'ok', 'select', 'success', 'todo']],
  ['calendar-edit', ['calendar-edit']],
  ['calendar-exclamation', ['calendar-exclamation', 'important']],
  ['calendar-minus', ['calendar-minus']],
  ['calendar-plus', ['calendar-plus']],
  ['calendar-times', ['calendar-times']],
  ['camera', ['camera', 'photo', 'picture', 'record']],
  ['camera-alt', ['camera-alt', 'photo', 'picture', 'record']],
  ['camera-retro', ['camera-retro', 'photo', 'picture', 'record']],
  ['cannabis', ['cannabis', 'bud', 'chronic', 'drugs', 'endica', 'endo', 'ganja', 'marijuana', 'mary jane', 'pot', 'reefer', 'sativa', 'spliff', 'weed',
    'whacky-tabacky']],
  ['capsules', ['capsules', 'drugs', 'medicine']],
  ['car', ['car', 'machine', 'transportation', 'vehicle']],
  ['caret-circle-down', ['caret-circle-down', 'dropdown', 'menu', 'more']],
  ['caret-circle-left', ['caret-circle-left', 'back', 'previous']],
  ['caret-circle-right', ['caret-circle-right', 'forward', 'next']],
  ['caret-circle-up', ['caret-circle-up']],
  ['caret-down', ['caret-down', 'arrow', 'dropdown', 'menu', 'more', 'triangle down']],
  ['caret-left', ['caret-left', 'arrow', 'back', 'previous', 'triangle left']],
  ['caret-right', ['caret-right', 'arrow', 'forward', 'next', 'triangle right']],
  ['caret-square-down', ['caret-square-down', 'caret-square-o-down', 'dropdown', 'menu', 'more']],
  ['caret-square-left', ['caret-square-left', 'back', 'caret-square-o-left', 'previous']],
  ['caret-square-right', ['caret-square-right', 'caret-square-o-right', 'forward', 'next']],
  ['caret-square-up', ['caret-square-up', 'caret-square-o-up']],
  ['caret-up', ['caret-up', 'arrow', 'triangle up']],
  ['cart-arrow-down', ['cart-arrow-down', 'shopping']],
  ['cart-plus', ['cart-plus', 'add', 'shopping']],
  ['cc-amazon-pay', ['cc-amazon-pay']],
  ['cc-amex', ['cc-amex', 'amex']],
  ['cc-apple-pay', ['cc-apple-pay']],
  ['cc-diners-club', ['cc-diners-club']],
  ['cc-discover', ['cc-discover']],
  ['cc-jcb', ['cc-jcb']],
  ['cc-mastercard', ['cc-mastercard']],
  ['cc-paypal', ['cc-paypal']],
  ['cc-stripe', ['cc-stripe']],
  ['cc-visa', ['cc-visa']],
  ['centercode', ['centercode']],
  ['certificate', ['certificate', 'badge', 'star']],
  ['chalkboard', ['chalkboard', 'blackboard', 'learning', 'school', 'teaching', 'whiteboard', 'writing']],
  ['chalkboard-teacher', ['chalkboard-teacher', 'blackboard', 'instructor', 'learning', 'professor', 'school', 'whiteboard', 'writing']],
  ['chart-area', ['chart-area', 'analytics', 'area-chart', 'graph']],
  ['chart-bar', ['chart-bar', 'analytics', 'bar-chart', 'graph']],
  ['chart-line', ['chart-line', 'activity', 'analytics', 'dashboard', 'graph', 'line-chart']],
  ['chart-pie', ['chart-pie', 'analytics', 'graph', 'pie-chart']],
  ['check', ['check', 'accept', 'agree', 'checkmark', 'confirm', 'correct', 'done', 'notice', 'notification', 'notify', 'ok', 'select', 'success', 'tick',
    'todo', 'yes']],
  ['check-circle', ['check-circle', 'accept', 'agree', 'confirm', 'correct', 'done', 'ok', 'select', 'success', 'todo', 'yes']],
  ['check-double', ['check-double']],
  ['check-square', ['check-square', 'accept', 'agree', 'checkmark', 'confirm', 'correct', 'done', 'ok', 'select', 'success', 'todo', 'yes']],
  ['chess', ['chess']],
  ['chess-bishop', ['chess-bishop']],
  ['chess-bishop-alt', ['chess-bishop-alt']],
  ['chess-board', ['chess-board']],
  ['chess-clock', ['chess-clock']],
  ['chess-clock-alt', ['chess-clock-alt']],
  ['chess-king', ['chess-king']],
  ['chess-king-alt', ['chess-king-alt']],
  ['chess-knight', ['chess-knight']],
  ['chess-knight-alt', ['chess-knight-alt']],
  ['chess-pawn', ['chess-pawn']],
  ['chess-pawn-alt', ['chess-pawn-alt']],
  ['chess-queen', ['chess-queen']],
  ['chess-queen-alt', ['chess-queen-alt']],
  ['chess-rook', ['chess-rook']],
  ['chess-rook-alt', ['chess-rook-alt']],
  ['chevron-circle-down', ['chevron-circle-down', 'arrow', 'dropdown', 'menu', 'more']],
  ['chevron-circle-left', ['chevron-circle-left', 'arrow', 'back', 'previous']],
  ['chevron-circle-right', ['chevron-circle-right', 'arrow', 'forward', 'next']],
  ['chevron-circle-up', ['chevron-circle-up', 'arrow']],
  ['chevron-double-down', ['chevron-double-down']],
  ['chevron-double-left', ['chevron-double-left', 'back', 'bracket', 'previous']],
  ['chevron-double-right', ['chevron-double-right', 'bracket', 'forward', 'next']],
  ['chevron-double-up', ['chevron-double-up']],
  ['chevron-down', ['chevron-down']],
  ['chevron-left', ['chevron-left', 'back', 'bracket', 'previous']],
  ['chevron-right', ['chevron-right', 'bracket', 'forward', 'next']],
  ['chevron-square-down', ['chevron-square-down', 'arrow', 'dropdown', 'menu', 'more']],
  ['chevron-square-left', ['chevron-square-left', 'arrow', 'back', 'previous']],
  ['chevron-square-right', ['chevron-square-right', 'arrow', 'forward', 'next']],
  ['chevron-square-up', ['chevron-square-up', 'arrow']],
  ['chevron-up', ['chevron-up']],
  ['child', ['child']],
  ['chrome', ['chrome', 'browser']],
  ['church', ['church', 'building', 'community', 'religion']],
  ['circle', ['circle', 'circle-thin', 'dot', 'notification']],
  ['circle-notch', ['circle-notch', 'circle-o-notch']],
  ['clipboard', ['clipboard', 'paste']],
  ['clipboard-check', ['clipboard-check', 'accept', 'agree', 'confirm', 'done', 'ok', 'select', 'success', 'todo', 'yes']],
  ['clipboard-list', ['clipboard-list', 'checklist', 'completed', 'done', 'finished', 'intinerary', 'ol', 'schedule', 'todo', 'ul']],
  ['clock', ['clock', 'date', 'late', 'schedule', 'timer', 'timestamp', 'watch']],
  ['clone', ['clone', 'copy', 'duplicate']],
  ['closed-captioning', ['closed-captioning', 'cc']],
  ['cloud', ['cloud', 'save']],
  ['cloud-download', ['cloud-download', 'import']],
  ['cloud-download-alt', ['cloud-download-alt', 'cloud-download']],
  ['cloud-upload', ['cloud-upload', 'import']],
  ['cloud-upload-alt', ['cloud-upload-alt', 'cloud-upload']],
  ['cloudscale', ['cloudscale']],
  ['cloudsmith', ['cloudsmith']],
  ['cloudversify', ['cloudversify']],
  ['club', ['club', 'card', 'suit']],
  ['cocktail', ['cocktail', 'alcohol', 'drink']],
  ['code', ['code', 'brackets', 'html']],
  ['code-branch', ['code-branch', 'branch', 'code-fork', 'fork', 'git', 'github', 'rebase', 'svn', 'vcs', 'version']],
  ['code-commit', ['code-commit', 'commit', 'git', 'github', 'hash', 'rebase', 'svn', 'vcs', 'version']],
  ['code-merge', ['code-merge', 'git', 'github', 'merge', 'pr', 'rebase', 'svn', 'vcs', 'version']],
  ['codepen', ['codepen']],
  ['codiepie', ['codiepie']],
  ['coffee', ['coffee', 'breakfast', 'cafe', 'drink', 'morning', 'mug', 'tea']],
  ['cog', ['cog', 'settings']],
  ['cogs', ['cogs', 'gears', 'settings']],
  ['coins', ['coins']],
  ['columns', ['columns', 'dashboard', 'panes', 'split']],
  ['comment', ['comment', 'bubble', 'chat', 'conversation', 'feedback', 'message', 'note', 'notification', 'sms', 'speech', 'texting']],
  ['comment-alt', ['comment-alt', 'bubble', 'chat', 'commenting', 'commenting', 'conversation', 'feedback', 'message', 'note', 'notification', 'sms', 'speech',
    'texting']],
  ['comment-alt-check', ['comment-alt-check']],
  ['comment-alt-dots', ['comment-alt-dots']],
  ['comment-alt-edit', ['comment-alt-edit']],
  ['comment-alt-exclamation', ['comment-alt-exclamation', 'important']],
  ['comment-alt-lines', ['comment-alt-lines']],
  ['comment-alt-minus', ['comment-alt-minus']],
  ['comment-alt-plus', ['comment-alt-plus']],
  ['comment-alt-slash', ['comment-alt-slash']],
  ['comment-alt-smile', ['comment-alt-smile']],
  ['comment-alt-times', ['comment-alt-times']],
  ['comment-check', ['comment-check']],
  ['comment-dots', ['comment-dots']],
  ['comment-edit', ['comment-edit']],
  ['comment-exclamation', ['comment-exclamation', 'important']],
  ['comment-lines', ['comment-lines']],
  ['comment-minus', ['comment-minus']],
  ['comment-plus', ['comment-plus']],
  ['comment-slash', ['comment-slash']],
  ['comment-smile', ['comment-smile']],
  ['comment-times', ['comment-times']],
  ['comments', ['comments', 'bubble', 'chat', 'conversation', 'feedback', 'message', 'note', 'notification', 'sms', 'speech', 'texting']],
  ['comments-alt', ['comments-alt']],
  ['compact-disc', ['compact-disc', 'bluray', 'cd', 'disc', 'media']],
  ['compass', ['compass', 'directory', 'location', 'menu', 'safari']],
  ['compress', ['compress', 'collapse', 'combine', 'contract', 'merge', 'smaller']],
  ['compress-alt', ['compress-alt', 'collapse', 'combine', 'contract', 'merge', 'smaller']],
  ['compress-wide', ['compress-wide', 'collapse', 'combine', 'contract', 'merge', 'smaller']],
  ['concierge-bell', ['concierge-bell', 'attention', 'hotel', 'service', 'support']],
  ['connectdevelop', ['connectdevelop']],
  ['container-storage', ['container-storage']],
  ['contao', ['contao']],
  ['conveyor-belt', ['conveyor-belt']],
  ['conveyor-belt-alt', ['conveyor-belt-alt']],
  ['cookie', ['cookie']],
  ['cookie-bite', ['cookie-bite']],
  ['copy', ['copy', 'clone', 'duplicate', 'file', 'files-o']],
  ['copyright', ['copyright']],
  ['couch', ['couch']],
  ['cpanel', ['cpanel']],
  ['creative-commons', ['creative-commons']],
  ['creative-commons-by', ['creative-commons-by']],
  ['creative-commons-nc', ['creative-commons-nc']],
  ['creative-commons-nc-eu', ['creative-commons-nc-eu']],
  ['creative-commons-nc-jp', ['creative-commons-nc-jp']],
  ['creative-commons-nd', ['creative-commons-nd']],
  ['creative-commons-pd', ['creative-commons-pd']],
  ['creative-commons-pd-alt', ['creative-commons-pd-alt']],
  ['creative-commons-remix', ['creative-commons-remix']],
  ['creative-commons-sa', ['creative-commons-sa']],
  ['creative-commons-sampling', ['creative-commons-sampling']],
  ['creative-commons-sampling-plus', ['creative-commons-sampling-plus']],
  ['creative-commons-share', ['creative-commons-share']],
  ['creative-commons-zero', ['creative-commons-zero']],
  ['credit-card', ['credit-card', 'buy', 'checkout', 'credit-card-alt', 'debit', 'money', 'payment', 'purchase']],
  ['credit-card-blank', ['credit-card-blank', 'buy', 'checkout', 'debit', 'money', 'payment', 'purchase']],
  ['credit-card-front', ['credit-card-front', 'buy', 'checkout', 'chip', 'debit', 'money', 'payment', 'purchase']],
  ['cricket', ['cricket']],
  ['crop', ['crop', 'design']],
  ['crop-alt', ['crop-alt']],
  ['crosshairs', ['crosshairs', 'gpd', 'picker', 'position']],
  ['crow', ['crow', 'bird', 'bullfrog', 'toad']],
  ['crown', ['crown']],
  ['css3', ['css3', 'code']],
  ['css3-alt', ['css3']],
  ['cube', ['cube', 'package']],
  ['cubes', ['cubes', 'packages']],
  ['curling', ['curling']],
  ['cut', ['cut', 'scissors', 'scissors']],
  ['cuttlefish', ['cuttlefish']],
  ['d-and-d', ['d-and-d']],
  ['dashcube', ['dashcube']],
  ['database', ['database']],
  ['deaf', ['deaf']],
  ['delicious', ['delicious']],
  ['deploydog', ['deploydog']],
  ['deskpro', ['deskpro']],
  ['desktop', ['desktop', 'computer', 'cpu', 'demo', 'desktop', 'device', 'machine', 'monitor', 'pc', 'screen']],
  ['desktop-alt', ['desktop-alt', 'apple', 'computer', 'cpu', 'demo', 'desktop', 'device', 'imac', 'machine', 'monitor', 'screen']],
  ['deviantart', ['deviantart']],
  ['diagnoses', ['diagnoses']],
  ['diamond', ['diamond', 'gem', 'gemstone']],
  ['dice', ['dice', 'chance', 'gambling', 'game', 'roll']],
  ['dice-five', ['dice-five', 'chance', 'gambling', 'game', 'roll']],
  ['dice-four', ['dice-four', 'chance', 'gambling', 'game', 'roll']],
  ['dice-one', ['dice-one', 'chance', 'gambling', 'game', 'roll']],
  ['dice-six', ['dice-six', 'chance', 'gambling', 'game', 'roll']],
  ['dice-three', ['dice-three', 'chance', 'gambling', 'game', 'roll']],
  ['dice-two', ['dice-two', 'chance', 'gambling', 'game', 'roll']],
  ['digg', ['digg']],
  ['digital-ocean', ['digital-ocean']],
  ['digital-tachograph', ['digital-tachograph']],
  ['discord', ['discord']],
  ['discourse', ['discourse']],
  ['divide', ['divide']],
  ['dizzy', ['dizzy']],
  ['dna', ['dna', 'double helix', 'helix']],
  ['dochub', ['dochub']],
  ['docker', ['docker']],
  ['dollar-sign', ['dollar-sign', '$', 'money', 'price', 'usd']],
  ['dolly', ['dolly']],
  ['dolly-empty', ['dolly-empty']],
  ['dolly-flatbed', ['dolly-flatbed']],
  ['dolly-flatbed-alt', ['dolly-flatbed-alt']],
  ['dolly-flatbed-empty', ['dolly-flatbed-empty']],
  ['donate', ['donate', 'generosity', 'give']],
  ['door-closed', ['door-closed']],
  ['door-open', ['door-open']],
  ['dot-circle', ['dot-circle', 'bullseye', 'notification', 'target']],
  ['dove', ['dove']],
  ['download', ['download', 'import']],
  ['draft2digital', ['draft2digital']],
  ['drafting-compass', ['drafting-compass']],
  ['dribbble', ['dribbble']],
  ['dribbble-square', ['dribbble-square']],
  ['dropbox', ['dropbox']],
  ['drum', ['drum']],
  ['drum-steelpan', ['drum-steelpan']],
  ['drupal', ['drupal']],
  ['dumbbell', ['dumbbell', 'exercise', 'gym', 'strength', 'weight', 'weight-lifting']],
  ['dyalog', ['dyalog']],
  ['earlybirds', ['earlybirds']],
  ['ebay', ['ebay']],
  ['edge', ['edge', 'browser', 'ie']],
  ['edit', ['edit', 'edit', 'pen', 'pencil', 'update', 'write']],
  ['eject', ['eject']],
  ['elementor', ['elementor']],
  ['ellipsis-h', ['ellipsis-h', 'dots', 'drag', 'kebab', 'list', 'menu', 'nav', 'navigation', 'ol', 'reorder', 'settings', 'ul']],
  ['ellipsis-h-alt', ['ellipsis-h-alt', 'dots', 'drag', 'kebab', 'list', 'menu', 'nav', 'navigation', 'ol', 'reorder', 'settings', 'ul']],
  ['ellipsis-v', ['ellipsis-v', 'dots', 'drag', 'kebab', 'list', 'menu', 'nav', 'navigation', 'ol', 'reorder', 'settings', 'ul']],
  ['ellipsis-v-alt', ['ellipsis-v-alt', 'dots', 'drag', 'kebab', 'list', 'menu', 'nav', 'navigation', 'ol', 'reorder', 'settings', 'ul']],
  ['ember', ['ember']],
  ['empire', ['empire']],
  ['envelope', ['envelope', 'e-mail', 'email', 'letter', 'mail', 'message', 'notification', 'support']],
  ['envelope-open', ['envelope-open', 'e-mail', 'email', 'letter', 'mail', 'message', 'notification', 'support']],
  ['envelope-square', ['envelope-square', 'e-mail', 'email', 'letter', 'mail', 'message', 'notification', 'support']],
  ['envira', ['envira', 'leaf']],
  ['equals', ['equals']],
  ['eraser', ['eraser', 'delete', 'remove']],
  ['erlang', ['erlang']],
  ['ethereum', ['ethereum']],
  ['etsy', ['etsy']],
  ['euro-sign', ['euro-sign', 'eur', 'eur', '€']],
  ['exchange', ['exchange', 'arrow', 'arrows', 'reciprocate', 'return', 'swap', 'transfer']],
  ['exchange-alt', ['exchange-alt', 'arrow', 'arrows', 'exchange', 'reciprocate', 'return', 'swap', 'transfer']],
  ['exclamation', ['exclamation', 'alert', 'danger', 'error', 'important', 'notice', 'notification', 'notify', 'problem', 'warning']],
  ['exclamation-circle', ['exclamation-circle', 'alert', 'danger', 'error', 'important', 'notice', 'notification', 'notify', 'problem', 'warning']],
  ['exclamation-square', ['exclamation-square', 'alert', 'danger', 'error', 'important', 'notice', 'notification', 'notify', 'problem', 'warning']],
  ['exclamation-triangle', ['exclamation-triangle', 'alert', 'danger', 'error', 'important', 'notice', 'notification', 'notify', 'problem', 'warning']],
  ['expand', ['expand', 'bigger', 'enlarge', 'resize']],
  ['expand-alt', ['expand-alt', 'bigger', 'enlarge', 'resize']],
  ['expand-arrows', ['expand-arrows', 'bigger', 'enlarge', 'move', 'resize']],
  ['expand-arrows-alt', ['expand-arrows-alt', 'arrows-alt', 'bigger', 'enlarge', 'move', 'resize']],
  ['expand-wide', ['expand-wide', 'bigger', 'enlarge', 'resize']],
  ['expeditedssl', ['expeditedssl']],
  ['external-link', ['external-link', 'new', 'open']],
  ['external-link-alt', ['external-link-alt', 'external-link', 'new', 'open']],
  ['external-link-square', ['external-link-square', 'new', 'open']],
  ['external-link-square-alt', ['external-link-square-alt', 'external-link-square', 'new', 'open']],
  ['eye', ['eye', 'optic', 'see', 'seen', 'show', 'sight', 'views', 'visible']],
  ['eye-dropper', ['eye-dropper', 'eyedropper']],
  ['eye-slash', ['eye-slash', 'blind', 'hide', 'show', 'toggle', 'unseen', 'views', 'visible', 'visiblity']],
  ['facebook', ['facebook', 'facebook-official', 'social network']],
  ['facebook-f', ['facebook-f', 'facebook']],
  ['facebook-messenger', ['facebook-messenger']],
  ['facebook-square', ['facebook-square', 'social network']],
  ['fast-backward', ['fast-backward', 'beginning', 'first', 'previous', 'rewind', 'start']],
  ['fast-forward', ['fast-forward', 'end', 'last', 'next']],
  ['fax', ['fax']],
  ['feather', ['feather']],
  ['feather-alt', ['feather-alt']],
  ['female', ['female', 'human', 'person', 'profile', 'user', 'woman']],
  ['field-hockey', ['field-hockey']],
  ['fighter-jet', ['fighter-jet', 'airplane', 'fast', 'fly', 'goose', 'maverick', 'plane', 'quick', 'top gun', 'transportation', 'travel']],
  ['file', ['file', 'document', 'new', 'page', 'pdf', 'resume']],
  ['file-alt', ['file-alt', 'document', 'file-text', 'invoice', 'new', 'page', 'pdf']],
  ['file-archive', ['file-archive', '.zip', 'bundle', 'compress', 'compression', 'download', 'zip']],
  ['file-audio', ['file-audio']],
  ['file-check', ['file-check', 'accept', 'agree', 'confirm', 'done', 'ok', 'select', 'success', 'synced', 'todo']],
  ['file-code', ['file-code']],
  ['file-contract', ['file-contract', 'agreement', 'binding', 'document', 'legal', 'signature']],
  ['file-download', ['file-download']],
  ['file-edit', ['file-edit', 'pen']],
  ['file-excel', ['file-excel']],
  ['file-exclamation', ['file-exclamation', 'important']],
  ['file-export', ['file-export']],
  ['file-image', ['file-image']],
  ['file-import', ['file-import']],
  ['file-invoice', ['file-invoice', 'bill', 'document', 'receipt']],
  ['file-invoice-dollar', ['file-invoice-dollar', '$', 'bill', 'document', 'dollar-sign', 'money', 'receipt', 'usd']],
  ['file-medical', ['file-medical']],
  ['file-medical-alt', ['file-medical-alt']],
  ['file-minus', ['file-minus']],
  ['file-pdf', ['file-pdf']],
  ['file-plus', ['file-plus']],
  ['file-powerpoint', ['file-powerpoint']],
  ['file-prescription', ['file-prescription', 'drugs', 'medical', 'medicine', 'rx']],
  ['file-signature', ['file-signature', ',John Hancock', 'contract', 'document', 'name']],
  ['file-times', ['file-times']],
  ['file-upload', ['file-upload']],
  ['file-video', ['file-video']],
  ['file-word', ['file-word']],
  ['fill', ['fill']],
  ['fill-drip', ['fill-drip']],
  ['film', ['film', 'movie']],
  ['film-alt', ['film-alt']],
  ['filter', ['filter', 'funnel', 'options']],
  ['fingerprint', ['fingerprint']],
  ['fire', ['fire', 'flame', 'hot', 'popular']],
  ['fire-extinguisher', ['fire-extinguisher']],
  ['firefox', ['firefox', 'browser']],
  ['first-aid', ['first-aid']],
  ['first-order', ['first-order']],
  ['first-order-alt', ['first-order-alt']],
  ['firstdraft', ['firstdraft']],
  ['fish', ['fish']],
  ['flag', ['flag', 'notice', 'notification', 'notify', 'report']],
  ['flag-checkered', ['flag-checkered', 'notice', 'notification', 'notify', 'report']],
  ['flask', ['flask', 'beaker', 'experimental', 'labs', 'science']],
  ['flickr', ['flickr']],
  ['flipboard', ['flipboard']],
  ['flushed', ['flushed']],
  ['fly', ['fly']],
  ['folder', ['folder']],
  ['folder-open', ['folder-open']],
  ['font', ['font', 'text']],
  ['font-awesome', ['font-awesome', 'meanpath']],
  ['font-awesome-alt', ['font-awesome-alt']],
  ['font-awesome-flag', ['font-awesome-flag']],
  ['font-awesome-logo-full', ['font-awesome-logo-full']],
  ['fonticons', ['fonticons']],
  ['fonticons-fi', ['fonticons-fi']],
  ['football-ball', ['football-ball']],
  ['football-helmet', ['football-helmet']],
  ['forklift', ['forklift']],
  ['fort-awesome', ['fort-awesome', 'castle']],
  ['fort-awesome-alt', ['fort-awesome-alt', 'castle']],
  ['forumbee', ['forumbee']],
  ['forward', ['forward', 'forward', 'next']],
  ['foursquare', ['foursquare']],
  ['fragile', ['fragile']],
  ['free-code-camp', ['free-code-camp']],
  ['freebsd', ['freebsd']],
  ['frog', ['frog', 'bullfrog', 'kermit', 'kiss', 'prince', 'toad', 'wart']],
  ['frown', ['frown', 'disapprove', 'emoticon', 'face', 'rating', 'sad']],
  ['frown-open', ['frown-open']],
  ['fulcrum', ['fulcrum']],
  ['futbol', ['futbol', 'ball', 'football', 'soccer']],
  ['galactic-republic', ['galactic-republic']],
  ['galactic-senate', ['galactic-senate']],
  ['gamepad', ['gamepad', 'controller']],
  ['gas-pump', ['gas-pump']],
  ['gavel', ['gavel', 'hammer', 'judge', 'lawyer', 'opinion']],
  ['gem', ['gem', 'diamond']],
  ['genderless', ['genderless']],
  ['get-pocket', ['get-pocket']],
  ['gg', ['gg']],
  ['gg-circle', ['gg-circle']],
  ['gift', ['gift', 'generosity', 'giving', 'party', 'present', 'wrapped']],
  ['git', ['git']],
  ['git-square', ['git-square']],
  ['github', ['github', 'octocat']],
  ['github-alt', ['github-alt', 'octocat']],
  ['github-square', ['github-square', 'octocat']],
  ['gitkraken', ['gitkraken']],
  ['gitlab', ['gitlab', 'Axosoft']],
  ['gitter', ['gitter']],
  ['glass-martini', ['glass-martini', 'alcohol', 'bar', 'drink', 'glass', 'liquor', 'martini']],
  ['glass-martini-alt', ['glass-martini-alt']],
  ['glasses', ['glasses', 'foureyes', 'hipster', 'nerd', 'reading', 'sight', 'spectacles']],
  ['glide', ['glide']],
  ['glide-g', ['glide-g']],
  ['globe', ['globe', 'all', 'coordinates', 'country', 'earth', 'global', 'gps', 'language', 'localize', 'location', 'map', 'online', 'place', 'planet',
    'translate', 'travel', 'world']],
  ['globe-africa', ['globe-africa', 'all', 'country', 'earth', 'global', 'gps', 'language', 'localize', 'location', 'map', 'online', 'place', 'planet',
    'translate', 'travel', 'world']],
  ['globe-americas', ['globe-americas', 'all', 'country', 'earth', 'global', 'gps', 'language', 'localize', 'location', 'map', 'online', 'place', 'planet',
    'translate', 'travel', 'world']],
  ['globe-asia', ['globe-asia', 'all', 'country', 'earth', 'global', 'gps', 'language', 'localize', 'location', 'map', 'online', 'place', 'planet', 'translate',
    'travel', 'world']],
  ['gofore', ['gofore']],
  ['golf-ball', ['golf-ball']],
  ['golf-club', ['golf-club']],
  ['goodreads', ['goodreads']],
  ['goodreads-g', ['goodreads-g']],
  ['google', ['google']],
  ['google-drive', ['google-drive']],
  ['google-play', ['google-play']],
  ['google-plus', ['google-plus', 'google-plus-circle', 'google-plus-official']],
  ['google-plus-g', ['google-plus-g', 'google-plus', 'social network']],
  ['google-plus-square', ['google-plus-square', 'social network']],
  ['google-wallet', ['google-wallet']],
  ['graduation-cap', ['graduation-cap', 'learning', 'school', 'student']],
  ['gratipay', ['gratipay', 'favorite', 'heart', 'like', 'love']],
  ['grav', ['grav']],
  ['greater-than', ['greater-than']],
  ['greater-than-equal', ['greater-than-equal']],
  ['grimace', ['grimace']],
  ['grin', ['grin']],
  ['grin-alt', ['grin-alt']],
  ['grin-beam', ['grin-beam']],
  ['grin-beam-sweat', ['grin-beam-sweat']],
  ['grin-hearts', ['grin-hearts']],
  ['grin-squint', ['grin-squint']],
  ['grin-squint-tears', ['grin-squint-tears']],
  ['grin-stars', ['grin-stars']],
  ['grin-tears', ['grin-tears']],
  ['grin-tongue', ['grin-tongue']],
  ['grin-tongue-squint', ['grin-tongue-squint']],
  ['grin-tongue-wink', ['grin-tongue-wink']],
  ['grin-wink', ['grin-wink']],
  ['grip-horizontal', ['grip-horizontal', 'affordance', 'grab', 'handle']],
  ['grip-vertical', ['grip-vertical', 'affordance', 'grab', 'handle']],
  ['gripfire', ['gripfire']],
  ['grunt', ['grunt']],
  ['gulp', ['gulp']],
  ['h-square', ['h-square', 'hospital', 'hotel']],
  ['h1', ['header']],
  ['h2', ['header']],
  ['h3', ['header']],
  ['hacker-news', ['hacker-news']],
  ['hacker-news-square', ['hacker-news-square']],
  ['hand-heart', ['hand-heart']],
  ['hand-holding', ['hand-holding']],
  ['hand-holding-box', ['hand-holding-box']],
  ['hand-holding-heart', ['hand-holding-heart']],
  ['hand-holding-seedling', ['hand-holding-seedling']],
  ['hand-holding-usd', ['hand-holding-usd', '$', 'dollar sign', 'donation', 'giving', 'money', 'price']],
  ['hand-holding-water', ['hand-holding-water']],
  ['hand-lizard', ['hand-lizard']],
  ['hand-paper', ['hand-paper', 'stop']],
  ['hand-peace', ['hand-peace']],
  ['hand-point-down', ['hand-point-down', 'finger', 'hand-o-down', 'point']],
  ['hand-point-left', ['hand-point-left', 'back', 'finger', 'hand-o-left', 'left', 'point', 'previous']],
  ['hand-point-right', ['hand-point-right', 'finger', 'forward', 'hand-o-right', 'next', 'point', 'right']],
  ['hand-point-up', ['hand-point-up', 'finger', 'hand-o-up', 'point']],
  ['hand-pointer', ['hand-pointer', 'select']],
  ['hand-receiving', ['hand-receiving']],
  ['hand-rock', ['hand-rock']],
  ['hand-scissors', ['hand-scissors']],
  ['hand-spock', ['hand-spock']],
  ['hands', ['hands']],
  ['hands-heart', ['hands-heart']],
  ['hands-helping', ['hands-helping', 'aid', 'assistance', 'partnership', 'volunteering']],
  ['hands-usd', ['hands-usd', '$', 'dollar sign', 'donation', 'giving', 'money', 'price', 'usd']],
  ['handshake', ['handshake', 'greeting', 'partnership']],
  ['handshake-alt', ['handshake-alt', 'greeting', 'partnership']],
  ['hashtag', ['hashtag']],
  ['hdd', ['hdd', 'cpu', 'hard drive', 'harddrive', 'machine', 'save', 'storage']],
  ['heading', ['heading', 'header', 'header']],
  ['headphones', ['headphones', 'audio', 'listen', 'music', 'sound', 'speaker']],
  ['headphones-alt', ['headphones-alt']],
  ['headset', ['headset']],
  ['heart', ['heart', 'favorite', 'like', 'love']],
  ['heart-circle', ['heart-circle', 'favorite', 'like', 'love']],
  ['heart-square', ['heart-square', 'favorite', 'like', 'love']],
  ['heartbeat', ['heartbeat', 'ekg', 'lifeline', 'vital signs']],
  ['helicopter', ['helicopter', 'airwolf', 'apache', 'chopper', 'flight', 'fly']],
  ['hexagon', ['hexagon']],
  ['highlighter', ['highlighter', 'edit', 'marker', 'sharpie', 'update', 'write']],
  ['hips', ['hips']],
  ['hire-a-helper', ['hire-a-helper']],
  ['history', ['history']],
  ['hockey-puck', ['hockey-puck']],
  ['hockey-sticks', ['hockey-sticks']],
  ['home', ['home', 'house', 'main']],
  ['home-heart', ['home-heart']],
  ['hooli', ['hooli']],
  ['hornbill', ['hornbill']],
  ['hospital', ['hospital', 'building', 'emergency room', 'medical center']],
  ['hospital-alt', ['hospital-alt', 'building', 'emergency room', 'medical center']],
  ['hospital-symbol', ['hospital-symbol']],
  ['hot-tub', ['hot-tub']],
  ['hotel', ['hotel', 'building', 'lodging']],
  ['hotjar', ['hotjar']],
  ['hourglass', ['hourglass']],
  ['hourglass-end', ['hourglass-end']],
  ['hourglass-half', ['hourglass-half']],
  ['hourglass-start', ['hourglass-start']],
  ['houzz', ['houzz']],
  ['html5', ['html5']],
  ['hubspot', ['hubspot']],
  ['i-cursor', ['i-cursor']],
  ['id-badge', ['id-badge']],
  ['id-card', ['id-card', 'document', 'identification', 'issued']],
  ['id-card-alt', ['id-card-alt', 'demographics']],
  ['image', ['image', 'album', 'photo', 'picture', 'picture']],
  ['images', ['images', 'album', 'photo', 'picture']],
  ['imdb', ['imdb']],
  ['inbox', ['inbox']],
  ['inbox-in', ['inbox-in']],
  ['inbox-out', ['inbox-out']],
  ['indent', ['indent']],
  ['industry', ['industry', 'factory', 'manufacturing']],
  ['industry-alt', ['industry-alt', 'factory', 'manufacturing']],
  ['infinity', ['infinity']],
  ['info', ['info', 'details', 'help', 'information', 'more']],
  ['info-circle', ['info-circle', 'details', 'help', 'information', 'more']],
  ['info-square', ['info-square', 'details', 'help', 'information', 'more']],
  ['instagram', ['instagram']],
  ['internet-explorer', ['internet-explorer', 'browser', 'ie']],
  ['inventory', ['inventory']],
  ['ioxhost', ['ioxhost']],
  ['italic', ['italic', 'italics']],
  ['itunes', ['itunes']],
  ['itunes-note', ['itunes-note']],
  ['jack-o-lantern', ['jack-o-lantern']],
  ['java', ['java']],
  ['jedi-order', ['jedi-order']],
  ['jenkins', ['jenkins']],
  ['joget', ['joget']],
  ['joint', ['joint', 'blunt', 'cannabis', 'doobie', 'drugs', 'marijuana', 'roach', 'smoke', 'smoking', 'spliff']],
  ['joomla', ['joomla']],
  ['js', ['js']],
  ['js-square', ['js-square']],
  ['jsfiddle', ['jsfiddle']],
  ['key', ['key', 'password', 'unlock']],
  ['keybase', ['keybase']],
  ['keyboard', ['keyboard', 'input', 'type']],
  ['keycdn', ['keycdn']],
  ['kickstarter', ['kickstarter']],
  ['kickstarter-k', ['kickstarter-k']],
  ['kiss', ['kiss']],
  ['kiss-beam', ['kiss-beam']],
  ['kiss-wink-heart', ['kiss-wink-heart']],
  ['kiwi-bird', ['kiwi-bird']],
  ['korvue', ['korvue']],
  ['lamp', ['lamp']],
  ['language', ['language']],
  ['laptop', ['laptop', 'computer', 'cpu', 'dell', 'demo', 'device', 'dude, you\'re getting', 'mac', 'macbook', 'machine', 'pc', 'pc']],
  ['laravel', ['laravel']],
  ['lastfm', ['lastfm']],
  ['lastfm-square', ['lastfm-square']],
  ['laugh', ['laugh']],
  ['laugh-beam', ['laugh-beam']],
  ['laugh-squint', ['laugh-squint']],
  ['laugh-wink', ['laugh-wink']],
  ['leaf', ['leaf', 'eco', 'nature', 'plant']],
  ['leaf-heart', ['leaf-heart']],
  ['leanpub', ['leanpub']],
  ['lemon', ['lemon', 'food']],
  ['less', ['less']],
  ['less-than', ['less-than']],
  ['less-than-equal', ['less-than-equal']],
  ['level-down', ['level-down', 'arrow']],
  ['level-down-alt', ['level-down-alt', 'level-down']],
  ['level-up', ['level-up', 'arrow']],
  ['level-up-alt', ['level-up-alt', 'level-up']],
  ['life-ring', ['life-ring', 'support']],
  ['lightbulb', ['lightbulb', 'idea', 'inspiration']],
  ['line', ['line']],
  ['link', ['link', 'chain']],
  ['linkedin', ['linkedin', 'linkedin-square']],
  ['linkedin-in', ['linkedin-in', 'linkedin']],
  ['linode', ['linode']],
  ['linux', ['linux', 'tux']],
  ['lira-sign', ['lira-sign', 'try', 'try', 'turkish']],
  ['list', ['list', 'checklist', 'completed', 'done', 'finished', 'ol', 'todo', 'ul']],
  ['list-alt', ['list-alt', 'checklist', 'completed', 'done', 'finished', 'ol', 'todo', 'ul']],
  ['list-ol', ['list-ol', 'checklist', 'list', 'list', 'numbers', 'ol', 'todo', 'ul']],
  ['list-ul', ['list-ul', 'checklist', 'list', 'ol', 'todo', 'ul']],
  ['location-arrow', ['location-arrow', 'address', 'coordinates', 'gps', 'location', 'map', 'place', 'where']],
  ['lock', ['lock', 'admin', 'protect', 'security']],
  ['lock-alt', ['lock-alt', 'admin', 'protect', 'security']],
  ['lock-open', ['lock-open', 'admin', 'lock', 'open', 'password', 'protect']],
  ['lock-open-alt', ['lock-open-alt', 'admin', 'lock', 'password', 'protect']],
  ['long-arrow-alt-down', ['long-arrow-alt-down', 'long-arrow-down']],
  ['long-arrow-alt-left', ['long-arrow-alt-left', 'back', 'long-arrow-left', 'previous']],
  ['long-arrow-alt-right', ['long-arrow-alt-right', 'long-arrow-right']],
  ['long-arrow-alt-up', ['long-arrow-alt-up', 'long-arrow-up']],
  ['long-arrow-down', ['long-arrow-down']],
  ['long-arrow-left', ['long-arrow-left', 'back', 'previous']],
  ['long-arrow-right', ['long-arrow-right']],
  ['long-arrow-up', ['long-arrow-up']],
  ['loveseat', ['loveseat']],
  ['low-vision', ['low-vision']],
  ['luchador', ['luchador']],
  ['luggage-cart', ['luggage-cart']],
  ['lyft', ['lyft']],
  ['magento', ['magento']],
  ['magic', ['magic', 'autocomplete', 'automatic', 'wizard']],
  ['magnet', ['magnet']],
  ['mailchimp', ['mailchimp']],
  ['male', ['male', 'human', 'man', 'person', 'profile', 'user']],
  ['mandalorian', ['mandalorian']],
  ['map', ['map', 'coordinates', 'location', 'paper', 'place', 'travel']],
  ['map-marked', ['map-marked', 'address', 'coordinates', 'destination', 'gps', 'localize', 'location', 'map', 'paper', 'pin', 'place', 'point of interest',
    'position', 'route', 'travel', 'where']],
  ['map-marked-alt', ['map-marked-alt', 'address', 'coordinates', 'destination', 'gps', 'localize', 'location', 'map', 'paper', 'pin', 'place',
    'point of interest', 'position', 'route', 'travel', 'where']],
  ['map-marker', ['map-marker', 'address', 'coordinates', 'gps', 'localize', 'location', 'map', 'pin', 'place', 'position', 'travel', 'where']],
  ['map-marker-alt', ['map-marker-alt', 'address', 'coordinates', 'gps', 'localize', 'location', 'map', 'pin', 'place', 'position', 'travel', 'where']],
  ['map-pin', ['map-pin', 'address', 'coordinates', 'gps', 'localize', 'location', 'map', 'marker', 'place', 'position', 'travel', 'where']],
  ['map-signs', ['map-signs']],
  ['marker', ['marker', 'edit', 'sharpie', 'update', 'write']],
  ['mars', ['mars', 'male']],
  ['mars-double', ['mars-double']],
  ['mars-stroke', ['mars-stroke']],
  ['mars-stroke-h', ['mars-stroke-h']],
  ['mars-stroke-v', ['mars-stroke-v']],
  ['mastodon', ['mastodon']],
  ['maxcdn', ['maxcdn']],
  ['medal', ['medal']],
  ['medapps', ['medapps']],
  ['medium', ['medium']],
  ['medium-m', ['medium-m']],
  ['medkit', ['medkit', 'first aid', 'firstaid', 'health', 'help', 'support']],
  ['medrt', ['medrt']],
  ['meetup', ['meetup']],
  ['megaport', ['megaport']],
  ['meh', ['meh', 'emoticon', 'face', 'neutral', 'rating']],
  ['meh-blank', ['meh-blank']],
  ['meh-rolling-eyes', ['meh-rolling-eyes']],
  ['memory', ['memory', 'DIMM', 'RAM']],
  ['mercury', ['mercury', 'transgender']],
  ['microchip', ['microchip', 'cpu', 'processor']],
  ['microphone', ['microphone', 'record', 'sound', 'voice']],
  ['microphone-alt', ['microphone-alt', 'record', 'sound', 'voice']],
  ['microphone-alt-slash', ['microphone-alt-slash', 'disable', 'mute', 'record', 'sound', 'voice']],
  ['microphone-slash', ['microphone-slash', 'disable', 'mute', 'record', 'sound', 'voice']],
  ['microsoft', ['microsoft']],
  ['minus', ['minus', 'collapse', 'delete', 'hide', 'hide', 'minify', 'remove', 'trash']],
  ['minus-circle', ['minus-circle', 'delete', 'hide', 'remove', 'trash']],
  ['minus-hexagon', ['minus-hexagon', 'delete', 'hide', 'remove', 'trash']],
  ['minus-octagon', ['minus-octagon', 'delete', 'hide', 'remove', 'trash']],
  ['minus-square', ['minus-square', 'collapse', 'delete', 'hide', 'hide', 'minify', 'remove', 'trash']],
  ['mix', ['mix']],
  ['mixcloud', ['mixcloud']],
  ['mizuni', ['mizuni']],
  ['mobile', ['mobile', 'apple', 'call', 'cell phone', 'cellphone', 'device', 'iphone', 'number', 'screen', 'telephone', 'text']],
  ['mobile-alt', ['mobile-alt', 'apple', 'call', 'cell phone', 'cellphone', 'device', 'iphone', 'number', 'screen', 'telephone', 'text']],
  ['mobile-android', ['mobile-android', 'android', 'call', 'cell phone', 'cellphone', 'device', 'number', 'screen', 'telephone', 'text']],
  ['mobile-android-alt', ['mobile-android-alt', 'android', 'call', 'cell phone', 'cellphone', 'device', 'number', 'screen', 'telephone', 'text']],
  ['modx', ['modx']],
  ['monero', ['monero']],
  ['money-bill', ['money-bill', 'buy', 'cash', 'checkout', 'money', 'payment', 'price', 'purchase']],
  ['money-bill-alt', ['money-bill-alt', 'buy', 'cash', 'checkout', 'money', 'payment', 'price', 'purchase']],
  ['money-bill-wave', ['money-bill-wave']],
  ['money-bill-wave-alt', ['money-bill-wave-alt']],
  ['money-check', ['money-check', 'bank check', 'cheque']],
  ['money-check-alt', ['money-check-alt', 'bank check', 'cheque']],
  ['monument', ['monument', 'building', 'historic', 'memoroable']],
  ['moon', ['moon', 'contrast', 'darker', 'night']],
  ['mortar-pestle', ['mortar-pestle', 'crush', 'culinary', 'grind', 'medical', 'mix', 'spices']],
  ['motorcycle', ['motorcycle', 'bike', 'machine', 'transportation', 'vehicle']],
  ['mouse-pointer', ['mouse-pointer', 'select']],
  ['music', ['music', 'note', 'sound']],
  ['napster', ['napster']],
  ['neuter', ['neuter']],
  ['newspaper', ['newspaper', 'article', 'press']],
  ['nimblr', ['nimblr']],
  ['nintendo-switch', ['nintendo-switch']],
  ['node', ['node']],
  ['node-js', ['node-js']],
  ['not-equal', ['not-equal']],
  ['notes-medical', ['notes-medical']],
  ['npm', ['npm']],
  ['ns8', ['ns8']],
  ['nutritionix', ['nutritionix']],
  ['object-group', ['object-group', 'design']],
  ['object-ungroup', ['object-ungroup', 'design']],
  ['octagon', ['octagon']],
  ['odnoklassniki', ['odnoklassniki']],
  ['odnoklassniki-square', ['odnoklassniki-square']],
  ['old-republic', ['old-republic']],
  ['opencart', ['opencart']],
  ['openid', ['openid']],
  ['opera', ['opera']],
  ['optin-monster', ['optin-monster']],
  ['osi', ['osi']],
  ['outdent', ['outdent']],
  ['page4', ['page4']],
  ['pagelines', ['pagelines', 'eco', 'leaf', 'leaves', 'nature', 'plant', 'tree']],
  ['paint-brush', ['paint-brush']],
  ['paint-brush-alt', ['paint-brush-alt']],
  ['paint-roller', ['paint-roller', 'brush', 'painting', 'tool']],
  ['palette', ['palette', 'colors', 'painting']],
  ['palfed', ['palfed']],
  ['pallet', ['pallet']],
  ['pallet-alt', ['pallet-alt']],
  ['paper-plane', ['paper-plane']],
  ['paperclip', ['paperclip', 'attachment']],
  ['parachute-box', ['parachute-box', 'aid', 'assistance', 'rescue', 'supplies']],
  ['paragraph', ['paragraph']],
  ['parking', ['parking']],
  ['passport', ['passport', 'document', 'identification', 'issued']],
  ['paste', ['paste', 'clipboard', 'copy']],
  ['patreon', ['patreon']],
  ['pause', ['pause', 'wait']],
  ['pause-circle', ['pause-circle']],
  ['paw', ['paw', 'pet']],
  ['paypal', ['paypal']],
  ['pen', ['pen', 'design', 'edit', 'update', 'write']],
  ['pen-alt', ['pen-alt', 'design', 'edit', 'update', 'write']],
  ['pen-fancy', ['pen-fancy', 'design', 'edit', 'fountain pen', 'update', 'write']],
  ['pen-nib', ['pen-nib', 'design', 'edit', 'fountain pen', 'update', 'write']],
  ['pen-square', ['pen-square', 'edit', 'pencil-square', 'update', 'write']],
  ['pencil', ['pencil', 'design', 'edit', 'update', 'write']],
  ['pencil-alt', ['pencil-alt', 'design', 'edit', 'pencil', 'update', 'write']],
  ['pencil-ruler', ['pencil-ruler']],
  ['pennant', ['pennant']],
  ['people-carry', ['people-carry', 'movers']],
  ['percent', ['percent']],
  ['percentage', ['percentage']],
  ['periscope', ['periscope']],
  ['person-carry', ['person-carry', 'mover']],
  ['person-dolly', ['person-dolly', 'mover dolly']],
  ['person-dolly-empty', ['person-dolly-empty', 'mover']],
  ['phabricator', ['phabricator']],
  ['phoenix-framework', ['phoenix-framework']],
  ['phoenix-squadron', ['phoenix-squadron']],
  ['phone', ['phone', 'call', 'earphone', 'number', 'support', 'telephone', 'voice']],
  ['phone-plus', ['phone-plus']],
  ['phone-slash', ['phone-slash']],
  ['phone-square', ['phone-square', 'call', 'number', 'support', 'telephone', 'voice']],
  ['phone-volume', ['phone-volume', 'telephone', 'volume-control-phone']],
  ['php', ['php']],
  ['pied-piper', ['pied-piper']],
  ['pied-piper-alt', ['pied-piper-alt']],
  ['pied-piper-hat', ['pied-piper-hat', 'clothing']],
  ['pied-piper-pp', ['pied-piper-pp']],
  ['piggy-bank', ['piggy-bank', 'save', 'savings']],
  ['pills', ['pills', 'drugs', 'medicine']],
  ['pinterest', ['pinterest']],
  ['pinterest-p', ['pinterest-p']],
  ['pinterest-square', ['pinterest-square']],
  ['plane', ['plane', 'airplane', 'destination', 'fly', 'location', 'mode', 'travel', 'trip']],
  ['plane-alt', ['plane-alt']],
  ['plane-arrival', ['plane-arrival', 'airplane', 'arriving', 'destination', 'fly', 'land', 'landing', 'location', 'mode', 'travel', 'trip']],
  ['plane-departure', ['plane-departure', 'airplane', 'departing', 'destination', 'fly', 'location', 'mode', 'take off', 'taking off', 'travel', 'trip']],
  ['play', ['play', 'music', 'playing', 'sound', 'start']],
  ['play-circle', ['play-circle', 'playing', 'start']],
  ['playstation', ['playstation']],
  ['plug', ['plug', 'connect', 'online', 'power']],
  ['plus', ['plus', 'add', 'create', 'expand', 'new']],
  ['plus-circle', ['plus-circle', 'add', 'create', 'expand', 'new']],
  ['plus-hexagon', ['plus-hexagon', 'add', 'create', 'expand', 'new']],
  ['plus-octagon', ['plus-octagon', 'add', 'create', 'expand', 'new']],
  ['plus-square', ['plus-square', 'add', 'create', 'expand', 'new']],
  ['podcast', ['podcast']],
  ['poo', ['poo']],
  ['portrait', ['portrait']],
  ['pound-sign', ['pound-sign', 'gbp', 'gbp']],
  ['power-off', ['power-off', 'on', 'reboot', 'restart']],
  ['prescription', ['prescription', 'drugs', 'medical', 'medicine', 'rx']],
  ['prescription-bottle', ['prescription-bottle', 'drugs', 'medical', 'medicine', 'rx']],
  ['prescription-bottle-alt', ['prescription-bottle-alt', 'drugs', 'medical', 'medicine', 'rx']],
  ['print', ['print']],
  ['procedures', ['procedures']],
  ['product-hunt', ['product-hunt']],
  ['project-diagram', ['project-diagram']],
  ['pushed', ['pushed']],
  ['puzzle-piece', ['puzzle-piece', 'add-on', 'addon', 'section']],
  ['python', ['python']],
  ['qq', ['qq']],
  ['qrcode', ['qrcode', 'scan']],
  ['question', ['question', 'help', 'information', 'support', 'unknown']],
  ['question-circle', ['question-circle', 'help', 'information', 'support', 'unknown']],
  ['question-square', ['question-square', 'help', 'information', 'support', 'unknown']],
  ['quidditch', ['quidditch']],
  ['quinscape', ['quinscape']],
  ['quora', ['quora']],
  ['quote-left', ['quote-left']],
  ['quote-right', ['quote-right']],
  ['r-project', ['r-project']],
  ['racquet', ['racquet']],
  ['ramp-loading', ['ramp-loading']],
  ['random', ['random', 'shuffle', 'sort']],
  ['ravelry', ['ravelry']],
  ['react', ['react']],
  ['readme', ['readme']],
  ['rebel', ['rebel']],
  ['receipt', ['receipt', 'check', 'invoice', 'table']],
  ['rectangle-landscape', ['rectangle-landscape']],
  ['rectangle-portrait', ['rectangle-portrait']],
  ['rectangle-wide', ['rectangle-wide']],
  ['recycle', ['recycle']],
  ['red-river', ['red-river']],
  ['reddit', ['reddit']],
  ['reddit-alien', ['reddit-alien']],
  ['reddit-square', ['reddit-square']],
  ['redo', ['redo', 'forward', 'repeat', 'repeat']],
  ['redo-alt', ['redo-alt', 'forward', 'repeat']],
  ['registered', ['registered']],
  ['rendact', ['rendact']],
  ['renren', ['renren']],
  ['repeat', ['repeat']],
  ['repeat-1', ['repeat-1']],
  ['repeat-1-alt', ['repeat-1-alt']],
  ['repeat-alt', ['repeat-alt']],
  ['reply', ['reply']],
  ['reply-all', ['reply-all']],
  ['replyd', ['replyd']],
  ['researchgate', ['researchgate']],
  ['resolving', ['resolving']],
  ['retweet', ['retweet', 'refresh', 'reload', 'share', 'swap']],
  ['retweet-alt', ['retweet-alt', 'refresh', 'reload', 'share', 'swap']],
  ['rev', ['rev']],
  ['ribbon', ['ribbon', 'badge', 'cause', 'lapel', 'pin']],
  ['road', ['road', 'street']],
  ['robot', ['robot']],
  ['rocket', ['rocket', 'app']],
  ['rocketchat', ['rocketchat']],
  ['rockrms', ['rockrms']],
  ['route', ['route']],
  ['rss', ['rss', 'blog']],
  ['rss-square', ['rss-square', 'blog', 'feed']],
  ['ruble-sign', ['ruble-sign', 'rub', 'rub']],
  ['ruler', ['ruler']],
  ['ruler-combined', ['ruler-combined']],
  ['ruler-horizontal', ['ruler-horizontal']],
  ['ruler-vertical', ['ruler-vertical']],
  ['rupee-sign', ['rupee-sign', 'indian', 'inr']],
  ['sad-cry', ['sad-cry']],
  ['sad-tear', ['sad-tear']],
  ['safari', ['safari', 'browser']],
  ['sass', ['sass']],
  ['save', ['save', 'floppy', 'floppy-o']],
  ['scanner', ['scanner']],
  ['scanner-keyboard', ['scanner-keyboard']],
  ['scanner-touchscreen', ['scanner-touchscreen']],
  ['schlix', ['schlix']],
  ['school', ['school']],
  ['screwdriver', ['screwdriver', 'admin', 'container', 'fix', 'repair', 'settings', 'tool']],
  ['scribd', ['scribd']],
  ['scrubber', ['scrubber']],
  ['search', ['search', 'bigger', 'enlarge', 'magnify', 'preview', 'zoom']],
  ['search-minus', ['search-minus', 'magnify', 'minify', 'smaller', 'zoom', 'zoom out']],
  ['search-plus', ['search-plus', 'bigger', 'enlarge', 'magnify', 'zoom', 'zoom in']],
  ['searchengin', ['searchengin']],
  ['seedling', ['seedling']],
  ['sellcast', ['sellcast', 'eercast']],
  ['sellsy', ['sellsy']],
  ['server', ['server', 'cpu']],
  ['servicestack', ['servicestack']],
  ['share', ['share']],
  ['share-all', ['share-all']],
  ['share-alt', ['share-alt']],
  ['share-alt-square', ['share-alt-square']],
  ['share-square', ['share-square', 'send', 'social']],
  ['shekel-sign', ['shekel-sign', 'ils', 'ils']],
  ['shield', ['shield', 'achievement', 'award', 'security', 'winner']],
  ['shield-alt', ['shield-alt', 'shield']],
  ['shield-check', ['shield-check', 'achievement', 'award', 'security', 'success', 'winner']],
  ['ship', ['ship', 'boat', 'sea']],
  ['shipping-fast', ['shipping-fast']],
  ['shipping-timed', ['shipping-timed']],
  ['shirtsinbulk', ['shirtsinbulk']],
  ['shoe-prints', ['shoe-prints', 'feet', 'footprints', 'steps']],
  ['shopping-bag', ['shopping-bag']],
  ['shopping-basket', ['shopping-basket']],
  ['shopping-cart', ['shopping-cart', 'buy', 'checkout', 'payment', 'purchase']],
  ['shopware', ['shopware']],
  ['shower', ['shower']],
  ['shuttle-van', ['shuttle-van', 'machine', 'public-transportation', 'transportation', 'vehicle']],
  ['shuttlecock', ['shuttlecock']],
  ['sign', ['sign']],
  ['sign-in', ['sign-in', 'arrow', 'enter', 'join', 'log in', 'login', 'sign in', 'sign up', 'signin', 'signup']],
  ['sign-in-alt', ['sign-in-alt', 'arrow', 'enter', 'join', 'log in', 'login', 'sign in', 'sign up', 'sign-in', 'signin', 'signup']],
  ['sign-language', ['sign-language']],
  ['sign-out', ['sign-out', 'arrow', 'exit', 'leave', 'log out', 'logout']],
  ['sign-out-alt', ['sign-out-alt', 'arrow', 'exit', 'leave', 'log out', 'logout', 'sign-out']],
  ['signal', ['signal', 'bars', 'graph', 'online', 'status']],
  ['signature', ['signature', 'John Hancock', 'cursive', 'name', 'writing']],
  ['simplybuilt', ['simplybuilt']],
  ['sistrix', ['sistrix']],
  ['sitemap', ['sitemap', 'directory', 'hierarchy', 'ia', 'information architecture', 'organization']],
  ['sith', ['sith']],
  ['skull', ['skull', 'bones', 'skeleton', 'yorick']],
  ['skyatlas', ['skyatlas']],
  ['skype', ['skype']],
  ['slack', ['slack', 'anchor', 'hash', 'hashtag']],
  ['slack-hash', ['slack-hash', 'anchor', 'hash', 'hashtag']],
  ['sliders-h', ['sliders-h', 'settings', 'sliders']],
  ['sliders-h-square', ['sliders-h-square']],
  ['sliders-v', ['sliders-v']],
  ['sliders-v-square', ['sliders-v-square']],
  ['slideshare', ['slideshare']],
  ['smile', ['smile', 'approve', 'emoticon', 'face', 'happy', 'rating', 'satisfied']],
  ['smile-beam', ['smile-beam']],
  ['smile-plus', ['smile-plus']],
  ['smile-wink', ['smile-wink']],
  ['smoking', ['smoking', 'cigarette', 'nicotine', 'smoking status']],
  ['smoking-ban', ['smoking-ban', 'no smoking', 'non-smoking']],
  ['snapchat', ['snapchat']],
  ['snapchat-ghost', ['snapchat-ghost']],
  ['snapchat-square', ['snapchat-square']],
  ['snowflake', ['snowflake']],
  ['solar-panel', ['solar-panel', 'clean', 'eco-friendly', 'energy', 'green', 'sun']],
  ['sort', ['sort', 'order']],
  ['sort-alpha-down', ['sort-alpha-down', 'sort-alpha-asc']],
  ['sort-alpha-up', ['sort-alpha-up', 'sort-alpha-desc']],
  ['sort-amount-down', ['sort-amount-down', 'sort-amount-asc']],
  ['sort-amount-up', ['sort-amount-up', 'sort-amount-desc']],
  ['sort-down', ['sort-down', 'arrow', 'descending', 'sort-desc']],
  ['sort-numeric-down', ['sort-numeric-down', 'numbers', 'sort-numeric-asc']],
  ['sort-numeric-up', ['sort-numeric-up', 'numbers', 'sort-numeric-desc']],
  ['sort-up', ['sort-up', 'arrow', 'ascending', 'sort-asc']],
  ['soundcloud', ['soundcloud']],
  ['spa', ['spa', 'mindfullness', 'plant', 'wellness']],
  ['space-shuttle', ['space-shuttle', 'astronaut', 'machine', 'nasa', 'rocket', 'transportation']],
  ['spade', ['spade']],
  ['speakap', ['speakap']],
  ['spinner', ['spinner', 'loading', 'progress']],
  ['spinner-third', ['spinner-third']],
  ['splotch', ['splotch']],
  ['spotify', ['spotify']],
  ['spray-can', ['spray-can']],
  ['square', ['square', 'block', 'box']],
  ['square-full', ['square-full']],
  ['squarespace', ['squarespace']],
  ['stack-exchange', ['stack-exchange']],
  ['stack-overflow', ['stack-overflow']],
  ['stamp', ['stamp']],
  ['star', ['star', 'achievement', 'award', 'favorite', 'important', 'night', 'rating', 'score']],
  ['star-exclamation', ['star-exclamation', 'achievement', 'award', 'favorite', 'night', 'rating', 'score']],
  ['star-half', ['star-half', 'achievement', 'award', 'rating', 'score', 'star-half-empty', 'star-half-full']],
  ['star-half-alt', ['star-half-alt', 'achievement', 'award', 'rating', 'score', 'star-half-empty', 'star-half-full']],
  ['staylinked', ['staylinked']],
  ['steam', ['steam']],
  ['steam-square', ['steam-square']],
  ['steam-symbol', ['steam-symbol']],
  ['step-backward', ['step-backward', 'beginning', 'first', 'previous', 'rewind', 'start']],
  ['step-forward', ['step-forward', 'end', 'last', 'next']],
  ['stethoscope', ['stethoscope']],
  ['sticker-mule', ['sticker-mule']],
  ['sticky-note', ['sticky-note']],
  ['stop', ['stop', 'block', 'box', 'square']],
  ['stop-circle', ['stop-circle']],
  ['stopwatch', ['stopwatch', 'time']],
  ['store', ['store']],
  ['store-alt', ['store-alt']],
  ['strava', ['strava']],
  ['stream', ['stream']],
  ['street-view', ['street-view', 'map']],
  ['strikethrough', ['strikethrough']],
  ['stripe', ['stripe']],
  ['stripe-s', ['stripe-s']],
  ['stroopwafel', ['stroopwafel', 'dessert', 'food', 'sweets', 'waffle']],
  ['studiovinari', ['studiovinari']],
  ['stumbleupon', ['stumbleupon']],
  ['stumbleupon-circle', ['stumbleupon-circle']],
  ['subscript', ['subscript']],
  ['subway', ['subway', 'machine', 'railway', 'train', 'transportation', 'vehicle']],
  ['suitcase', ['suitcase', 'baggage', 'luggage', 'move', 'suitcase', 'travel', 'trip']],
  ['suitcase-rolling', ['suitcase-rolling']],
  ['sun', ['sun', 'brighten', 'contrast', 'day', 'lighter', 'weather']],
  ['superpowers', ['superpowers']],
  ['superscript', ['superscript', 'exponential']],
  ['supple', ['supple']],
  ['surprise', ['surprise']],
  ['swatchbook', ['swatchbook']],
  ['swimmer', ['swimmer', 'athlete', 'head', 'man', 'person', 'water']],
  ['swimming-pool', ['swimming-pool', 'ladder', 'recreation', 'water']],
  ['sync', ['sync', 'exchange', 'refresh', 'reload', 'rotate', 'swap']],
  ['sync-alt', ['sync-alt', 'refresh', 'reload', 'rotate']],
  ['syringe', ['syringe', 'immunizations', 'needle']],
  ['table', ['table', 'data', 'excel', 'spreadsheet']],
  ['table-tennis', ['table-tennis']],
  ['tablet', ['tablet', 'apple', 'device', 'ipad', 'kindle', 'screen']],
  ['tablet-alt', ['tablet-alt', 'apple', 'device', 'ipad', 'kindle', 'screen']],
  ['tablet-android', ['tablet-android', 'device', 'screen']],
  ['tablet-android-alt', ['tablet-android-alt', 'device', 'screen']],
  ['tablet-rugged', ['tablet-rugged', 'device', 'durable', 'screen', 'tough']],
  ['tablets', ['tablets', 'drugs', 'medicine']],
  ['tachometer', ['tachometer', 'dashboard', 'fast', 'speedometer']],
  ['tachometer-alt', ['tachometer-alt', 'dashboard', 'tachometer']],
  ['tag', ['tag', 'label']],
  ['tags', ['tags', 'labels']],
  ['tape', ['tape']],
  ['tasks', ['tasks', 'downloading', 'downloads', 'loading', 'progress', 'settings']],
  ['taxi', ['taxi', 'cab', 'cabbie', 'car', 'car service', 'lyft', 'machine', 'transportation', 'uber', 'vehicle']],
  ['teamspeak', ['teamspeak']],
  ['telegram', ['telegram']],
  ['telegram-plane', ['telegram-plane']],
  ['tencent-weibo', ['tencent-weibo']],
  ['tennis-ball', ['tennis-ball']],
  ['terminal', ['terminal', 'code', 'command', 'console', 'prompt']],
  ['text-height', ['text-height']],
  ['text-width', ['text-width']],
  ['th', ['th', 'blocks', 'boxes', 'grid', 'squares']],
  ['th-large', ['th-large', 'blocks', 'boxes', 'grid', 'squares']],
  ['th-list', ['th-list', 'checklist', 'completed', 'done', 'finished', 'ol', 'todo', 'ul']],
  ['themeco', ['themeco']],
  ['themeisle', ['themeisle']],
  ['thermometer', ['thermometer', 'fever', 'temperature']],
  ['thermometer-empty', ['thermometer-empty', 'status']],
  ['thermometer-full', ['thermometer-full', 'status']],
  ['thermometer-half', ['thermometer-half', 'status']],
  ['thermometer-quarter', ['thermometer-quarter', 'status']],
  ['thermometer-three-quarters', ['thermometer-three-quarters', 'status']],
  ['thumbs-down', ['thumbs-down', 'disagree', 'disapprove', 'dislike', 'hand', 'thumbs-o-down']],
  ['thumbs-up', ['thumbs-up', 'agree', 'approve', 'favorite', 'hand', 'like', 'ok', 'okay', 'success', 'thumbs-o-up', 'yes', 'you got it dude']],
  ['thumbtack', ['thumbtack', 'coordinates', 'location', 'marker', 'pin', 'thumb-tack']],
  ['ticket', ['ticket', 'movie', 'pass', 'support']],
  ['ticket-alt', ['ticket-alt', 'ticket']],
  ['times', ['times', 'close', 'cross', 'error', 'exit', 'incorrect', 'notice', 'notification', 'notify', 'problem', 'wrong', 'x']],
  ['times-circle', ['times-circle', 'close', 'cross', 'exit', 'incorrect', 'notice', 'notification', 'notify', 'problem', 'wrong', 'x']],
  ['times-hexagon', ['times-hexagon', 'close', 'cross', 'exit', 'incorrect', 'notice', 'notification', 'notify', 'problem', 'wrong', 'x']],
  ['times-octagon', ['times-octagon', 'close', 'cross', 'exit', 'incorrect', 'notice', 'notification', 'notify', 'problem', 'wrong', 'x']],
  ['times-square', ['times-square', 'close', 'cross', 'incorrect', 'notice', 'notification', 'notify', 'problem', 'window', 'wrong']],
  ['tint', ['tint', 'drop', 'droplet', 'raindrop', 'waterdrop']],
  ['tint-slash', ['tint-slash']],
  ['tired', ['tired']],
  ['toggle-off', ['toggle-off', 'switch']],
  ['toggle-on', ['toggle-on', 'switch']],
  ['toolbox', ['toolbox', 'admin', 'container', 'fix', 'repair', 'settings', 'tools']],
  ['tooth', ['tooth']],
  ['trade-federation', ['trade-federation']],
  ['trademark', ['trademark']],
  ['train', ['train', 'bullet', 'locomotive', 'railway']],
  ['transgender', ['transgender', 'intersex']],
  ['transgender-alt', ['transgender-alt']],
  ['trash', ['trash', 'delete', 'garbage', 'hide', 'remove']],
  ['trash-alt', ['trash-alt', 'delete', 'garbage', 'hide', 'remove', 'trash', 'trash-o']],
  ['tree', ['tree']],
  ['tree-alt', ['tree-alt']],
  ['trello', ['trello']],
  ['triangle', ['triangle']],
  ['tripadvisor', ['tripadvisor']],
  ['trophy', ['trophy', 'achievement', 'award', 'cup', 'game', 'winner']],
  ['trophy-alt', ['trophy-alt', 'achievement', 'award', 'cup', 'game', 'star', 'winner']],
  ['truck', ['truck', 'delivery', 'shipping']],
  ['truck-container', ['truck-container']],
  ['truck-couch', ['truck-couch']],
  ['truck-loading', ['truck-loading']],
  ['truck-moving', ['truck-moving']],
  ['truck-ramp', ['truck-ramp']],
  ['tshirt', ['tshirt', 'cloth', 'clothing']],
  ['tty', ['tty']],
  ['tumblr', ['tumblr']],
  ['tumblr-square', ['tumblr-square']],
  ['tv', ['tv', 'computer', 'display', 'monitor', 'television']],
  ['tv-retro', ['tv-retro']],
  ['twitch', ['twitch']],
  ['twitter', ['twitter', 'social network', 'tweet']],
  ['twitter-square', ['twitter-square', 'social network', 'tweet']],
  ['typo3', ['typo3']],
  ['uber', ['uber']],
  ['uikit', ['uikit']],
  ['umbrella', ['umbrella', 'protection', 'rain']],
  ['umbrella-beach', ['umbrella-beach', 'protection', 'recreation', 'sun']],
  ['underline', ['underline']],
  ['undo', ['undo', 'back', 'control z', 'exchange', 'oops', 'return', 'rotate', 'swap']],
  ['undo-alt', ['undo-alt', 'back', 'control z', 'exchange', 'oops', 'return', 'swap']],
  ['uniregistry', ['uniregistry']],
  ['universal-access', ['universal-access']],
  ['university', ['university', 'bank', 'institution']],
  ['unlink', ['unlink', 'chain', 'chain-broken', 'remove']],
  ['unlock', ['unlock', 'admin', 'lock', 'password', 'protect']],
  ['unlock-alt', ['unlock-alt', 'admin', 'lock', 'password', 'protect']],
  ['untappd', ['untappd']],
  ['upload', ['upload', 'export', 'publish']],
  ['usb', ['usb']],
  ['usd-circle', ['usd-circle', '$', 'dollar-sign', 'money', 'price', 'usd']],
  ['usd-square', ['usd-square', '$', 'dollar-sign', 'money', 'price', 'usd']],
  ['user', ['user', 'account', 'avatar', 'head', 'man', 'person', 'profile']],
  ['user-alt', ['user-alt', 'account', 'avatar', 'head', 'man', 'person', 'profile']],
  ['user-alt-slash', ['user-alt-slash']],
  ['user-astronaut', ['user-astronaut', 'avatar', 'clothing', 'cosmonaut', 'space', 'suit']],
  ['user-check', ['user-check']],
  ['user-circle', ['user-circle', 'account', 'avatar', 'head', 'man', 'person', 'profile']],
  ['user-clock', ['user-clock']],
  ['user-cog', ['user-cog']],
  ['user-edit', ['user-edit']],
  ['user-friends', ['user-friends']],
  ['user-graduate', ['user-graduate', 'cap', 'clothing', 'commencement', 'gown', 'graduation', 'student']],
  ['user-lock', ['user-lock']],
  ['user-md', ['user-md', 'doctor', 'job', 'medical', 'nurse', 'occupation', 'profile']],
  ['user-minus', ['user-minus']],
  ['user-ninja', ['user-ninja', 'assassin', 'avatar', 'dangerous', 'sneaky']],
  ['user-plus', ['user-plus', 'sign-up', 'signup']],
  ['user-secret', ['user-secret', 'clothing', 'coat', 'hat', 'incognito', 'privacy', 'spy', 'whisper']],
  ['user-shield', ['user-shield']],
  ['user-slash', ['user-slash']],
  ['user-tag', ['user-tag']],
  ['user-tie', ['user-tie', 'avatar', 'business', 'clothing', 'formal']],
  ['user-times', ['user-times']],
  ['users', ['users', 'people', 'persons', 'profiles']],
  ['users-cog', ['users-cog']],
  ['ussunnah', ['ussunnah']],
  ['utensil-fork', ['utensil-fork']],
  ['utensil-knife', ['utensil-knife']],
  ['utensil-spoon', ['utensil-spoon', 'spoon']],
  ['utensils', ['utensils', 'cutlery', 'dinner', 'eat', 'food', 'knife', 'restaurant', 'spoon']],
  ['utensils-alt', ['utensils-alt']],
  ['vaadin', ['vaadin']],
  ['vector-square', ['vector-square']],
  ['venus', ['venus', 'female']],
  ['venus-double', ['venus-double']],
  ['venus-mars', ['venus-mars']],
  ['viacoin', ['viacoin']],
  ['viadeo', ['viadeo']],
  ['viadeo-square', ['viadeo-square']],
  ['vial', ['vial', 'test tube']],
  ['vials', ['vials', 'lab results', 'test tubes']],
  ['viber', ['viber']],
  ['video', ['video', 'camera', 'film', 'movie', 'record', 'video-camera']],
  ['video-plus', ['video-plus']],
  ['video-slash', ['video-slash']],
  ['vimeo', ['vimeo']],
  ['vimeo-square', ['vimeo-square']],
  ['vimeo-v', ['vimeo-v', 'vimeo']],
  ['vine', ['vine']],
  ['vk', ['vk']],
  ['vnv', ['vnv']],
  ['volleyball-ball', ['volleyball-ball']],
  ['volume-down', ['volume-down', 'audio', 'lower', 'music', 'quieter', 'sound', 'speaker']],
  ['volume-mute', ['volume-mute', 'audio', 'music', 'mute', 'sound']],
  ['volume-off', ['volume-off', 'audio', 'music', 'mute', 'sound']],
  ['volume-up', ['volume-up', 'audio', 'higher', 'louder', 'music', 'sound', 'speaker']],
  ['vuejs', ['vuejs']],
  ['walking', ['walking']],
  ['wallet', ['wallet']],
  ['warehouse', ['warehouse']],
  ['warehouse-alt', ['warehouse-alt']],
  ['watch', ['watch']],
  ['weebly', ['weebly']],
  ['weibo', ['weibo']],
  ['weight', ['weight', 'measurement', 'scale', 'weight']],
  ['weight-hanging', ['weight-hanging', 'anvil', 'heavy', 'measurement']],
  ['weixin', ['weixin']],
  ['whatsapp', ['whatsapp']],
  ['whatsapp-square', ['whatsapp-square']],
  ['wheelchair', ['wheelchair', 'handicap', 'person']],
  ['whistle', ['whistle']],
  ['whmcs', ['whmcs']],
  ['wifi', ['wifi']],
  ['wikipedia-w', ['wikipedia-w']],
  ['window', ['window']],
  ['window-alt', ['window-alt']],
  ['window-close', ['window-close']],
  ['window-maximize', ['window-maximize']],
  ['window-minimize', ['window-minimize']],
  ['window-restore', ['window-restore']],
  ['windows', ['windows', 'microsoft']],
  ['wine-glass', ['wine-glass']],
  ['wine-glass-alt', ['wine-glass-alt']],
  ['wix', ['wix']],
  ['wolf-pack-battalion', ['wolf-pack-battalion']],
  ['won-sign', ['won-sign', 'krw', 'krw']],
  ['wordpress', ['wordpress']],
  ['wordpress-simple', ['wordpress-simple']],
  ['wpbeginner', ['wpbeginner']],
  ['wpexplorer', ['wpexplorer']],
  ['wpforms', ['wpforms']],
  ['wrench', ['wrench', 'fix', 'settings', 'spanner', 'tool', 'update']],
  ['x-ray', ['x-ray', 'radiological images', 'radiology']],
  ['xbox', ['xbox']],
  ['xing', ['xing']],
  ['xing-square', ['xing-square']],
  ['y-combinator', ['y-combinator']],
  ['yahoo', ['yahoo']],
  ['yandex', ['yandex']],
  ['yandex-international', ['yandex-international']],
  ['yelp', ['yelp']],
  ['yen-sign', ['yen-sign', 'jpy']],
  ['yoast', ['yoast']],
  ['youtube', ['youtube', 'film', 'video', 'youtube-play', 'youtube-square']],
  ['youtube-square', ['youtube-square']]
]);

export function getIconMeta(icon: string): string[] {
  return iconsMeta[getPureIconName(icon)];
}

export function getPureIconName(icon: string): string {
  return icon.substring(icon.indexOf('-') + 1);
}

export function searchIconsByMeta(meta: string): string[] {
  let result = [];
  iconsMeta.forEach((iconMeta, key) => {
    if (iconMeta.filter(m => m.indexOf(meta) >= 0).length > 0) {
      result.push(key);
    }
  });

  return result;
}
