/*
 * Lumeer: Modern Data Definition and Processing Platform
 *
 * Copyright (C) since 2017 Answer Institute, s.r.o. and/or its affiliates.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export const icons: string[] = ['fa-address-book',
  'fa-address-card',
  'fa-adjust',
  'fa-alarm-clock',
  'fa-align-center',
  'fa-align-justify',
  'fa-align-left',
  'fa-align-right',
  'fa-allergies',
  'fa-ambulance',
  'fa-american-sign-language-interpreting',
  'fa-anchor',
  'fa-angle-double-down',
  'fa-angle-double-left',
  'fa-angle-double-right',
  'fa-angle-double-up',
  'fa-angle-down',
  'fa-angle-left',
  'fa-angle-right',
  'fa-angle-up',
  'fa-archive',
  'fa-arrow-alt-circle-down',
  'fa-arrow-alt-circle-left',
  'fa-arrow-alt-circle-right',
  'fa-arrow-alt-circle-up',
  'fa-arrow-alt-down',
  'fa-arrow-alt-from-bottom',
  'fa-arrow-alt-from-left',
  'fa-arrow-alt-from-right',
  'fa-arrow-alt-from-top',
  'fa-arrow-alt-left',
  'fa-arrow-alt-right',
  'fa-arrow-alt-square-down',
  'fa-arrow-alt-square-left',
  'fa-arrow-alt-square-right',
  'fa-arrow-alt-square-up',
  'fa-arrow-alt-to-bottom',
  'fa-arrow-alt-to-left',
  'fa-arrow-alt-to-right',
  'fa-arrow-alt-to-top',
  'fa-arrow-alt-up',
  'fa-arrow-circle-down',
  'fa-arrow-circle-left',
  'fa-arrow-circle-right',
  'fa-arrow-circle-up',
  'fa-arrow-down',
  'fa-arrow-from-bottom',
  'fa-arrow-from-left',
  'fa-arrow-from-right',
  'fa-arrow-from-top',
  'fa-arrow-left',
  'fa-arrow-right',
  'fa-arrow-square-down',
  'fa-arrow-square-left',
  'fa-arrow-square-right',
  'fa-arrow-square-up',
  'fa-arrow-to-bottom',
  'fa-arrow-to-left',
  'fa-arrow-to-right',
  'fa-arrow-to-top',
  'fa-arrow-up',
  'fa-arrows',
  'fa-arrows-alt',
  'fa-arrows-alt-h',
  'fa-arrows-alt-v',
  'fa-arrows-h',
  'fa-arrows-v',
  'fa-assistive-listening-systems',
  'fa-asterisk',
  'fa-at',
  'fa-audio-description',
  'fa-backward',
  'fa-badge',
  'fa-badge-check',
  'fa-balance-scale',
  'fa-ban',
  'fa-band-aid',
  'fa-barcode',
  'fa-barcode-alt',
  'fa-barcode-read',
  'fa-barcode-scan',
  'fa-bars',
  'fa-baseball',
  'fa-baseball-ball',
  'fa-basketball-ball',
  'fa-basketball-hoop',
  'fa-bath',
  'fa-battery-bolt',
  'fa-battery-empty',
  'fa-battery-full',
  'fa-battery-half',
  'fa-battery-quarter',
  'fa-battery-slash',
  'fa-battery-three-quarters',
  'fa-bed',
  'fa-beer',
  'fa-bell',
  'fa-bell-slash',
  'fa-bicycle',
  'fa-binoculars',
  'fa-birthday-cake',
  'fa-blanket',
  'fa-blind',
  'fa-bold',
  'fa-bolt',
  'fa-bomb',
  'fa-book',
  'fa-book-heart',
  'fa-bookmark',
  'fa-bowling-ball',
  'fa-bowling-pins',
  'fa-box',
  'fa-box-alt',
  'fa-box-check',
  'fa-box-fragile',
  'fa-box-full',
  'fa-box-heart',
  'fa-box-open',
  'fa-box-up',
  'fa-box-usd',
  'fa-boxes',
  'fa-boxes-alt',
  'fa-boxing-glove',
  'fa-braille',
  'fa-briefcase',
  'fa-briefcase-medical',
  'fa-browser',
  'fa-bug',
  'fa-building',
  'fa-bullhorn',
  'fa-bullseye',
  'fa-burn',
  'fa-bus',
  'fa-calculator',
  'fa-calendar',
  'fa-calendar-alt',
  'fa-calendar-check',
  'fa-calendar-edit',
  'fa-calendar-exclamation',
  'fa-calendar-minus',
  'fa-calendar-plus',
  'fa-calendar-times',
  'fa-camera',
  'fa-camera-alt',
  'fa-camera-retro',
  'fa-capsules',
  'fa-car',
  'fa-caret-circle-down',
  'fa-caret-circle-left',
  'fa-caret-circle-right',
  'fa-caret-circle-up',
  'fa-caret-down',
  'fa-caret-left',
  'fa-caret-right',
  'fa-caret-square-down',
  'fa-caret-square-left',
  'fa-caret-square-right',
  'fa-caret-square-up',
  'fa-caret-up',
  'fa-cart-arrow-down',
  'fa-cart-plus',
  'fa-certificate',
  'fa-chart-area',
  'fa-chart-bar',
  'fa-chart-line',
  'fa-chart-pie',
  'fa-check',
  'fa-check-circle',
  'fa-check-square',
  'fa-chess',
  'fa-chess-bishop',
  'fa-chess-bishop-alt',
  'fa-chess-board',
  'fa-chess-clock',
  'fa-chess-clock-alt',
  'fa-chess-king',
  'fa-chess-king-alt',
  'fa-chess-knight',
  'fa-chess-knight-alt',
  'fa-chess-pawn',
  'fa-chess-pawn-alt',
  'fa-chess-queen',
  'fa-chess-queen-alt',
  'fa-chess-rook',
  'fa-chess-rook-alt',
  'fa-chevron-circle-down',
  'fa-chevron-circle-left',
  'fa-chevron-circle-right',
  'fa-chevron-circle-up',
  'fa-chevron-double-down',
  'fa-chevron-double-left',
  'fa-chevron-double-right',
  'fa-chevron-double-up',
  'fa-chevron-down',
  'fa-chevron-left',
  'fa-chevron-right',
  'fa-chevron-square-down',
  'fa-chevron-square-left',
  'fa-chevron-square-right',
  'fa-chevron-square-up',
  'fa-chevron-up',
  'fa-child',
  'fa-circle',
  'fa-circle-notch',
  'fa-clipboard',
  'fa-clipboard-check',
  'fa-clipboard-list',
  'fa-clock',
  'fa-clone',
  'fa-closed-captioning',
  'fa-cloud',
  'fa-cloud-download',
  'fa-cloud-download-alt',
  'fa-cloud-upload',
  'fa-cloud-upload-alt',
  'fa-club',
  'fa-code',
  'fa-code-branch',
  'fa-code-commit',
  'fa-code-merge',
  'fa-coffee',
  'fa-cog',
  'fa-cogs',
  'fa-columns',
  'fa-comment',
  'fa-comment-alt',
  'fa-comment-alt-check',
  'fa-comment-alt-dots',
  'fa-comment-alt-edit',
  'fa-comment-alt-exclamation',
  'fa-comment-alt-lines',
  'fa-comment-alt-minus',
  'fa-comment-alt-plus',
  'fa-comment-alt-slash',
  'fa-comment-alt-smile',
  'fa-comment-alt-times',
  'fa-comment-check',
  'fa-comment-dots',
  'fa-comment-edit',
  'fa-comment-exclamation',
  'fa-comment-lines',
  'fa-comment-minus',
  'fa-comment-plus',
  'fa-comment-slash',
  'fa-comment-smile',
  'fa-comment-times',
  'fa-comments',
  'fa-comments-alt',
  'fa-compass',
  'fa-compress',
  'fa-compress-alt',
  'fa-compress-wide',
  'fa-container-storage',
  'fa-conveyor-belt',
  'fa-conveyor-belt-alt',
  'fa-copy',
  'fa-copyright',
  'fa-couch',
  'fa-credit-card',
  'fa-credit-card-blank',
  'fa-credit-card-front',
  'fa-cricket',
  'fa-crop',
  'fa-crosshairs',
  'fa-cube',
  'fa-cubes',
  'fa-curling',
  'fa-cut',
  'fa-database',
  'fa-deaf',
  'fa-desktop',
  'fa-desktop-alt',
  'fa-diagnoses',
  'fa-diamond',
  'fa-dna',
  'fa-dollar-sign',
  'fa-dolly',
  'fa-dolly-empty',
  'fa-dolly-flatbed',
  'fa-dolly-flatbed-alt',
  'fa-dolly-flatbed-empty',
  'fa-donate',
  'fa-dot-circle',
  'fa-dove',
  'fa-download',
  'fa-dumbbell',
  'fa-edit',
  'fa-eject',
  'fa-ellipsis-h',
  'fa-ellipsis-h-alt',
  'fa-ellipsis-v',
  'fa-ellipsis-v-alt',
  'fa-envelope',
  'fa-envelope-open',
  'fa-envelope-square',
  'fa-eraser',
  'fa-euro-sign',
  'fa-exchange',
  'fa-exchange-alt',
  'fa-exclamation',
  'fa-exclamation-circle',
  'fa-exclamation-square',
  'fa-exclamation-triangle',
  'fa-expand',
  'fa-expand-alt',
  'fa-expand-arrows',
  'fa-expand-arrows-alt',
  'fa-expand-wide',
  'fa-external-link',
  'fa-external-link-alt',
  'fa-external-link-square',
  'fa-external-link-square-alt',
  'fa-eye',
  'fa-eye-dropper',
  'fa-eye-slash',
  'fa-fast-backward',
  'fa-fast-forward',
  'fa-fax',
  'fa-female',
  'fa-field-hockey',
  'fa-fighter-jet',
  'fa-file',
  'fa-file-alt',
  'fa-file-archive',
  'fa-file-audio',
  'fa-file-check',
  'fa-file-code',
  'fa-file-edit',
  'fa-file-excel',
  'fa-file-exclamation',
  'fa-file-image',
  'fa-file-medical',
  'fa-file-medical-alt',
  'fa-file-minus',
  'fa-file-pdf',
  'fa-file-plus',
  'fa-file-powerpoint',
  'fa-file-times',
  'fa-file-video',
  'fa-file-word',
  'fa-film',
  'fa-film-alt',
  'fa-filter',
  'fa-fire',
  'fa-fire-extinguisher',
  'fa-first-aid',
  'fa-flag',
  'fa-flag-checkered',
  'fa-flask',
  'fa-folder',
  'fa-folder-open',
  'fa-font',
  'fa-football-ball',
  'fa-football-helmet',
  'fa-forklift',
  'fa-forward',
  'fa-fragile',
  'fa-frown',
  'fa-futbol',
  'fa-gamepad',
  'fa-gavel',
  'fa-gem',
  'fa-genderless',
  'fa-gift',
  'fa-glass-martini',
  'fa-globe',
  'fa-golf-ball',
  'fa-golf-club',
  'fa-graduation-cap',
  'fa-h-square',
  'fa-h1',
  'fa-h2',
  'fa-h3',
  'fa-hand-heart',
  'fa-hand-holding',
  'fa-hand-holding-box',
  'fa-hand-holding-heart',
  'fa-hand-holding-seedling',
  'fa-hand-holding-usd',
  'fa-hand-holding-water',
  'fa-hand-lizard',
  'fa-hand-paper',
  'fa-hand-peace',
  'fa-hand-point-down',
  'fa-hand-point-left',
  'fa-hand-point-right',
  'fa-hand-point-up',
  'fa-hand-pointer',
  'fa-hand-receiving',
  'fa-hand-rock',
  'fa-hand-scissors',
  'fa-hand-spock',
  'fa-hands',
  'fa-hands-heart',
  'fa-hands-helping',
  'fa-hands-usd',
  'fa-handshake',
  'fa-handshake-alt',
  'fa-hashtag',
  'fa-hdd',
  'fa-heading',
  'fa-headphones',
  'fa-heart',
  'fa-heart-circle',
  'fa-heart-square',
  'fa-heartbeat',
  'fa-hexagon',
  'fa-history',
  'fa-hockey-puck',
  'fa-hockey-sticks',
  'fa-home',
  'fa-home-heart',
  'fa-hospital',
  'fa-hospital-alt',
  'fa-hospital-symbol',
  'fa-hourglass',
  'fa-hourglass-end',
  'fa-hourglass-half',
  'fa-hourglass-start',
  'fa-i-cursor',
  'fa-id-badge',
  'fa-id-card',
  'fa-id-card-alt',
  'fa-image',
  'fa-images',
  'fa-inbox',
  'fa-inbox-in',
  'fa-inbox-out',
  'fa-indent',
  'fa-industry',
  'fa-industry-alt',
  'fa-info',
  'fa-info-circle',
  'fa-info-square',
  'fa-inventory',
  'fa-italic',
  'fa-jack-o-lantern',
  'fa-key',
  'fa-keyboard',
  'fa-lamp',
  'fa-language',
  'fa-laptop',
  'fa-leaf',
  'fa-leaf-heart',
  'fa-lemon',
  'fa-level-down',
  'fa-level-down-alt',
  'fa-level-up',
  'fa-level-up-alt',
  'fa-life-ring',
  'fa-lightbulb',
  'fa-link',
  'fa-lira-sign',
  'fa-list',
  'fa-list-alt',
  'fa-list-ol',
  'fa-list-ul',
  'fa-location-arrow',
  'fa-lock',
  'fa-lock-alt',
  'fa-lock-open',
  'fa-lock-open-alt',
  'fa-long-arrow-alt-down',
  'fa-long-arrow-alt-left',
  'fa-long-arrow-alt-right',
  'fa-long-arrow-alt-up',
  'fa-long-arrow-down',
  'fa-long-arrow-left',
  'fa-long-arrow-right',
  'fa-long-arrow-up',
  'fa-loveseat',
  'fa-low-vision',
  'fa-luchador',
  'fa-magic',
  'fa-magnet',
  'fa-male',
  'fa-map',
  'fa-map-marker',
  'fa-map-marker-alt',
  'fa-map-pin',
  'fa-map-signs',
  'fa-mars',
  'fa-mars-double',
  'fa-mars-stroke',
  'fa-mars-stroke-h',
  'fa-mars-stroke-v',
  'fa-medkit',
  'fa-meh',
  'fa-mercury',
  'fa-microchip',
  'fa-microphone',
  'fa-microphone-alt',
  'fa-microphone-slash',
  'fa-minus',
  'fa-minus-circle',
  'fa-minus-hexagon',
  'fa-minus-octagon',
  'fa-minus-square',
  'fa-mobile',
  'fa-mobile-alt',
  'fa-mobile-android',
  'fa-mobile-android-alt',
  'fa-money-bill',
  'fa-money-bill-alt',
  'fa-moon',
  'fa-motorcycle',
  'fa-mouse-pointer',
  'fa-music',
  'fa-neuter',
  'fa-newspaper',
  'fa-notes-medical',
  'fa-object-group',
  'fa-object-ungroup',
  'fa-octagon',
  'fa-outdent',
  'fa-paint-brush',
  'fa-pallet',
  'fa-pallet-alt',
  'fa-paper-plane',
  'fa-paperclip',
  'fa-parachute-box',
  'fa-paragraph',
  'fa-paste',
  'fa-pause',
  'fa-pause-circle',
  'fa-paw',
  'fa-pen',
  'fa-pen-alt',
  'fa-pen-square',
  'fa-pencil',
  'fa-pencil-alt',
  'fa-pennant',
  'fa-people-carry',
  'fa-percent',
  'fa-person-carry',
  'fa-person-dolly',
  'fa-person-dolly-empty',
  'fa-phone',
  'fa-phone-plus',
  'fa-phone-slash',
  'fa-phone-square',
  'fa-phone-volume',
  'fa-piggy-bank',
  'fa-pills',
  'fa-plane',
  'fa-plane-alt',
  'fa-play',
  'fa-play-circle',
  'fa-plug',
  'fa-plus',
  'fa-plus-circle',
  'fa-plus-hexagon',
  'fa-plus-octagon',
  'fa-plus-square',
  'fa-podcast',
  'fa-poo',
  'fa-portrait',
  'fa-pound-sign',
  'fa-power-off',
  'fa-prescription-bottle',
  'fa-prescription-bottle-alt',
  'fa-print',
  'fa-procedures',
  'fa-puzzle-piece',
  'fa-qrcode',
  'fa-question',
  'fa-question-circle',
  'fa-question-square',
  'fa-quidditch',
  'fa-quote-left',
  'fa-quote-right',
  'fa-racquet',
  'fa-ramp-loading',
  'fa-random',
  'fa-rectangle-landscape',
  'fa-rectangle-portrait',
  'fa-rectangle-wide',
  'fa-recycle',
  'fa-redo',
  'fa-redo-alt',
  'fa-registered',
  'fa-repeat',
  'fa-repeat-1',
  'fa-repeat-1-alt',
  'fa-repeat-alt',
  'fa-reply',
  'fa-reply-all',
  'fa-retweet',
  'fa-retweet-alt',
  'fa-ribbon',
  'fa-road',
  'fa-rocket',
  'fa-route',
  'fa-rss',
  'fa-rss-square',
  'fa-ruble-sign',
  'fa-rupee-sign',
  'fa-save',
  'fa-scanner',
  'fa-scanner-keyboard',
  'fa-scanner-touchscreen',
  'fa-scrubber',
  'fa-search',
  'fa-search-minus',
  'fa-search-plus',
  'fa-seedling',
  'fa-server',
  'fa-share',
  'fa-share-all',
  'fa-share-alt',
  'fa-share-alt-square',
  'fa-share-square',
  'fa-shekel-sign',
  'fa-shield',
  'fa-shield-alt',
  'fa-shield-check',
  'fa-ship',
  'fa-shipping-fast',
  'fa-shipping-timed',
  'fa-shopping-bag',
  'fa-shopping-basket',
  'fa-shopping-cart',
  'fa-shower',
  'fa-shuttlecock',
  'fa-sign',
  'fa-sign-in',
  'fa-sign-in-alt',
  'fa-sign-language',
  'fa-sign-out',
  'fa-sign-out-alt',
  'fa-signal',
  'fa-sitemap',
  'fa-sliders-h',
  'fa-sliders-h-square',
  'fa-sliders-v',
  'fa-sliders-v-square',
  'fa-smile',
  'fa-smile-plus',
  'fa-smoking',
  'fa-snowflake',
  'fa-sort',
  'fa-sort-alpha-down',
  'fa-sort-alpha-up',
  'fa-sort-amount-down',
  'fa-sort-amount-up',
  'fa-sort-down',
  'fa-sort-numeric-down',
  'fa-sort-numeric-up',
  'fa-sort-up',
  'fa-space-shuttle',
  'fa-spade',
  'fa-spinner',
  'fa-spinner-third',
  'fa-square',
  'fa-square-full',
  'fa-star',
  'fa-star-exclamation',
  'fa-star-half',
  'fa-step-backward',
  'fa-step-forward',
  'fa-stethoscope',
  'fa-sticky-note',
  'fa-stop',
  'fa-stop-circle',
  'fa-stopwatch',
  'fa-street-view',
  'fa-strikethrough',
  'fa-subscript',
  'fa-subway',
  'fa-suitcase',
  'fa-sun',
  'fa-superscript',
  'fa-sync',
  'fa-sync-alt',
  'fa-syringe',
  'fa-table',
  'fa-table-tennis',
  'fa-tablet',
  'fa-tablet-alt',
  'fa-tablet-android',
  'fa-tablet-android-alt',
  'fa-tablet-rugged',
  'fa-tablets',
  'fa-tachometer',
  'fa-tachometer-alt',
  'fa-tag',
  'fa-tags',
  'fa-tape',
  'fa-tasks',
  'fa-taxi',
  'fa-tennis-ball',
  'fa-terminal',
  'fa-text-height',
  'fa-text-width',
  'fa-th',
  'fa-th-large',
  'fa-th-list',
  'fa-thermometer',
  'fa-thermometer-empty',
  'fa-thermometer-full',
  'fa-thermometer-half',
  'fa-thermometer-quarter',
  'fa-thermometer-three-quarters',
  'fa-thumbs-down',
  'fa-thumbs-up',
  'fa-thumbtack',
  'fa-ticket',
  'fa-ticket-alt',
  'fa-times',
  'fa-times-circle',
  'fa-times-hexagon',
  'fa-times-octagon',
  'fa-times-square',
  'fa-tint',
  'fa-toggle-off',
  'fa-toggle-on',
  'fa-trademark',
  'fa-train',
  'fa-transgender',
  'fa-transgender-alt',
  'fa-trash',
  'fa-trash-alt',
  'fa-tree',
  'fa-tree-alt',
  'fa-triangle',
  'fa-trophy',
  'fa-trophy-alt',
  'fa-truck',
  'fa-truck-container',
  'fa-truck-couch',
  'fa-truck-loading',
  'fa-truck-moving',
  'fa-truck-ramp',
  'fa-tty',
  'fa-tv',
  'fa-tv-retro',
  'fa-umbrella',
  'fa-underline',
  'fa-undo',
  'fa-undo-alt',
  'fa-universal-access',
  'fa-university',
  'fa-unlink',
  'fa-unlock',
  'fa-unlock-alt',
  'fa-upload',
  'fa-usd-circle',
  'fa-usd-square',
  'fa-user',
  'fa-user-alt',
  'fa-user-alt-slash',
  'fa-user-astronaut',
  'fa-user-check',
  'fa-user-circle',
  'fa-user-clock',
  'fa-user-cog',
  'fa-user-edit',
  'fa-user-friends',
  'fa-user-graduate',
  'fa-user-lock',
  'fa-user-md',
  'fa-user-minus',
  'fa-user-ninja',
  'fa-user-plus',
  'fa-user-secret',
  'fa-user-shield',
  'fa-user-slash',
  'fa-user-tag',
  'fa-user-tie',
  'fa-user-times',
  'fa-users',
  'fa-users-cog',
  'fa-utensil-fork',
  'fa-utensil-knife',
  'fa-utensil-spoon',
  'fa-utensils',
  'fa-utensils-alt',
  'fa-venus',
  'fa-venus-double',
  'fa-venus-mars',
  'fa-vial',
  'fa-vials',
  'fa-video',
  'fa-video-plus',
  'fa-video-slash',
  'fa-volleyball-ball',
  'fa-volume-down',
  'fa-volume-mute',
  'fa-volume-off',
  'fa-volume-up',
  'fa-warehouse',
  'fa-warehouse-alt',
  'fa-watch',
  'fa-weight',
  'fa-wheelchair',
  'fa-whistle',
  'fa-wifi',
  'fa-window',
  'fa-window-alt',
  'fa-window-close',
  'fa-window-maximize',
  'fa-window-minimize',
  'fa-window-restore',
  'fa-wine-glass',
  'fa-won-sign',
  'fa-wrench',
  'fa-x-ray',
  'fa-yen-sign'];

export const solid: string[] = icons.map(color => `fas ${color}`);

export const regular: string[] = icons.map(color => `far ${color}`);

export const light: string[] = icons.map(color => `fal ${color}`);

export const brand: string[] = ['fab fa-500px',
  'fab fa-accessible-icon',
  'fab fa-accusoft',
  'fab fa-adn',
  'fab fa-adversal',
  'fab fa-affiliatetheme',
  'fab fa-algolia',
  'fab fa-amazon',
  'fab fa-amazon-pay',
  'fab fa-amilia',
  'fab fa-android',
  'fab fa-angellist',
  'fab fa-angrycreative',
  'fab fa-angular',
  'fab fa-app-store',
  'fab fa-app-store-ios',
  'fab fa-apper',
  'fab fa-apple',
  'fab fa-apple-pay',
  'fab fa-asymmetrik',
  'fab fa-audible',
  'fab fa-autoprefixer',
  'fab fa-avianex',
  'fab fa-aviato',
  'fab fa-aws',
  'fab fa-bandcamp',
  'fab fa-behance',
  'fab fa-behance-square',
  'fab fa-bimobject',
  'fab fa-bitbucket',
  'fab fa-bitcoin',
  'fab fa-bity',
  'fab fa-black-tie',
  'fab fa-blackberry',
  'fab fa-blogger',
  'fab fa-blogger-b',
  'fab fa-bluetooth',
  'fab fa-bluetooth-b',
  'fab fa-btc',
  'fab fa-buromobelexperte',
  'fab fa-buysellads',
  'fab fa-cc-amazon-pay',
  'fab fa-cc-amex',
  'fab fa-cc-apple-pay',
  'fab fa-cc-diners-club',
  'fab fa-cc-discover',
  'fab fa-cc-jcb',
  'fab fa-cc-mastercard',
  'fab fa-cc-paypal',
  'fab fa-cc-stripe',
  'fab fa-cc-visa',
  'fab fa-centercode',
  'fab fa-chrome',
  'fab fa-cloudscale',
  'fab fa-cloudsmith',
  'fab fa-cloudversify',
  'fab fa-codepen',
  'fab fa-codiepie',
  'fab fa-connectdevelop',
  'fab fa-contao',
  'fab fa-cpanel',
  'fab fa-creative-commons',
  'fab fa-creative-commons-by',
  'fab fa-creative-commons-nc',
  'fab fa-creative-commons-nc-eu',
  'fab fa-creative-commons-nc-jp',
  'fab fa-creative-commons-nd',
  'fab fa-creative-commons-pd',
  'fab fa-creative-commons-pd-alt',
  'fab fa-creative-commons-remix',
  'fab fa-creative-commons-sa',
  'fab fa-creative-commons-sampling',
  'fab fa-creative-commons-sampling-plus',
  'fab fa-creative-commons-share',
  'fab fa-creative-commons-zero',
  'fab fa-css3',
  'fab fa-css3-alt',
  'fab fa-cuttlefish',
  'fab fa-d-and-d',
  'fab fa-dashcube',
  'fab fa-delicious',
  'fab fa-deploydog',
  'fab fa-deskpro',
  'fab fa-deviantart',
  'fab fa-digg',
  'fab fa-digital-ocean',
  'fab fa-discord',
  'fab fa-discourse',
  'fab fa-dochub',
  'fab fa-docker',
  'fab fa-draft2digital',
  'fab fa-dribbble',
  'fab fa-dribbble-square',
  'fab fa-dropbox',
  'fab fa-drupal',
  'fab fa-dyalog',
  'fab fa-earlybirds',
  'fab fa-ebay',
  'fab fa-edge',
  'fab fa-elementor',
  'fab fa-ember',
  'fab fa-empire',
  'fab fa-envira',
  'fab fa-erlang',
  'fab fa-ethereum',
  'fab fa-etsy',
  'fab fa-expeditedssl',
  'fab fa-facebook',
  'fab fa-facebook-f',
  'fab fa-facebook-messenger',
  'fab fa-facebook-square',
  'fab fa-firefox',
  'fab fa-first-order',
  'fab fa-first-order-alt',
  'fab fa-firstdraft',
  'fab fa-flickr',
  'fab fa-flipboard',
  'fab fa-fly',
  'fab fa-font-awesome',
  'fab fa-font-awesome-alt',
  'fab fa-font-awesome-flag',
  'fab fa-font-awesome-logo-full',
  'fab fa-fonticons',
  'fab fa-fonticons-fi',
  'fab fa-fort-awesome',
  'fab fa-fort-awesome-alt',
  'fab fa-forumbee',
  'fab fa-foursquare',
  'fab fa-free-code-camp',
  'fab fa-freebsd',
  'fab fa-fulcrum',
  'fab fa-galactic-republic',
  'fab fa-galactic-senate',
  'fab fa-get-pocket',
  'fab fa-gg',
  'fab fa-gg-circle',
  'fab fa-git',
  'fab fa-git-square',
  'fab fa-github',
  'fab fa-github-alt',
  'fab fa-github-square',
  'fab fa-gitkraken',
  'fab fa-gitlab',
  'fab fa-gitter',
  'fab fa-glide',
  'fab fa-glide-g',
  'fab fa-gofore',
  'fab fa-goodreads',
  'fab fa-goodreads-g',
  'fab fa-google',
  'fab fa-google-drive',
  'fab fa-google-play',
  'fab fa-google-plus',
  'fab fa-google-plus-g',
  'fab fa-google-plus-square',
  'fab fa-google-wallet',
  'fab fa-gratipay',
  'fab fa-grav',
  'fab fa-gripfire',
  'fab fa-grunt',
  'fab fa-gulp',
  'fab fa-hacker-news',
  'fab fa-hacker-news-square',
  'fab fa-hips',
  'fab fa-hire-a-helper',
  'fab fa-hooli',
  'fab fa-hotjar',
  'fab fa-houzz',
  'fab fa-html5',
  'fab fa-hubspot',
  'fab fa-imdb',
  'fab fa-instagram',
  'fab fa-internet-explorer',
  'fab fa-ioxhost',
  'fab fa-itunes',
  'fab fa-itunes-note',
  'fab fa-java',
  'fab fa-jedi-order',
  'fab fa-jenkins',
  'fab fa-joget',
  'fab fa-joomla',
  'fab fa-js',
  'fab fa-js-square',
  'fab fa-jsfiddle',
  'fab fa-keybase',
  'fab fa-keycdn',
  'fab fa-kickstarter',
  'fab fa-kickstarter-k',
  'fab fa-korvue',
  'fab fa-laravel',
  'fab fa-lastfm',
  'fab fa-lastfm-square',
  'fab fa-leanpub',
  'fab fa-less',
  'fab fa-line',
  'fab fa-linkedin',
  'fab fa-linkedin-in',
  'fab fa-linode',
  'fab fa-linux',
  'fab fa-lyft',
  'fab fa-magento',
  'fab fa-mandalorian',
  'fab fa-mastodon',
  'fab fa-maxcdn',
  'fab fa-medapps',
  'fab fa-medium',
  'fab fa-medium-m',
  'fab fa-medrt',
  'fab fa-meetup',
  'fab fa-microsoft',
  'fab fa-mix',
  'fab fa-mixcloud',
  'fab fa-mizuni',
  'fab fa-modx',
  'fab fa-monero',
  'fab fa-napster',
  'fab fa-nintendo-switch',
  'fab fa-node',
  'fab fa-node-js',
  'fab fa-npm',
  'fab fa-ns8',
  'fab fa-nutritionix',
  'fab fa-odnoklassniki',
  'fab fa-odnoklassniki-square',
  'fab fa-old-republic',
  'fab fa-opencart',
  'fab fa-openid',
  'fab fa-opera',
  'fab fa-optin-monster',
  'fab fa-osi',
  'fab fa-page4',
  'fab fa-pagelines',
  'fab fa-palfed',
  'fab fa-patreon',
  'fab fa-paypal',
  'fab fa-periscope',
  'fab fa-phabricator',
  'fab fa-phoenix-framework',
  'fab fa-phoenix-squadron',
  'fab fa-php',
  'fab fa-pied-piper',
  'fab fa-pied-piper-alt',
  'fab fa-pied-piper-hat',
  'fab fa-pied-piper-pp',
  'fab fa-pinterest',
  'fab fa-pinterest-p',
  'fab fa-pinterest-square',
  'fab fa-playstation',
  'fab fa-product-hunt',
  'fab fa-pushed',
  'fab fa-python',
  'fab fa-qq',
  'fab fa-quinscape',
  'fab fa-quora',
  'fab fa-r-project',
  'fab fa-ravelry',
  'fab fa-react',
  'fab fa-readme',
  'fab fa-rebel',
  'fab fa-red-river',
  'fab fa-reddit',
  'fab fa-reddit-alien',
  'fab fa-reddit-square',
  'fab fa-rendact',
  'fab fa-renren',
  'fab fa-replyd',
  'fab fa-researchgate',
  'fab fa-resolving',
  'fab fa-rocketchat',
  'fab fa-rockrms',
  'fab fa-safari',
  'fab fa-sass',
  'fab fa-schlix',
  'fab fa-scribd',
  'fab fa-searchengin',
  'fab fa-sellcast',
  'fab fa-sellsy',
  'fab fa-servicestack',
  'fab fa-shirtsinbulk',
  'fab fa-simplybuilt',
  'fab fa-sistrix',
  'fab fa-sith',
  'fab fa-skyatlas',
  'fab fa-skype',
  'fab fa-slack',
  'fab fa-slack-hash',
  'fab fa-slideshare',
  'fab fa-snapchat',
  'fab fa-snapchat-ghost',
  'fab fa-snapchat-square',
  'fab fa-soundcloud',
  'fab fa-speakap',
  'fab fa-spotify',
  'fab fa-stack-exchange',
  'fab fa-stack-overflow',
  'fab fa-staylinked',
  'fab fa-steam',
  'fab fa-steam-square',
  'fab fa-steam-symbol',
  'fab fa-sticker-mule',
  'fab fa-strava',
  'fab fa-stripe',
  'fab fa-stripe-s',
  'fab fa-studiovinari',
  'fab fa-stumbleupon',
  'fab fa-stumbleupon-circle',
  'fab fa-superpowers',
  'fab fa-supple',
  'fab fa-teamspeak',
  'fab fa-telegram',
  'fab fa-telegram-plane',
  'fab fa-tencent-weibo',
  'fab fa-themeisle',
  'fab fa-trade-federation',
  'fab fa-trello',
  'fab fa-tripadvisor',
  'fab fa-tumblr',
  'fab fa-tumblr-square',
  'fab fa-twitch',
  'fab fa-twitter',
  'fab fa-twitter-square',
  'fab fa-typo3',
  'fab fa-uber',
  'fab fa-uikit',
  'fab fa-uniregistry',
  'fab fa-untappd',
  'fab fa-usb',
  'fab fa-ussunnah',
  'fab fa-vaadin',
  'fab fa-viacoin',
  'fab fa-viadeo',
  'fab fa-viadeo-square',
  'fab fa-viber',
  'fab fa-vimeo',
  'fab fa-vimeo-square',
  'fab fa-vimeo-v',
  'fab fa-vine',
  'fab fa-vk',
  'fab fa-vnv',
  'fab fa-vuejs',
  'fab fa-weibo',
  'fab fa-weixin',
  'fab fa-whatsapp',
  'fab fa-whatsapp-square',
  'fab fa-whmcs',
  'fab fa-wikipedia-w',
  'fab fa-windows',
  'fab fa-wolf-pack-battalion',
  'fab fa-wordpress',
  'fab fa-wordpress-simple',
  'fab fa-wpbeginner',
  'fab fa-wpexplorer',
  'fab fa-wpforms',
  'fab fa-xbox',
  'fab fa-xing',
  'fab fa-xing-square',
  'fab fa-y-combinator',
  'fab fa-yahoo',
  'fab fa-yandex',
  'fab fa-yandex-international',
  'fab fa-yelp',
  'fab fa-yoast',
  'fab fa-youtube',
  'fab fa-youtube-square'];
