/*
 * -----------------------------------------------------------------------\
 * Lumeer
 *
 * Copyright (C) since 2016 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * -----------------------------------------------------------------------/
 */

export const greyscaleColors: string[] = [
  '#0000000', '#444444', '#666666', '#999999', '#cccccc', '#eeeeee', '#f3f3f3', '#ffffff'
];

export const saturatedColors: string[] = [
  '#ff0000', '#ff9900', '#ffff00', '#00ff00', '#00ffff', '#0000ff', '#9900ff', '#ff00ff'
];

export const colors: string[] = [
  '#f4cccc', '#fce5cd', '#fff2cc', '#d9ead3', '#d0e0e3', '#cfe2f3', '#d9d2e9', '#ead1dc',
  '#ea9999', '#f9cb9c', '#ffe599', '#b6d7a8', '#a2c4c9', '#9fc5e8', '#b4a7d6', '#d5a6bd',
  '#e06666', '#f6b26b', '#ffd966', '#93c47d', '#76a5af', '#6fa8dc', '#8e7cc3', '#c27ba0',
  '#cc0000', '#e69138', '#f1c232', '#6aa84f', '#45818e', '#3d85c6', '#674ea7', '#a64d79',
  '#990000', '#b45f06', '#bf9000', '#38761d', '#134f5c', '#0b5394', '#351c75', '#741b47',
  '#660000', '#783f04', '#7f6000', '#274e13', '#0c343d', '#073763', '#20124d', '#4c1130 '
];

export const icons: string[] = ['fa fa-address-book', 'fa fa-address-card', 'fa fa-adjust', 'fa fa-alarm-clock',
  'fa fa-align-center', 'fa fa-align-justify', 'fa fa-align-left', 'fa fa-align-right', 'fa fa-ambulance',
  'fa fa-american-sign-language-interpreting', 'fa fa-anchor', 'fa fa-angle-double-down', 'fa fa-angle-double-left',
  'fa fa-angle-double-right', 'fa fa-angle-double-up', 'fa fa-angle-down', 'fa fa-angle-left', 'fa fa-angle-right',
  'fa fa-angle-up', 'fa fa-archive', 'fa fa-arrow-alt-circle-down', 'fa fa-arrow-alt-circle-left',
  'fa fa-arrow-alt-circle-right', 'fa fa-arrow-alt-circle-up', 'fa fa-arrow-alt-down', 'fa fa-arrow-alt-from-bottom',
  'fa fa-arrow-alt-from-left', 'fa fa-arrow-alt-from-right', 'fa fa-arrow-alt-from-top', 'fa fa-arrow-alt-left',
  'fa fa-arrow-alt-right', 'fa fa-arrow-alt-square-down', 'fa fa-arrow-alt-square-left',
  'fa fa-arrow-alt-square-right', 'fa fa-arrow-alt-square-up', 'fa fa-arrow-alt-to-bottom',
  'fa fa-arrow-alt-to-left', 'fa fa-arrow-alt-to-right', 'fa fa-arrow-alt-to-top', 'fa fa-arrow-alt-up',
  'fa fa-arrow-circle-down', 'fa fa-arrow-circle-left', 'fa fa-arrow-circle-right', 'fa fa-arrow-circle-up',
  'fa fa-arrow-down', 'fa fa-arrow-from-bottom', 'fa fa-arrow-from-left', 'fa fa-arrow-from-right',
  'fa fa-arrow-from-top', 'fa fa-arrow-left', 'fa fa-arrow-right', 'fa fa-arrow-square-down',
  'fa fa-arrow-square-left', 'fa fa-arrow-square-right', 'fa fa-arrow-square-up', 'fa fa-arrow-to-bottom',
  'fa fa-arrow-to-left', 'fa fa-arrow-to-right', 'fa fa-arrow-to-top', 'fa fa-arrow-up', 'fa fa-arrows',
  'fa fa-arrows-alt', 'fa fa-arrows-alt-h', 'fa fa-arrows-alt-v', 'fa fa-arrows-h', 'fa fa-arrows-v',
  'fa fa-assistive-listening-systems', 'fa fa-asterisk', 'fa fa-at', 'fa fa-audio-description', 'fa fa-backward',
  'fa fa-badge', 'fa fa-badge-check', 'fa fa-balance-scale', 'fa fa-ban', 'fa fa-barcode', 'fa fa-bars',
  'fa fa-bath', 'fa fa-battery-bolt', 'fa fa-battery-empty', 'fa fa-battery-full', 'fa fa-battery-half',
  'fa fa-battery-quarter', 'fa fa-battery-slash', 'fa fa-battery-three-quarters', 'fa fa-bed', 'fa fa-beer',
  'fa fa-bell', 'fa fa-bell-slash', 'fa fa-bicycle', 'fa fa-binoculars', 'fa fa-birthday-cake', 'fa fa-blind',
  'fa fa-bold', 'fa fa-bolt', 'fa fa-bomb', 'fa fa-book', 'fa fa-bookmark', 'fa fa-braille', 'fa fa-briefcase',
  'fa fa-browser', 'fa fa-bug', 'fa fa-building', 'fa fa-bullhorn', 'fa fa-bullseye', 'fa fa-bus', 'fa fa-calculator',
  'fa fa-calendar', 'fa fa-calendar-alt', 'fa fa-calendar-check', 'fa fa-calendar-edit', 'fa fa-calendar-exclamation',
  'fa fa-calendar-minus', 'fa fa-calendar-plus', 'fa fa-calendar-times', 'fa fa-camera', 'fa fa-camera-alt',
  'fa fa-camera-retro', 'fa fa-car', 'fa fa-caret-circle-down', 'fa fa-caret-circle-left', 'fa fa-caret-circle-right',
  'fa fa-caret-circle-up', 'fa fa-caret-down', 'fa fa-caret-left', 'fa fa-caret-right', 'fa fa-caret-square-down',
  'fa fa-caret-square-left', 'fa fa-caret-square-right', 'fa fa-caret-square-up', 'fa fa-caret-up',
  'fa fa-cart-arrow-down', 'fa fa-cart-plus', 'fa fa-certificate', 'fa fa-chart-area', 'fa fa-chart-bar',
  'fa fa-chart-line', 'fa fa-chart-pie', 'fa fa-check', 'fa fa-check-circle', 'fa fa-check-square',
  'fa fa-chevron-circle-down', 'fa fa-chevron-circle-left', 'fa fa-chevron-circle-right', 'fa fa-chevron-circle-up',
  'fa fa-chevron-double-down', 'fa fa-chevron-double-left', 'fa fa-chevron-double-right', 'fa fa-chevron-double-up',
  'fa fa-chevron-down', 'fa fa-chevron-left', 'fa fa-chevron-right', 'fa fa-chevron-square-down',
  'fa fa-chevron-square-left', 'fa fa-chevron-square-right', 'fa fa-chevron-square-up', 'fa fa-chevron-up',
  'fa fa-child', 'fa fa-circle', 'fa fa-circle-notch', 'fa fa-clipboard', 'fa fa-clock', 'fa fa-clone',
  'fa fa-closed-captioning', 'fa fa-cloud', 'fa fa-cloud-download', 'fa fa-cloud-download-alt', 'fa fa-cloud-upload',
  'fa fa-cloud-upload-alt', 'fa fa-club', 'fa fa-code', 'fa fa-code-branch', 'fa fa-code-commit', 'fa fa-code-merge',
  'fa fa-coffee', 'fa fa-cog', 'fa fa-cogs', 'fa fa-columns', 'fa fa-comment', 'fa fa-comment-alt', 'fa fa-comments',
  'fa fa-compass', 'fa fa-compress', 'fa fa-compress-wide', 'fa fa-copy', 'fa fa-copyright', 'fa fa-credit-card',
  'fa fa-credit-card-blank', 'fa fa-credit-card-front', 'fa fa-crop', 'fa fa-crosshairs', 'fa fa-cube', 'fa fa-cubes',
  'fa fa-cut', 'fa fa-database', 'fa fa-deaf', 'fa fa-desktop', 'fa fa-desktop-alt', 'fa fa-diamond',
  'fa fa-dollar-sign', 'fa fa-dot-circle', 'fa fa-download', 'fa fa-edit', 'fa fa-eject', 'fa fa-ellipsis-h',
  'fa fa-ellipsis-h-alt', 'fa fa-ellipsis-v', 'fa fa-ellipsis-v-alt', 'fa fa-envelope', 'fa fa-envelope-open',
  'fa fa-envelope-square', 'fa fa-eraser', 'fa fa-euro-sign', 'fa fa-exchange', 'fa fa-exchange-alt',
  'fa fa-exclamation', 'fa fa-exclamation-circle', 'fa fa-exclamation-square', 'fa fa-exclamation-triangle',
  'fa fa-expand', 'fa fa-expand-arrows', 'fa fa-expand-arrows-alt', 'fa fa-expand-wide', 'fa fa-external-link',
  'fa fa-external-link-alt', 'fa fa-external-link-square', 'fa fa-external-link-square-alt', 'fa fa-eye',
  'fa fa-eye-dropper', 'fa fa-eye-slash', 'fa fa-fast-backward', 'fa fa-fast-forward', 'fa fa-fax', 'fa fa-female',
  'fa fa-fighter-jet', 'fa fa-file', 'fa fa-file-alt', 'fa fa-file-archive', 'fa fa-file-audio', 'fa fa-file-check',
  'fa fa-file-code', 'fa fa-file-edit', 'fa fa-file-excel', 'fa fa-file-exclamation', 'fa fa-file-image',
  'fa fa-file-minus', 'fa fa-file-pdf', 'fa fa-file-plus', 'fa fa-file-powerpoint', 'fa fa-file-times',
  'fa fa-file-video', 'fa fa-file-word', 'fa fa-film', 'fa fa-filter', 'fa fa-fire', 'fa fa-fire-extinguisher',
  'fa fa-flag', 'fa fa-flag-checkered', 'fa fa-flask', 'fa fa-folder', 'fa fa-folder-open', 'fa fa-font',
  'fa fa-forward', 'fa fa-frown', 'fa fa-futbol', 'fa fa-gamepad', 'fa fa-gavel', 'fa fa-gem', 'fa fa-genderless',
  'fa fa-gift', 'fa fa-glass-martini', 'fa fa-globe', 'fa fa-graduation-cap', 'fa fa-h-square', 'fa fa-h1',
  'fa fa-h2', 'fa fa-h3', 'fa fa-hand-lizard', 'fa fa-hand-paper', 'fa fa-hand-peace', 'fa fa-hand-point-down',
  'fa fa-hand-point-left', 'fa fa-hand-point-right', 'fa fa-hand-point-up', 'fa fa-hand-pointer', 'fa fa-hand-rock',
  'fa fa-hand-scissors', 'fa fa-hand-spock', 'fa fa-handshake', 'fa fa-hashtag', 'fa fa-hdd', 'fa fa-heading',
  'fa fa-headphones', 'fa fa-heart', 'fa fa-heartbeat', 'fa fa-hexagon', 'fa fa-history', 'fa fa-home',
  'fa fa-hospital', 'fa fa-hourglass', 'fa fa-hourglass-end', 'fa fa-hourglass-half', 'fa fa-hourglass-start',
  'fa fa-i-cursor', 'fa fa-id-badge', 'fa fa-id-card', 'fa fa-image', 'fa fa-images', 'fa fa-inbox',
  'fa fa-inbox-in', 'fa fa-inbox-out', 'fa fa-indent', 'fa fa-industry', 'fa fa-industry-alt', 'fa fa-info',
  'fa fa-info-circle', 'fa fa-info-square', 'fa fa-italic', 'fa fa-jack-o-lantern', 'fa fa-key', 'fa fa-keyboard',
  'fa fa-language', 'fa fa-laptop', 'fa fa-leaf', 'fa fa-lemon', 'fa fa-level-down', 'fa fa-level-down-alt',
  'fa fa-level-up', 'fa fa-level-up-alt', 'fa fa-life-ring', 'fa fa-lightbulb', 'fa fa-link', 'fa fa-lira-sign',
  'fa fa-list', 'fa fa-list-alt', 'fa fa-list-ol', 'fa fa-list-ul', 'fa fa-location-arrow', 'fa fa-lock',
  'fa fa-lock-alt', 'fa fa-lock-open', 'fa fa-lock-open-alt', 'fa fa-long-arrow-alt-down', 'fa fa-long-arrow-alt-left',
  'fa fa-long-arrow-alt-right', 'fa fa-long-arrow-alt-up', 'fa fa-long-arrow-down', 'fa fa-long-arrow-left',
  'fa fa-long-arrow-right', 'fa fa-long-arrow-up', 'fa fa-low-vision', 'fa fa-magic', 'fa fa-magnet', 'fa fa-male',
  'fa fa-map', 'fa fa-map-marker', 'fa fa-map-marker-alt', 'fa fa-map-pin', 'fa fa-map-signs', 'fa fa-mars',
  'fa fa-mars-double', 'fa fa-mars-stroke', 'fa fa-mars-stroke-h', 'fa fa-mars-stroke-v', 'fa fa-medkit', 'fa fa-meh',
  'fa fa-mercury', 'fa fa-microchip', 'fa fa-microphone', 'fa fa-microphone-alt', 'fa fa-microphone-slash',
  'fa fa-minus', 'fa fa-minus-circle', 'fa fa-minus-hexagon', 'fa fa-minus-octagon', 'fa fa-minus-square',
  'fa fa-mobile', 'fa fa-mobile-alt', 'fa fa-mobile-android', 'fa fa-mobile-android-alt', 'fa fa-money-bill',
  'fa fa-money-bill-alt', 'fa fa-moon', 'fa fa-motorcycle', 'fa fa-mouse-pointer', 'fa fa-music', 'fa fa-neuter',
  'fa fa-newspaper', 'fa fa-object-group', 'fa fa-object-ungroup', 'fa fa-octagon', 'fa fa-outdent',
  'fa fa-paint-brush', 'fa fa-paper-plane', 'fa fa-paperclip', 'fa fa-paragraph', 'fa fa-paste', 'fa fa-pause',
  'fa fa-pause-circle', 'fa fa-paw', 'fa fa-pen', 'fa fa-pen-alt', 'fa fa-pen-square', 'fa fa-pencil',
  'fa fa-pencil-alt', 'fa fa-percent', 'fa fa-phone', 'fa fa-phone-slash', 'fa fa-phone-square', 'fa fa-phone-volume',
  'fa fa-plane', 'fa fa-plane-alt', 'fa fa-play', 'fa fa-play-circle', 'fa fa-plug', 'fa fa-plus', 'fa fa-plus-circle',
  'fa fa-plus-hexagon', 'fa fa-plus-octagon', 'fa fa-plus-square', 'fa fa-podcast', 'fa fa-poo', 'fa fa-portrait',
  'fa fa-pound-sign', 'fa fa-power-off', 'fa fa-print', 'fa fa-puzzle-piece', 'fa fa-qrcode', 'fa fa-question',
  'fa fa-question-circle', 'fa fa-question-square', 'fa fa-quote-left', 'fa fa-quote-right', 'fa fa-random',
  'fa fa-rectangle-landscape', 'fa fa-rectangle-portrait', 'fa fa-rectangle-wide', 'fa fa-recycle', 'fa fa-redo',
  'fa fa-redo-alt', 'fa fa-registered', 'fa fa-repeat', 'fa fa-repeat-1', 'fa fa-repeat-1-alt', 'fa fa-repeat-alt',
  'fa fa-reply', 'fa fa-reply-all', 'fa fa-retweet', 'fa fa-retweet-alt', 'fa fa-road', 'fa fa-rocket', 'fa fa-rss',
  'fa fa-rss-square', 'fa fa-ruble-sign', 'fa fa-rupee-sign', 'fa fa-save', 'fa fa-scrubber', 'fa fa-search',
  'fa fa-search-minus', 'fa fa-search-plus', 'fa fa-server', 'fa fa-share', 'fa fa-share-all', 'fa fa-share-alt',
  'fa fa-share-alt-square', 'fa fa-share-square', 'fa fa-shekel-sign', 'fa fa-shield', 'fa fa-shield-alt',
  'fa fa-shield-check', 'fa fa-ship', 'fa fa-shopping-bag', 'fa fa-shopping-basket', 'fa fa-shopping-cart',
  'fa fa-shower', 'fa fa-sign-in', 'fa fa-sign-in-alt', 'fa fa-sign-language', 'fa fa-sign-out', 'fa fa-sign-out-alt',
  'fa fa-signal', 'fa fa-sitemap', 'fa fa-sliders-h', 'fa fa-sliders-h-square', 'fa fa-sliders-v',
  'fa fa-sliders-v-square', 'fa fa-smile', 'fa fa-snowflake', 'fa fa-sort', 'fa fa-sort-alpha-down',
  'fa fa-sort-alpha-up', 'fa fa-sort-amount-down', 'fa fa-sort-amount-up', 'fa fa-sort-down',
  'fa fa-sort-numeric-down', 'fa fa-sort-numeric-up', 'fa fa-sort-up', 'fa fa-space-shuttle', 'fa fa-spade',
  'fa fa-spinner', 'fa fa-spinner-third', 'fa fa-square', 'fa fa-star', 'fa fa-star-exclamation', 'fa fa-star-half',
  'fa fa-step-backward', 'fa fa-step-forward', 'fa fa-stethoscope', 'fa fa-sticky-note', 'fa fa-stop',
  'fa fa-stop-circle', 'fa fa-stopwatch', 'fa fa-street-view', 'fa fa-strikethrough', 'fa fa-subscript',
  'fa fa-subway', 'fa fa-suitcase', 'fa fa-sun', 'fa fa-superscript', 'fa fa-sync', 'fa fa-sync-alt', 'fa fa-table',
  'fa fa-tablet', 'fa fa-tablet-alt', 'fa fa-tablet-android', 'fa fa-tablet-android-alt', 'fa fa-tachometer',
  'fa fa-tachometer-alt', 'fa fa-tag', 'fa fa-tags', 'fa fa-tasks', 'fa fa-taxi', 'fa fa-terminal',
  'fa fa-text-height', 'fa fa-text-width', 'fa fa-th', 'fa fa-th-large', 'fa fa-th-list', 'fa fa-thermometer-empty',
  'fa fa-thermometer-full', 'fa fa-thermometer-half', 'fa fa-thermometer-quarter', 'fa fa-thermometer-three-quarters',
  'fa fa-thumbs-down', 'fa fa-thumbs-up', 'fa fa-thumbtack', 'fa fa-ticket', 'fa fa-ticket-alt', 'fa fa-times',
  'fa fa-times-circle', 'fa fa-times-hexagon', 'fa fa-times-octagon', 'fa fa-times-square', 'fa fa-tint',
  'fa fa-toggle-off', 'fa fa-toggle-on', 'fa fa-trademark', 'fa fa-train', 'fa fa-transgender',
  'fa fa-transgender-alt', 'fa fa-trash', 'fa fa-trash-alt', 'fa fa-tree', 'fa fa-tree-alt', 'fa fa-triangle',
  'fa fa-trophy', 'fa fa-trophy-alt', 'fa fa-truck', 'fa fa-tty', 'fa fa-tv', 'fa fa-tv-retro',
  'fa fa-umbrella', 'fa fa-underline', 'fa fa-undo', 'fa fa-undo-alt', 'fa fa-universal-access', 'fa fa-university',
  'fa fa-unlink', 'fa fa-unlock', 'fa fa-unlock-alt', 'fa fa-upload', 'fa fa-usd-circle', 'fa fa-usd-square',
  'fa fa-user', 'fa fa-user-alt', 'fa fa-user-circle', 'fa fa-user-md', 'fa fa-user-plus', 'fa fa-user-secret',
  'fa fa-user-times', 'fa fa-users', 'fa fa-utensil-fork', 'fa fa-utensil-knife', 'fa fa-utensil-spoon',
  'fa fa-utensils', 'fa fa-utensils-alt', 'fa fa-venus', 'fa fa-venus-double', 'fa fa-venus-mars', 'fa fa-video',
  'fa fa-volume-down', 'fa fa-volume-mute', 'fa fa-volume-off', 'fa fa-volume-up', 'fa fa-watch',
  'fa fa-wheelchair', 'fa fa-wifi', 'fa fa-window', 'fa fa-window-alt', 'fa fa-window-close', 'fa fa-window-maximize',
  'fa fa-window-minimize', 'fa fa-window-restore', 'fa fa-won-sign', 'fa fa-wrench', 'fa fa-yen-sign',

  'fab fa-500px', 'fab fa-accessible-icon', 'fab fa-adn', 'fab fa-adversal',
  'fab fa-affiliatetheme', 'fab fa-algolia', 'fab fa-amazon', 'fab fa-amilia', 'fab fa-android', 'fab fa-angellist',
  'fab fa-angrycreative', 'fab fa-app-store', 'fab fa-app-store-ios', 'fab fa-apper', 'fab fa-apple',
  'fab fa-asymmetrik', 'fab fa-audible', 'fab fa-avianex', 'fab fa-aws', 'fab fa-bandcamp', 'fab fa-behance',
  'fab fa-behance-square', 'fab fa-bimobject', 'fab fa-bitbucket', 'fab fa-bitbucket-square', 'fab fa-bitcoin',
  'fab fa-bity', 'fab fa-black-tie', 'fab fa-blackberry', 'fab fa-blogger', 'fab fa-blogger-b', 'fab fa-bluetooth',
  'fab fa-bluetooth-b', 'fab fa-btc', 'fab fa-buromobelexperte', 'fab fa-buysellads', 'fab fa-cc-amex',
  'fab fa-cc-diners-club', 'fab fa-cc-discover', 'fab fa-cc-jcb', 'fab fa-cc-mastercard', 'fab fa-cc-paypal',
  'fab fa-cc-stripe', 'fab fa-cc-visa', 'fab fa-centercode', 'fab fa-chrome', 'fab fa-cloudscale',
  'fab fa-cloudsmith', 'fab fa-cloudversify', 'fab fa-codepen', 'fab fa-codiepie', 'fab fa-connectdevelop',
  'fab fa-contao', 'fab fa-cpanel', 'fab fa-creative-commons', 'fab fa-css3', 'fab fa-cuttlefish', 'fab fa-d-and-d',
  'fab fa-dashcube', 'fab fa-delicious', 'fab fa-deploydog', 'fab fa-deskpro', 'fab fa-deviantart', 'fab fa-digg',
  'fab fa-digital-ocean', 'fab fa-discord', 'fab fa-discourse', 'fab fa-dochub', 'fab fa-docker',
  'fab fa-draft2digital', 'fab fa-dribbble', 'fab fa-dribbble-square', 'fab fa-dropbox', 'fab fa-dropbox-alt',
  'fab fa-drupal', 'fab fa-dyalog', 'fab fa-earlybirds', 'fab fa-edge', 'fab fa-empire', 'fab fa-envira',
  'fab fa-erlang', 'fab fa-etsy', 'fab fa-expeditedssl', 'fab fa-facebook', 'fab fa-facebook-f',
  'fab fa-facebook-messenger', 'fab fa-facebook-square', 'fab fa-firefox', 'fab fa-first-order',
  'fab fa-firstdraft', 'fab fa-flickr', 'fab fa-font-awesome', 'fab fa-font-awesome-alt', 'fab fa-fonticons',
  'fab fa-fonticons-fi', 'fab fa-fort-awesome', 'fab fa-fort-awesome-alt', 'fab fa-forumbee', 'fab fa-foursquare',
  'fab fa-free-code-camp', 'fab fa-freebsd', 'fab fa-get-pocket', 'fab fa-gg', 'fab fa-gg-circle', 'fab fa-git',
  'fab fa-git-square', 'fab fa-github', 'fab fa-github-alt', 'fab fa-github-square', 'fab fa-gitkraken',
  'fab fa-gitlab', 'fab fa-glide', 'fab fa-glide-g', 'fab fa-gofore', 'fab fa-goodreads', 'fab fa-goodreads-g',
  'fab fa-google', 'fab fa-google-drive', 'fab fa-google-play', 'fab fa-google-plus', 'fab fa-google-plus-g',
  'fab fa-google-plus-square', 'fab fa-google-wallet', 'fab fa-gratipay', 'fab fa-grav', 'fab fa-gripfire',
  'fab fa-grunt', 'fab fa-gulp', 'fab fa-hacker-news', 'fab fa-hacker-news-square', 'fab fa-hire-a-helper',
  'fab fa-hotjar', 'fab fa-houzz', 'fab fa-html5', 'fab fa-hubspot', 'fab fa-imdb', 'fab fa-instagram',
  'fab fa-internet-explorer', 'fab fa-ioxhost', 'fab fa-itunes', 'fab fa-itunes-note', 'fab fa-jenkins',
  'fab fa-joget', 'fab fa-joomla', 'fab fa-js', 'fab fa-js-square', 'fab fa-jsfiddle', 'fab fa-keycdn',
  'fab fa-kickstarter', 'fab fa-kickstarter-k', 'fab fa-laravel', 'fab fa-lastfm', 'fab fa-lastfm-square',
  'fab fa-leanpub', 'fab fa-line', 'fab fa-linkedin', 'fab fa-linkedin-in', 'fab fa-linode', 'fab fa-linux',
  'fab fa-lyft', 'fab fa-magento', 'fab fa-maxcdn', 'fab fa-medapps', 'fab fa-medium', 'fab fa-medium-m',
  'fab fa-medrt', 'fab fa-meetup', 'fab fa-mix', 'fab fa-mixcloud', 'fab fa-mizuni', 'fab fa-modx', 'fab fa-monero',
  'fab fa-napster', 'fab fa-nintendo-switch', 'fab fa-npm', 'fab fa-nutritionix', 'fab fa-odnoklassniki',
  'fab fa-odnoklassniki-square', 'fab fa-opencart', 'fab fa-openid', 'fab fa-opera', 'fab fa-optin-monster',
  'fab fa-page4', 'fab fa-pagelines', 'fab fa-palfed', 'fab fa-patreon', 'fab fa-paypal', 'fab fa-periscope',
  'fab fa-phabricator', 'fab fa-phoenix-framework', 'fab fa-pied-piper', 'fab fa-pied-piper-alt',
  'fab fa-pied-piper-pp', 'fab fa-pinterest', 'fab fa-pinterest-p', 'fab fa-pinterest-square',
  'fab fa-playstation', 'fab fa-product-hunt', 'fab fa-pushed', 'fab fa-python', 'fab fa-qq',
  'fab fa-quora', 'fab fa-ravelry', 'fab fa-rebel', 'fab fa-red-river', 'fab fa-reddit', 'fab fa-reddit-alien',
  'fab fa-reddit-square', 'fab fa-rendact', 'fab fa-renren', 'fab fa-replyd', 'fab fa-resolving', 'fab fa-rocketchat',
  'fab fa-rockrms', 'fab fa-safari', 'fab fa-schlix', 'fab fa-scribd', 'fab fa-searchengin', 'fab fa-sellcast',
  'fab fa-sellsy', 'fab fa-servicestack', 'fab fa-shirtsinbulk', 'fab fa-simplybuilt', 'fab fa-sistrix',
  'fab fa-skyatlas', 'fab fa-skype', 'fab fa-slack', 'fab fa-slack-hash', 'fab fa-slideshare', 'fab fa-snapchat',
  'fab fa-snapchat-ghost', 'fab fa-snapchat-square', 'fab fa-soundcloud', 'fab fa-speakap', 'fab fa-spotify',
  'fab fa-stack-exchange', 'fab fa-stack-overflow', 'fab fa-staylinked', 'fab fa-steam', 'fab fa-steam-square',
  'fab fa-steam-symbol', 'fab fa-sticker-mule', 'fab fa-studiovinari', 'fab fa-stumbleupon',
  'fab fa-stumbleupon-circle', 'fab fa-superpowers', 'fab fa-supple', 'fab fa-telegram', 'fab fa-telegram-plane',
  'fab fa-tencent-weibo', 'fab fa-themeisle', 'fab fa-trello', 'fab fa-tripadvisor', 'fab fa-tumblr',
  'fab fa-tumblr-square', 'fab fa-twitch', 'fab fa-twitter', 'fab fa-twitter-square', 'fab fa-uber', 'fab fa-uikit',
  'fab fa-untappd', 'fab fa-usb', 'fab fa-ussunnah', 'fab fa-vaadin', 'fab fa-viacoin', 'fab fa-viadeo',
  'fab fa-viadeo-square', 'fab fa-viber', 'fab fa-vimeo', 'fab fa-vimeo-square', 'fab fa-vimeo-v', 'fab fa-vine',
  'fab fa-vk', 'fab fa-vnv', 'fab fa-weibo', 'fab fa-weixin', 'fab fa-whatsapp', 'fab fa-whatsapp-square',
  'fab fa-whmcs', 'fab fa-wikipedia-w', 'fab fa-windows', 'fab fa-wordpress', 'fab fa-wordpress-simple',
  'fab fa-wpbeginner', 'fab fa-wpexplorer', 'fab fa-wpforms', 'fab fa-xbox', 'fab fa-xing', 'fab fa-xing-square',
  'fab fa-y-combinator', 'fab fa-yahoo', 'fab fa-yandex', 'fab fa-yandex-international', 'fab fa-yelp',
  'fab fa-yoast', 'fab fa-youtube', 'fab fa-youtube-play'];
