/*
 * -----------------------------------------------------------------------\
 * Lumeer
 *
 * Copyright (C) since 2016 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * -----------------------------------------------------------------------/
 */

export const greyscaleColors: string[] = [
  '#0000000', '#444444', '#666666', '#999999', '#cccccc', '#eeeeee', '#f3f3f3', '#ffffff'
];

export const saturatedColors: string[] = [
  '#ff0000', '#ff9900', '#ffff00', '#00ff00', '#00ffff', '#0000ff', '#9900ff', '#ff00ff'
];

export const colors: string[] = [
  '#f4cccc', '#fce5cd', '#fff2cc', '#d9ead3', '#d0e0e3', '#cfe2f3', '#d9d2e9', '#ead1dc',
  '#ea9999', '#f9cb9c', '#ffe599', '#b6d7a8', '#a2c4c9', '#9fc5e8', '#b4a7d6', '#d5a6bd',
  '#e06666', '#f6b26b', '#ffd966', '#93c47d', '#76a5af', '#6fa8dc', '#8e7cc3', '#c27ba0',
  '#cc0000', '#e69138', '#f1c232', '#6aa84f', '#45818e', '#3d85c6', '#674ea7', '#a64d79',
  '#990000', '#b45f06', '#bf9000', '#38761d', '#134f5c', '#0b5394', '#351c75', '#741b47',
  '#660000', '#783f04', '#7f6000', '#274e13', '#0c343d', '#073763', '#20124d', '#4c1130 '
];

export const icons: string[] = ['fas fa-address-book', 'fas fa-address-card', 'fas fa-adjust', 'fas fa-alarm-clock',
  'fas fa-align-center', 'fas fa-align-justify', 'fas fa-align-left', 'fas fa-align-right', 'fas fa-ambulance',
  'fas fa-american-sign-language-interpreting', 'fas fa-anchor', 'fas fa-angle-double-down', 'fas fa-angle-double-left',
  'fas fa-angle-double-right', 'fas fa-angle-double-up', 'fas fa-angle-down', 'fas fa-angle-left', 'fas fa-angle-right',
  'fas fa-angle-up', 'fas fa-archive', 'fas fa-arrow-alt-circle-down', 'fas fa-arrow-alt-circle-left',
  'fas fa-arrow-alt-circle-right', 'fas fa-arrow-alt-circle-up', 'fas fa-arrow-alt-down', 'fas fa-arrow-alt-from-bottom',
  'fas fa-arrow-alt-from-left', 'fas fa-arrow-alt-from-right', 'fas fa-arrow-alt-from-top', 'fas fa-arrow-alt-left',
  'fas fa-arrow-alt-right', 'fas fa-arrow-alt-square-down', 'fas fa-arrow-alt-square-left',
  'fas fa-arrow-alt-square-right', 'fas fa-arrow-alt-square-up', 'fas fa-arrow-alt-to-bottom',
  'fas fa-arrow-alt-to-left', 'fas fa-arrow-alt-to-right', 'fas fa-arrow-alt-to-top', 'fas fa-arrow-alt-up',
  'fas fa-arrow-circle-down', 'fas fa-arrow-circle-left', 'fas fa-arrow-circle-right', 'fas fa-arrow-circle-up',
  'fas fa-arrow-down', 'fas fa-arrow-from-bottom', 'fas fa-arrow-from-left', 'fas fa-arrow-from-right',
  'fas fa-arrow-from-top', 'fas fa-arrow-left', 'fas fa-arrow-right', 'fas fa-arrow-square-down',
  'fas fa-arrow-square-left', 'fas fa-arrow-square-right', 'fas fa-arrow-square-up', 'fas fa-arrow-to-bottom',
  'fas fa-arrow-to-left', 'fas fa-arrow-to-right', 'fas fa-arrow-to-top', 'fas fa-arrow-up', 'fas fa-arrows',
  'fas fa-arrows-alt', 'fas fa-arrows-alt-h', 'fas fa-arrows-alt-v', 'fas fa-arrows-h', 'fas fa-arrows-v',
  'fas fa-assistive-listening-systems', 'fas fa-asterisk', 'fas fa-at', 'fas fa-audio-description', 'fas fa-backward',
  'fas fa-badge', 'fas fa-badge-check', 'fas fa-balance-scale', 'fas fa-ban', 'fas fa-barcode', 'fas fa-bars',
  'fas fa-bath', 'fas fa-battery-bolt', 'fas fa-battery-empty', 'fas fa-battery-full', 'fas fa-battery-half',
  'fas fa-battery-quarter', 'fas fa-battery-slash', 'fas fa-battery-three-quarters', 'fas fa-bed', 'fas fa-beer',
  'fas fa-bell', 'fas fa-bell-slash', 'fas fa-bicycle', 'fas fa-binoculars', 'fas fa-birthday-cake', 'fas fa-blind',
  'fas fa-bold', 'fas fa-bolt', 'fas fa-bomb', 'fas fa-book', 'fas fa-bookmark', 'fas fa-braille', 'fas fa-briefcase',
  'fas fa-browser', 'fas fa-bug', 'fas fa-building', 'fas fa-bullhorn', 'fas fa-bullseye', 'fas fa-bus', 'fas fa-calculator',
  'fas fa-calendar', 'fas fa-calendar-alt', 'fas fa-calendar-check', 'fas fa-calendar-edit', 'fas fa-calendar-exclamation',
  'fas fa-calendar-minus', 'fas fa-calendar-plus', 'fas fa-calendar-times', 'fas fa-camera', 'fas fa-camera-alt',
  'fas fa-camera-retro', 'fas fa-car', 'fas fa-caret-circle-down', 'fas fa-caret-circle-left', 'fas fa-caret-circle-right',
  'fas fa-caret-circle-up', 'fas fa-caret-down', 'fas fa-caret-left', 'fas fa-caret-right', 'fas fa-caret-square-down',
  'fas fa-caret-square-left', 'fas fa-caret-square-right', 'fas fa-caret-square-up', 'fas fa-caret-up',
  'fas fa-cart-arrow-down', 'fas fa-cart-plus', 'fas fa-certificate', 'fas fa-chart-area', 'fas fa-chart-bar',
  'fas fa-chart-line', 'fas fa-chart-pie', 'fas fa-check', 'fas fa-check-circle', 'fas fa-check-square',
  'fas fa-chevron-circle-down', 'fas fa-chevron-circle-left', 'fas fa-chevron-circle-right', 'fas fa-chevron-circle-up',
  'fas fa-chevron-double-down', 'fas fa-chevron-double-left', 'fas fa-chevron-double-right', 'fas fa-chevron-double-up',
  'fas fa-chevron-down', 'fas fa-chevron-left', 'fas fa-chevron-right', 'fas fa-chevron-square-down',
  'fas fa-chevron-square-left', 'fas fa-chevron-square-right', 'fas fa-chevron-square-up', 'fas fa-chevron-up',
  'fas fa-child', 'fas fa-circle', 'fas fa-circle-notch', 'fas fa-clipboard', 'fas fa-clock', 'fas fa-clone',
  'fas fa-closed-captioning', 'fas fa-cloud', 'fas fa-cloud-download', 'fas fa-cloud-download-alt', 'fas fa-cloud-upload',
  'fas fa-cloud-upload-alt', 'fas fa-club', 'fas fa-code', 'fas fa-code-branch', 'fas fa-code-commit', 'fas fa-code-merge',
  'fas fa-coffee', 'fas fa-cog', 'fas fa-cogs', 'fas fa-columns', 'fas fa-comment', 'fas fa-comment-alt', 'fas fa-comments',
  'fas fa-compass', 'fas fa-compress', 'fas fa-compress-wide', 'fas fa-copy', 'fas fa-copyright', 'fas fa-credit-card',
  'fas fa-credit-card-blank', 'fas fa-credit-card-front', 'fas fa-crop', 'fas fa-crosshairs', 'fas fa-cube', 'fas fa-cubes',
  'fas fa-cut', 'fas fa-database', 'fas fa-deaf', 'fas fa-desktop', 'fas fa-desktop-alt', 'fas fa-diamond',
  'fas fa-dollar-sign', 'fas fa-dot-circle', 'fas fa-download', 'fas fa-edit', 'fas fa-eject', 'fas fa-ellipsis-h',
  'fas fa-ellipsis-h-alt', 'fas fa-ellipsis-v', 'fas fa-ellipsis-v-alt', 'fas fa-envelope', 'fas fa-envelope-open',
  'fas fa-envelope-square', 'fas fa-eraser', 'fas fa-euro-sign', 'fas fa-exchange', 'fas fa-exchange-alt',
  'fas fa-exclamation', 'fas fa-exclamation-circle', 'fas fa-exclamation-square', 'fas fa-exclamation-triangle',
  'fas fa-expand', 'fas fa-expand-arrows', 'fas fa-expand-arrows-alt', 'fas fa-expand-wide', 'fas fa-external-link',
  'fas fa-external-link-alt', 'fas fa-external-link-square', 'fas fa-external-link-square-alt', 'fas fa-eye',
  'fas fa-eye-dropper', 'fas fa-eye-slash', 'fas fa-fast-backward', 'fas fa-fast-forward', 'fas fa-fax', 'fas fa-female',
  'fas fa-fighter-jet', 'fas fa-file', 'fas fa-file-alt', 'fas fa-file-archive', 'fas fa-file-audio', 'fas fa-file-check',
  'fas fa-file-code', 'fas fa-file-edit', 'fas fa-file-excel', 'fas fa-file-exclamation', 'fas fa-file-image',
  'fas fa-file-minus', 'fas fa-file-pdf', 'fas fa-file-plus', 'fas fa-file-powerpoint', 'fas fa-file-times',
  'fas fa-file-video', 'fas fa-file-word', 'fas fa-film', 'fas fa-filter', 'fas fa-fire', 'fas fa-fire-extinguisher',
  'fas fa-flag', 'fas fa-flag-checkered', 'fas fa-flask', 'fas fa-folder', 'fas fa-folder-open', 'fas fa-font',
  'fas fa-forward', 'fas fa-frown', 'fas fa-futbol', 'fas fa-gamepad', 'fas fa-gavel', 'fas fa-gem', 'fas fa-genderless',
  'fas fa-gift', 'fas fa-glass-martini', 'fas fa-globe', 'fas fa-graduation-cap', 'fas fa-h-square', 'fas fa-h1',
  'fas fa-h2', 'fas fa-h3', 'fas fa-hand-lizard', 'fas fa-hand-paper', 'fas fa-hand-peace', 'fas fa-hand-point-down',
  'fas fa-hand-point-left', 'fas fa-hand-point-right', 'fas fa-hand-point-up', 'fas fa-hand-pointer', 'fas fa-hand-rock',
  'fas fa-hand-scissors', 'fas fa-hand-spock', 'fas fa-handshake', 'fas fa-hashtag', 'fas fa-hdd', 'fas fa-heading',
  'fas fa-headphones', 'fas fa-heart', 'fas fa-heartbeat', 'fas fa-hexagon', 'fas fa-history', 'fas fa-home',
  'fas fa-hospital', 'fas fa-hourglass', 'fas fa-hourglass-end', 'fas fa-hourglass-half', 'fas fa-hourglass-start',
  'fas fa-i-cursor', 'fas fa-id-badge', 'fas fa-id-card', 'fas fa-image', 'fas fa-images', 'fas fa-inbox',
  'fas fa-inbox-in', 'fas fa-inbox-out', 'fas fa-indent', 'fas fa-industry', 'fas fa-industry-alt', 'fas fa-info',
  'fas fa-info-circle', 'fas fa-info-square', 'fas fa-italic', 'fas fa-jack-o-lantern', 'fas fa-key', 'fas fa-keyboard',
  'fas fa-language', 'fas fa-laptop', 'fas fa-leaf', 'fas fa-lemon', 'fas fa-level-down', 'fas fa-level-down-alt',
  'fas fa-level-up', 'fas fa-level-up-alt', 'fas fa-life-ring', 'fas fa-lightbulb', 'fas fa-link', 'fas fa-lira-sign',
  'fas fa-list', 'fas fa-list-alt', 'fas fa-list-ol', 'fas fa-list-ul', 'fas fa-location-arrow', 'fas fa-lock',
  'fas fa-lock-alt', 'fas fa-lock-open', 'fas fa-lock-open-alt', 'fas fa-long-arrow-alt-down', 'fas fa-long-arrow-alt-left',
  'fas fa-long-arrow-alt-right', 'fas fa-long-arrow-alt-up', 'fas fa-long-arrow-down', 'fas fa-long-arrow-left',
  'fas fa-long-arrow-right', 'fas fa-long-arrow-up', 'fas fa-low-vision', 'fas fa-magic', 'fas fa-magnet', 'fas fa-male',
  'fas fa-map', 'fas fa-map-marker', 'fas fa-map-marker-alt', 'fas fa-map-pin', 'fas fa-map-signs', 'fas fa-mars',
  'fas fa-mars-double', 'fas fa-mars-stroke', 'fas fa-mars-stroke-h', 'fas fa-mars-stroke-v', 'fas fa-medkit', 'fas fa-meh',
  'fas fa-mercury', 'fas fa-microchip', 'fas fa-microphone', 'fas fa-microphone-alt', 'fas fa-microphone-slash',
  'fas fa-minus', 'fas fa-minus-circle', 'fas fa-minus-hexagon', 'fas fa-minus-octagon', 'fas fa-minus-square',
  'fas fa-mobile', 'fas fa-mobile-alt', 'fas fa-mobile-android', 'fas fa-mobile-android-alt', 'fas fa-money-bill',
  'fas fa-money-bill-alt', 'fas fa-moon', 'fas fa-motorcycle', 'fas fa-mouse-pointer', 'fas fa-music', 'fas fa-neuter',
  'fas fa-newspaper', 'fas fa-object-group', 'fas fa-object-ungroup', 'fas fa-octagon', 'fas fa-outdent',
  'fas fa-paint-brush', 'fas fa-paper-plane', 'fas fa-paperclip', 'fas fa-paragraph', 'fas fa-paste', 'fas fa-pause',
  'fas fa-pause-circle', 'fas fa-paw', 'fas fa-pen', 'fas fa-pen-alt', 'fas fa-pen-square', 'fas fa-pencil',
  'fas fa-pencil-alt', 'fas fa-percent', 'fas fa-phone', 'fas fa-phone-slash', 'fas fa-phone-square', 'fas fa-phone-volume',
  'fas fa-plane', 'fas fa-plane-alt', 'fas fa-play', 'fas fa-play-circle', 'fas fa-plug', 'fas fa-plus', 'fas fa-plus-circle',
  'fas fa-plus-hexagon', 'fas fa-plus-octagon', 'fas fa-plus-square', 'fas fa-podcast', 'fas fa-poo', 'fas fa-portrait',
  'fas fa-pound-sign', 'fas fa-power-off', 'fas fa-print', 'fas fa-puzzle-piece', 'fas fa-qrcode', 'fas fa-question',
  'fas fa-question-circle', 'fas fa-question-square', 'fas fa-quote-left', 'fas fa-quote-right', 'fas fa-random',
  'fas fa-rectangle-landscape', 'fas fa-rectangle-portrait', 'fas fa-rectangle-wide', 'fas fa-recycle', 'fas fa-redo',
  'fas fa-redo-alt', 'fas fa-registered', 'fas fa-repeat', 'fas fa-repeat-1', 'fas fa-repeat-1-alt', 'fas fa-repeat-alt',
  'fas fa-reply', 'fas fa-reply-all', 'fas fa-retweet', 'fas fa-retweet-alt', 'fas fa-road', 'fas fa-rocket', 'fas fa-rss',
  'fas fa-rss-square', 'fas fa-ruble-sign', 'fas fa-rupee-sign', 'fas fa-save', 'fas fa-scrubber', 'fas fa-search',
  'fas fa-search-minus', 'fas fa-search-plus', 'fas fa-server', 'fas fa-share', 'fas fa-share-all', 'fas fa-share-alt',
  'fas fa-share-alt-square', 'fas fa-share-square', 'fas fa-shekel-sign', 'fas fa-shield', 'fas fa-shield-alt',
  'fas fa-shield-check', 'fas fa-ship', 'fas fa-shopping-bag', 'fas fa-shopping-basket', 'fas fa-shopping-cart',
  'fas fa-shower', 'fas fa-sign-in', 'fas fa-sign-in-alt', 'fas fa-sign-language', 'fas fa-sign-out', 'fas fa-sign-out-alt',
  'fas fa-signal', 'fas fa-sitemap', 'fas fa-sliders-h', 'fas fa-sliders-h-square', 'fas fa-sliders-v',
  'fas fa-sliders-v-square', 'fas fa-smile', 'fas fa-snowflake', 'fas fa-sort', 'fas fa-sort-alpha-down',
  'fas fa-sort-alpha-up', 'fas fa-sort-amount-down', 'fas fa-sort-amount-up', 'fas fa-sort-down',
  'fas fa-sort-numeric-down', 'fas fa-sort-numeric-up', 'fas fa-sort-up', 'fas fa-space-shuttle', 'fas fa-spade',
  'fas fa-spinner', 'fas fa-spinner-third', 'fas fa-square', 'fas fa-star', 'fas fa-star-exclamation', 'fas fa-star-half',
  'fas fa-step-backward', 'fas fa-step-forward', 'fas fa-stethoscope', 'fas fa-sticky-note', 'fas fa-stop',
  'fas fa-stop-circle', 'fas fa-stopwatch', 'fas fa-street-view', 'fas fa-strikethrough', 'fas fa-subscript',
  'fas fa-subway', 'fas fa-suitcase', 'fas fa-sun', 'fas fa-superscript', 'fas fa-sync', 'fas fa-sync-alt', 'fas fa-table',
  'fas fa-tablet', 'fas fa-tablet-alt', 'fas fa-tablet-android', 'fas fa-tablet-android-alt', 'fas fa-tachometer',
  'fas fa-tachometer-alt', 'fas fa-tag', 'fas fa-tags', 'fas fa-tasks', 'fas fa-taxi', 'fas fa-terminal',
  'fas fa-text-height', 'fas fa-text-width', 'fas fa-th', 'fas fa-th-large', 'fas fa-th-list', 'fas fa-thermometer-empty',
  'fas fa-thermometer-full', 'fas fa-thermometer-half', 'fas fa-thermometer-quarter', 'fas fa-thermometer-three-quarters',
  'fas fa-thumbs-down', 'fas fa-thumbs-up', 'fas fa-thumbtack', 'fas fa-ticket', 'fas fa-ticket-alt', 'fas fa-times',
  'fas fa-times-circle', 'fas fa-times-hexagon', 'fas fa-times-octagon', 'fas fa-times-square', 'fas fa-tint',
  'fas fa-toggle-off', 'fas fa-toggle-on', 'fas fa-trademark', 'fas fa-train', 'fas fa-transgender',
  'fas fa-transgender-alt', 'fas fa-trash', 'fas fa-trash-alt', 'fas fa-tree', 'fas fa-tree-alt', 'fas fa-triangle',
  'fas fa-trophy', 'fas fa-trophy-alt', 'fas fa-truck', 'fas fa-tty', 'fas fa-tv', 'fas fa-tv-retro',
  'fas fa-umbrella', 'fas fa-underline', 'fas fa-undo', 'fas fa-undo-alt', 'fas fa-universal-access', 'fas fa-university',
  'fas fa-unlink', 'fas fa-unlock', 'fas fa-unlock-alt', 'fas fa-upload', 'fas fa-usd-circle', 'fas fa-usd-square',
  'fas fa-user', 'fas fa-user-alt', 'fas fa-user-circle', 'fas fa-user-md', 'fas fa-user-plus', 'fas fa-user-secret',
  'fas fa-user-times', 'fas fa-users', 'fas fa-utensil-fork', 'fas fa-utensil-knife', 'fas fa-utensil-spoon',
  'fas fa-utensils', 'fas fa-utensils-alt', 'fas fa-venus', 'fas fa-venus-double', 'fas fa-venus-mars', 'fas fa-video',
  'fas fa-volume-down', 'fas fa-volume-mute', 'fas fa-volume-off', 'fas fa-volume-up', 'fas fa-watch',
  'fas fa-wheelchair', 'fas fa-wifi', 'fas fa-window', 'fas fa-window-alt', 'fas fa-window-close', 'fas fa-window-maximize',
  'fas fa-window-minimize', 'fas fa-window-restore', 'fas fa-won-sign', 'fas fa-wrench', 'fas fa-yen-sign',

  'far fa-address-book', 'far fa-address-card', 'far fa-adjust', 'far fa-alarm-clock',
  'far fa-align-center', 'far fa-align-justify', 'far fa-align-left', 'far fa-align-right', 'far fa-ambulance',
  'far fa-american-sign-language-interpreting', 'far fa-anchor', 'far fa-angle-double-down', 'far fa-angle-double-left',
  'far fa-angle-double-right', 'far fa-angle-double-up', 'far fa-angle-down', 'far fa-angle-left', 'far fa-angle-right',
  'far fa-angle-up', 'far fa-archive', 'far fa-arrow-alt-circle-down', 'far fa-arrow-alt-circle-left',
  'far fa-arrow-alt-circle-right', 'far fa-arrow-alt-circle-up', 'far fa-arrow-alt-down', 'far fa-arrow-alt-from-bottom',
  'far fa-arrow-alt-from-left', 'far fa-arrow-alt-from-right', 'far fa-arrow-alt-from-top', 'far fa-arrow-alt-left',
  'far fa-arrow-alt-right', 'far fa-arrow-alt-square-down', 'far fa-arrow-alt-square-left',
  'far fa-arrow-alt-square-right', 'far fa-arrow-alt-square-up', 'far fa-arrow-alt-to-bottom',
  'far fa-arrow-alt-to-left', 'far fa-arrow-alt-to-right', 'far fa-arrow-alt-to-top', 'far fa-arrow-alt-up',
  'far fa-arrow-circle-down', 'far fa-arrow-circle-left', 'far fa-arrow-circle-right', 'far fa-arrow-circle-up',
  'far fa-arrow-down', 'far fa-arrow-from-bottom', 'far fa-arrow-from-left', 'far fa-arrow-from-right',
  'far fa-arrow-from-top', 'far fa-arrow-left', 'far fa-arrow-right', 'far fa-arrow-square-down',
  'far fa-arrow-square-left', 'far fa-arrow-square-right', 'far fa-arrow-square-up', 'far fa-arrow-to-bottom',
  'far fa-arrow-to-left', 'far fa-arrow-to-right', 'far fa-arrow-to-top', 'far fa-arrow-up', 'far fa-arrows',
  'far fa-arrows-alt', 'far fa-arrows-alt-h', 'far fa-arrows-alt-v', 'far fa-arrows-h', 'far fa-arrows-v',
  'far fa-assistive-listening-systems', 'far fa-asterisk', 'far fa-at', 'far fa-audio-description', 'far fa-backward',
  'far fa-badge', 'far fa-badge-check', 'far fa-balance-scale', 'far fa-ban', 'far fa-barcode', 'far fa-bars',
  'far fa-bath', 'far fa-battery-bolt', 'far fa-battery-empty', 'far fa-battery-full', 'far fa-battery-half',
  'far fa-battery-quarter', 'far fa-battery-slash', 'far fa-battery-three-quarters', 'far fa-bed', 'far fa-beer',
  'far fa-bell', 'far fa-bell-slash', 'far fa-bicycle', 'far fa-binoculars', 'far fa-birthday-cake', 'far fa-blind',
  'far fa-bold', 'far fa-bolt', 'far fa-bomb', 'far fa-book', 'far fa-bookmark', 'far fa-braille', 'far fa-briefcase',
  'far fa-browser', 'far fa-bug', 'far fa-building', 'far fa-bullhorn', 'far fa-bullseye', 'far fa-bus', 'far fa-calculator',
  'far fa-calendar', 'far fa-calendar-alt', 'far fa-calendar-check', 'far fa-calendar-edit', 'far fa-calendar-exclamation',
  'far fa-calendar-minus', 'far fa-calendar-plus', 'far fa-calendar-times', 'far fa-camera', 'far fa-camera-alt',
  'far fa-camera-retro', 'far fa-car', 'far fa-caret-circle-down', 'far fa-caret-circle-left', 'far fa-caret-circle-right',
  'far fa-caret-circle-up', 'far fa-caret-down', 'far fa-caret-left', 'far fa-caret-right', 'far fa-caret-square-down',
  'far fa-caret-square-left', 'far fa-caret-square-right', 'far fa-caret-square-up', 'far fa-caret-up',
  'far fa-cart-arrow-down', 'far fa-cart-plus', 'far fa-certificate', 'far fa-chart-area', 'far fa-chart-bar',
  'far fa-chart-line', 'far fa-chart-pie', 'far fa-check', 'far fa-check-circle', 'far fa-check-square',
  'far fa-chevron-circle-down', 'far fa-chevron-circle-left', 'far fa-chevron-circle-right', 'far fa-chevron-circle-up',
  'far fa-chevron-double-down', 'far fa-chevron-double-left', 'far fa-chevron-double-right', 'far fa-chevron-double-up',
  'far fa-chevron-down', 'far fa-chevron-left', 'far fa-chevron-right', 'far fa-chevron-square-down',
  'far fa-chevron-square-left', 'far fa-chevron-square-right', 'far fa-chevron-square-up', 'far fa-chevron-up',
  'far fa-child', 'far fa-circle', 'far fa-circle-notch', 'far fa-clipboard', 'far fa-clock', 'far fa-clone',
  'far fa-closed-captioning', 'far fa-cloud', 'far fa-cloud-download', 'far fa-cloud-download-alt', 'far fa-cloud-upload',
  'far fa-cloud-upload-alt', 'far fa-club', 'far fa-code', 'far fa-code-branch', 'far fa-code-commit', 'far fa-code-merge',
  'far fa-coffee', 'far fa-cog', 'far fa-cogs', 'far fa-columns', 'far fa-comment', 'far fa-comment-alt', 'far fa-comments',
  'far fa-compass', 'far fa-compress', 'far fa-compress-wide', 'far fa-copy', 'far fa-copyright', 'far fa-credit-card',
  'far fa-credit-card-blank', 'far fa-credit-card-front', 'far fa-crop', 'far fa-crosshairs', 'far fa-cube', 'far fa-cubes',
  'far fa-cut', 'far fa-database', 'far fa-deaf', 'far fa-desktop', 'far fa-desktop-alt', 'far fa-diamond',
  'far fa-dollar-sign', 'far fa-dot-circle', 'far fa-download', 'far fa-edit', 'far fa-eject', 'far fa-ellipsis-h',
  'far fa-ellipsis-h-alt', 'far fa-ellipsis-v', 'far fa-ellipsis-v-alt', 'far fa-envelope', 'far fa-envelope-open',
  'far fa-envelope-square', 'far fa-eraser', 'far fa-euro-sign', 'far fa-exchange', 'far fa-exchange-alt',
  'far fa-exclamation', 'far fa-exclamation-circle', 'far fa-exclamation-square', 'far fa-exclamation-triangle',
  'far fa-expand', 'far fa-expand-arrows', 'far fa-expand-arrows-alt', 'far fa-expand-wide', 'far fa-external-link',
  'far fa-external-link-alt', 'far fa-external-link-square', 'far fa-external-link-square-alt', 'far fa-eye',
  'far fa-eye-dropper', 'far fa-eye-slash', 'far fa-fast-backward', 'far fa-fast-forward', 'far fa-fax', 'far fa-female',
  'far fa-fighter-jet', 'far fa-file', 'far fa-file-alt', 'far fa-file-archive', 'far fa-file-audio', 'far fa-file-check',
  'far fa-file-code', 'far fa-file-edit', 'far fa-file-excel', 'far fa-file-exclamation', 'far fa-file-image',
  'far fa-file-minus', 'far fa-file-pdf', 'far fa-file-plus', 'far fa-file-powerpoint', 'far fa-file-times',
  'far fa-file-video', 'far fa-file-word', 'far fa-film', 'far fa-filter', 'far fa-fire', 'far fa-fire-extinguisher',
  'far fa-flag', 'far fa-flag-checkered', 'far fa-flask', 'far fa-folder', 'far fa-folder-open', 'far fa-font',
  'far fa-forward', 'far fa-frown', 'far fa-futbol', 'far fa-gamepad', 'far fa-gavel', 'far fa-gem', 'far fa-genderless',
  'far fa-gift', 'far fa-glass-martini', 'far fa-globe', 'far fa-graduation-cap', 'far fa-h-square', 'far fa-h1',
  'far fa-h2', 'far fa-h3', 'far fa-hand-lizard', 'far fa-hand-paper', 'far fa-hand-peace', 'far fa-hand-point-down',
  'far fa-hand-point-left', 'far fa-hand-point-right', 'far fa-hand-point-up', 'far fa-hand-pointer', 'far fa-hand-rock',
  'far fa-hand-scissors', 'far fa-hand-spock', 'far fa-handshake', 'far fa-hashtag', 'far fa-hdd', 'far fa-heading',
  'far fa-headphones', 'far fa-heart', 'far fa-heartbeat', 'far fa-hexagon', 'far fa-history', 'far fa-home',
  'far fa-hospital', 'far fa-hourglass', 'far fa-hourglass-end', 'far fa-hourglass-half', 'far fa-hourglass-start',
  'far fa-i-cursor', 'far fa-id-badge', 'far fa-id-card', 'far fa-image', 'far fa-images', 'far fa-inbox',
  'far fa-inbox-in', 'far fa-inbox-out', 'far fa-indent', 'far fa-industry', 'far fa-industry-alt', 'far fa-info',
  'far fa-info-circle', 'far fa-info-square', 'far fa-italic', 'far fa-jack-o-lantern', 'far fa-key', 'far fa-keyboard',
  'far fa-language', 'far fa-laptop', 'far fa-leaf', 'far fa-lemon', 'far fa-level-down', 'far fa-level-down-alt',
  'far fa-level-up', 'far fa-level-up-alt', 'far fa-life-ring', 'far fa-lightbulb', 'far fa-link', 'far fa-lira-sign',
  'far fa-list', 'far fa-list-alt', 'far fa-list-ol', 'far fa-list-ul', 'far fa-location-arrow', 'far fa-lock',
  'far fa-lock-alt', 'far fa-lock-open', 'far fa-lock-open-alt', 'far fa-long-arrow-alt-down', 'far fa-long-arrow-alt-left',
  'far fa-long-arrow-alt-right', 'far fa-long-arrow-alt-up', 'far fa-long-arrow-down', 'far fa-long-arrow-left',
  'far fa-long-arrow-right', 'far fa-long-arrow-up', 'far fa-low-vision', 'far fa-magic', 'far fa-magnet', 'far fa-male',
  'far fa-map', 'far fa-map-marker', 'far fa-map-marker-alt', 'far fa-map-pin', 'far fa-map-signs', 'far fa-mars',
  'far fa-mars-double', 'far fa-mars-stroke', 'far fa-mars-stroke-h', 'far fa-mars-stroke-v', 'far fa-medkit', 'far fa-meh',
  'far fa-mercury', 'far fa-microchip', 'far fa-microphone', 'far fa-microphone-alt', 'far fa-microphone-slash',
  'far fa-minus', 'far fa-minus-circle', 'far fa-minus-hexagon', 'far fa-minus-octagon', 'far fa-minus-square',
  'far fa-mobile', 'far fa-mobile-alt', 'far fa-mobile-android', 'far fa-mobile-android-alt', 'far fa-money-bill',
  'far fa-money-bill-alt', 'far fa-moon', 'far fa-motorcycle', 'far fa-mouse-pointer', 'far fa-music', 'far fa-neuter',
  'far fa-newspaper', 'far fa-object-group', 'far fa-object-ungroup', 'far fa-octagon', 'far fa-outdent',
  'far fa-paint-brush', 'far fa-paper-plane', 'far fa-paperclip', 'far fa-paragraph', 'far fa-paste', 'far fa-pause',
  'far fa-pause-circle', 'far fa-paw', 'far fa-pen', 'far fa-pen-alt', 'far fa-pen-square', 'far fa-pencil',
  'far fa-pencil-alt', 'far fa-percent', 'far fa-phone', 'far fa-phone-slash', 'far fa-phone-square', 'far fa-phone-volume',
  'far fa-plane', 'far fa-plane-alt', 'far fa-play', 'far fa-play-circle', 'far fa-plug', 'far fa-plus', 'far fa-plus-circle',
  'far fa-plus-hexagon', 'far fa-plus-octagon', 'far fa-plus-square', 'far fa-podcast', 'far fa-poo', 'far fa-portrait',
  'far fa-pound-sign', 'far fa-power-off', 'far fa-print', 'far fa-puzzle-piece', 'far fa-qrcode', 'far fa-question',
  'far fa-question-circle', 'far fa-question-square', 'far fa-quote-left', 'far fa-quote-right', 'far fa-random',
  'far fa-rectangle-landscape', 'far fa-rectangle-portrait', 'far fa-rectangle-wide', 'far fa-recycle', 'far fa-redo',
  'far fa-redo-alt', 'far fa-registered', 'far fa-repeat', 'far fa-repeat-1', 'far fa-repeat-1-alt', 'far fa-repeat-alt',
  'far fa-reply', 'far fa-reply-all', 'far fa-retweet', 'far fa-retweet-alt', 'far fa-road', 'far fa-rocket', 'far fa-rss',
  'far fa-rss-square', 'far fa-ruble-sign', 'far fa-rupee-sign', 'far fa-save', 'far fa-scrubber', 'far fa-search',
  'far fa-search-minus', 'far fa-search-plus', 'far fa-server', 'far fa-share', 'far fa-share-all', 'far fa-share-alt',
  'far fa-share-alt-square', 'far fa-share-square', 'far fa-shekel-sign', 'far fa-shield', 'far fa-shield-alt',
  'far fa-shield-check', 'far fa-ship', 'far fa-shopping-bag', 'far fa-shopping-basket', 'far fa-shopping-cart',
  'far fa-shower', 'far fa-sign-in', 'far fa-sign-in-alt', 'far fa-sign-language', 'far fa-sign-out', 'far fa-sign-out-alt',
  'far fa-signal', 'far fa-sitemap', 'far fa-sliders-h', 'far fa-sliders-h-square', 'far fa-sliders-v',
  'far fa-sliders-v-square', 'far fa-smile', 'far fa-snowflake', 'far fa-sort', 'far fa-sort-alpha-down',
  'far fa-sort-alpha-up', 'far fa-sort-amount-down', 'far fa-sort-amount-up', 'far fa-sort-down',
  'far fa-sort-numeric-down', 'far fa-sort-numeric-up', 'far fa-sort-up', 'far fa-space-shuttle', 'far fa-spade',
  'far fa-spinner', 'far fa-spinner-third', 'far fa-square', 'far fa-star', 'far fa-star-exclamation', 'far fa-star-half',
  'far fa-step-backward', 'far fa-step-forward', 'far fa-stethoscope', 'far fa-sticky-note', 'far fa-stop',
  'far fa-stop-circle', 'far fa-stopwatch', 'far fa-street-view', 'far fa-strikethrough', 'far fa-subscript',
  'far fa-subway', 'far fa-suitcase', 'far fa-sun', 'far fa-superscript', 'far fa-sync', 'far fa-sync-alt', 'far fa-table',
  'far fa-tablet', 'far fa-tablet-alt', 'far fa-tablet-android', 'far fa-tablet-android-alt', 'far fa-tachometer',
  'far fa-tachometer-alt', 'far fa-tag', 'far fa-tags', 'far fa-tasks', 'far fa-taxi', 'far fa-terminal',
  'far fa-text-height', 'far fa-text-width', 'far fa-th', 'far fa-th-large', 'far fa-th-list', 'far fa-thermometer-empty',
  'far fa-thermometer-full', 'far fa-thermometer-half', 'far fa-thermometer-quarter', 'far fa-thermometer-three-quarters',
  'far fa-thumbs-down', 'far fa-thumbs-up', 'far fa-thumbtack', 'far fa-ticket', 'far fa-ticket-alt', 'far fa-times',
  'far fa-times-circle', 'far fa-times-hexagon', 'far fa-times-octagon', 'far fa-times-square', 'far fa-tint',
  'far fa-toggle-off', 'far fa-toggle-on', 'far fa-trademark', 'far fa-train', 'far fa-transgender',
  'far fa-transgender-alt', 'far fa-trash', 'far fa-trash-alt', 'far fa-tree', 'far fa-tree-alt', 'far fa-triangle',
  'far fa-trophy', 'far fa-trophy-alt', 'far fa-truck', 'far fa-tty', 'far fa-tv', 'far fa-tv-retro',
  'far fa-umbrella', 'far fa-underline', 'far fa-undo', 'far fa-undo-alt', 'far fa-universal-access', 'far fa-university',
  'far fa-unlink', 'far fa-unlock', 'far fa-unlock-alt', 'far fa-upload', 'far fa-usd-circle', 'far fa-usd-square',
  'far fa-user', 'far fa-user-alt', 'far fa-user-circle', 'far fa-user-md', 'far fa-user-plus', 'far fa-user-secret',
  'far fa-user-times', 'far fa-users', 'far fa-utensil-fork', 'far fa-utensil-knife', 'far fa-utensil-spoon',
  'far fa-utensils', 'far fa-utensils-alt', 'far fa-venus', 'far fa-venus-double', 'far fa-venus-mars', 'far fa-video',
  'far fa-volume-down', 'far fa-volume-mute', 'far fa-volume-off', 'far fa-volume-up', 'far fa-watch',
  'far fa-wheelchair', 'far fa-wifi', 'far fa-window', 'far fa-window-alt', 'far fa-window-close', 'far fa-window-maximize',
  'far fa-window-minimize', 'far fa-window-restore', 'far fa-won-sign', 'far fa-wrench', 'far fa-yen-sign',

  'fal fa-address-book', 'fal fa-address-card', 'fal fa-adjust', 'fal fa-alarm-clock',
  'fal fa-align-center', 'fal fa-align-justify', 'fal fa-align-left', 'fal fa-align-right', 'fal fa-ambulance',
  'fal fa-american-sign-language-interpreting', 'fal fa-anchor', 'fal fa-angle-double-down', 'fal fa-angle-double-left',
  'fal fa-angle-double-right', 'fal fa-angle-double-up', 'fal fa-angle-down', 'fal fa-angle-left', 'fal fa-angle-right',
  'fal fa-angle-up', 'fal fa-archive', 'fal fa-arrow-alt-circle-down', 'fal fa-arrow-alt-circle-left',
  'fal fa-arrow-alt-circle-right', 'fal fa-arrow-alt-circle-up', 'fal fa-arrow-alt-down', 'fal fa-arrow-alt-from-bottom',
  'fal fa-arrow-alt-from-left', 'fal fa-arrow-alt-from-right', 'fal fa-arrow-alt-from-top', 'fal fa-arrow-alt-left',
  'fal fa-arrow-alt-right', 'fal fa-arrow-alt-square-down', 'fal fa-arrow-alt-square-left',
  'fal fa-arrow-alt-square-right', 'fal fa-arrow-alt-square-up', 'fal fa-arrow-alt-to-bottom',
  'fal fa-arrow-alt-to-left', 'fal fa-arrow-alt-to-right', 'fal fa-arrow-alt-to-top', 'fal fa-arrow-alt-up',
  'fal fa-arrow-circle-down', 'fal fa-arrow-circle-left', 'fal fa-arrow-circle-right', 'fal fa-arrow-circle-up',
  'fal fa-arrow-down', 'fal fa-arrow-from-bottom', 'fal fa-arrow-from-left', 'fal fa-arrow-from-right',
  'fal fa-arrow-from-top', 'fal fa-arrow-left', 'fal fa-arrow-right', 'fal fa-arrow-square-down',
  'fal fa-arrow-square-left', 'fal fa-arrow-square-right', 'fal fa-arrow-square-up', 'fal fa-arrow-to-bottom',
  'fal fa-arrow-to-left', 'fal fa-arrow-to-right', 'fal fa-arrow-to-top', 'fal fa-arrow-up', 'fal fa-arrows',
  'fal fa-arrows-alt', 'fal fa-arrows-alt-h', 'fal fa-arrows-alt-v', 'fal fa-arrows-h', 'fal fa-arrows-v',
  'fal fa-assistive-listening-systems', 'fal fa-asterisk', 'fal fa-at', 'fal fa-audio-description', 'fal fa-backward',
  'fal fa-badge', 'fal fa-badge-check', 'fal fa-balance-scale', 'fal fa-ban', 'fal fa-barcode', 'fal fa-bars',
  'fal fa-bath', 'fal fa-battery-bolt', 'fal fa-battery-empty', 'fal fa-battery-full', 'fal fa-battery-half',
  'fal fa-battery-quarter', 'fal fa-battery-slash', 'fal fa-battery-three-quarters', 'fal fa-bed', 'fal fa-beer',
  'fal fa-bell', 'fal fa-bell-slash', 'fal fa-bicycle', 'fal fa-binoculars', 'fal fa-birthday-cake', 'fal fa-blind',
  'fal fa-bold', 'fal fa-bolt', 'fal fa-bomb', 'fal fa-book', 'fal fa-bookmark', 'fal fa-braille', 'fal fa-briefcase',
  'fal fa-browser', 'fal fa-bug', 'fal fa-building', 'fal fa-bullhorn', 'fal fa-bullseye', 'fal fa-bus', 'fal fa-calculator',
  'fal fa-calendar', 'fal fa-calendar-alt', 'fal fa-calendar-check', 'fal fa-calendar-edit', 'fal fa-calendar-exclamation',
  'fal fa-calendar-minus', 'fal fa-calendar-plus', 'fal fa-calendar-times', 'fal fa-camera', 'fal fa-camera-alt',
  'fal fa-camera-retro', 'fal fa-car', 'fal fa-caret-circle-down', 'fal fa-caret-circle-left', 'fal fa-caret-circle-right',
  'fal fa-caret-circle-up', 'fal fa-caret-down', 'fal fa-caret-left', 'fal fa-caret-right', 'fal fa-caret-square-down',
  'fal fa-caret-square-left', 'fal fa-caret-square-right', 'fal fa-caret-square-up', 'fal fa-caret-up',
  'fal fa-cart-arrow-down', 'fal fa-cart-plus', 'fal fa-certificate', 'fal fa-chart-area', 'fal fa-chart-bar',
  'fal fa-chart-line', 'fal fa-chart-pie', 'fal fa-check', 'fal fa-check-circle', 'fal fa-check-square',
  'fal fa-chevron-circle-down', 'fal fa-chevron-circle-left', 'fal fa-chevron-circle-right', 'fal fa-chevron-circle-up',
  'fal fa-chevron-double-down', 'fal fa-chevron-double-left', 'fal fa-chevron-double-right', 'fal fa-chevron-double-up',
  'fal fa-chevron-down', 'fal fa-chevron-left', 'fal fa-chevron-right', 'fal fa-chevron-square-down',
  'fal fa-chevron-square-left', 'fal fa-chevron-square-right', 'fal fa-chevron-square-up', 'fal fa-chevron-up',
  'fal fa-child', 'fal fa-circle', 'fal fa-circle-notch', 'fal fa-clipboard', 'fal fa-clock', 'fal fa-clone',
  'fal fa-closed-captioning', 'fal fa-cloud', 'fal fa-cloud-download', 'fal fa-cloud-download-alt', 'fal fa-cloud-upload',
  'fal fa-cloud-upload-alt', 'fal fa-club', 'fal fa-code', 'fal fa-code-branch', 'fal fa-code-commit', 'fal fa-code-merge',
  'fal fa-coffee', 'fal fa-cog', 'fal fa-cogs', 'fal fa-columns', 'fal fa-comment', 'fal fa-comment-alt', 'fal fa-comments',
  'fal fa-compass', 'fal fa-compress', 'fal fa-compress-wide', 'fal fa-copy', 'fal fa-copyright', 'fal fa-credit-card',
  'fal fa-credit-card-blank', 'fal fa-credit-card-front', 'fal fa-crop', 'fal fa-crosshairs', 'fal fa-cube', 'fal fa-cubes',
  'fal fa-cut', 'fal fa-database', 'fal fa-deaf', 'fal fa-desktop', 'fal fa-desktop-alt', 'fal fa-diamond',
  'fal fa-dollar-sign', 'fal fa-dot-circle', 'fal fa-download', 'fal fa-edit', 'fal fa-eject', 'fal fa-ellipsis-h',
  'fal fa-ellipsis-h-alt', 'fal fa-ellipsis-v', 'fal fa-ellipsis-v-alt', 'fal fa-envelope', 'fal fa-envelope-open',
  'fal fa-envelope-square', 'fal fa-eraser', 'fal fa-euro-sign', 'fal fa-exchange', 'fal fa-exchange-alt',
  'fal fa-exclamation', 'fal fa-exclamation-circle', 'fal fa-exclamation-square', 'fal fa-exclamation-triangle',
  'fal fa-expand', 'fal fa-expand-arrows', 'fal fa-expand-arrows-alt', 'fal fa-expand-wide', 'fal fa-external-link',
  'fal fa-external-link-alt', 'fal fa-external-link-square', 'fal fa-external-link-square-alt', 'fal fa-eye',
  'fal fa-eye-dropper', 'fal fa-eye-slash', 'fal fa-fast-backward', 'fal fa-fast-forward', 'fal fa-fax', 'fal fa-female',
  'fal fa-fighter-jet', 'fal fa-file', 'fal fa-file-alt', 'fal fa-file-archive', 'fal fa-file-audio', 'fal fa-file-check',
  'fal fa-file-code', 'fal fa-file-edit', 'fal fa-file-excel', 'fal fa-file-exclamation', 'fal fa-file-image',
  'fal fa-file-minus', 'fal fa-file-pdf', 'fal fa-file-plus', 'fal fa-file-powerpoint', 'fal fa-file-times',
  'fal fa-file-video', 'fal fa-file-word', 'fal fa-film', 'fal fa-filter', 'fal fa-fire', 'fal fa-fire-extinguisher',
  'fal fa-flag', 'fal fa-flag-checkered', 'fal fa-flask', 'fal fa-folder', 'fal fa-folder-open', 'fal fa-font',
  'fal fa-forward', 'fal fa-frown', 'fal fa-futbol', 'fal fa-gamepad', 'fal fa-gavel', 'fal fa-gem', 'fal fa-genderless',
  'fal fa-gift', 'fal fa-glass-martini', 'fal fa-globe', 'fal fa-graduation-cap', 'fal fa-h-square', 'fal fa-h1',
  'fal fa-h2', 'fal fa-h3', 'fal fa-hand-lizard', 'fal fa-hand-paper', 'fal fa-hand-peace', 'fal fa-hand-point-down',
  'fal fa-hand-point-left', 'fal fa-hand-point-right', 'fal fa-hand-point-up', 'fal fa-hand-pointer', 'fal fa-hand-rock',
  'fal fa-hand-scissors', 'fal fa-hand-spock', 'fal fa-handshake', 'fal fa-hashtag', 'fal fa-hdd', 'fal fa-heading',
  'fal fa-headphones', 'fal fa-heart', 'fal fa-heartbeat', 'fal fa-hexagon', 'fal fa-history', 'fal fa-home',
  'fal fa-hospital', 'fal fa-hourglass', 'fal fa-hourglass-end', 'fal fa-hourglass-half', 'fal fa-hourglass-start',
  'fal fa-i-cursor', 'fal fa-id-badge', 'fal fa-id-card', 'fal fa-image', 'fal fa-images', 'fal fa-inbox',
  'fal fa-inbox-in', 'fal fa-inbox-out', 'fal fa-indent', 'fal fa-industry', 'fal fa-industry-alt', 'fal fa-info',
  'fal fa-info-circle', 'fal fa-info-square', 'fal fa-italic', 'fal fa-jack-o-lantern', 'fal fa-key', 'fal fa-keyboard',
  'fal fa-language', 'fal fa-laptop', 'fal fa-leaf', 'fal fa-lemon', 'fal fa-level-down', 'fal fa-level-down-alt',
  'fal fa-level-up', 'fal fa-level-up-alt', 'fal fa-life-ring', 'fal fa-lightbulb', 'fal fa-link', 'fal fa-lira-sign',
  'fal fa-list', 'fal fa-list-alt', 'fal fa-list-ol', 'fal fa-list-ul', 'fal fa-location-arrow', 'fal fa-lock',
  'fal fa-lock-alt', 'fal fa-lock-open', 'fal fa-lock-open-alt', 'fal fa-long-arrow-alt-down', 'fal fa-long-arrow-alt-left',
  'fal fa-long-arrow-alt-right', 'fal fa-long-arrow-alt-up', 'fal fa-long-arrow-down', 'fal fa-long-arrow-left',
  'fal fa-long-arrow-right', 'fal fa-long-arrow-up', 'fal fa-low-vision', 'fal fa-magic', 'fal fa-magnet', 'fal fa-male',
  'fal fa-map', 'fal fa-map-marker', 'fal fa-map-marker-alt', 'fal fa-map-pin', 'fal fa-map-signs', 'fal fa-mars',
  'fal fa-mars-double', 'fal fa-mars-stroke', 'fal fa-mars-stroke-h', 'fal fa-mars-stroke-v', 'fal fa-medkit', 'fal fa-meh',
  'fal fa-mercury', 'fal fa-microchip', 'fal fa-microphone', 'fal fa-microphone-alt', 'fal fa-microphone-slash',
  'fal fa-minus', 'fal fa-minus-circle', 'fal fa-minus-hexagon', 'fal fa-minus-octagon', 'fal fa-minus-square',
  'fal fa-mobile', 'fal fa-mobile-alt', 'fal fa-mobile-android', 'fal fa-mobile-android-alt', 'fal fa-money-bill',
  'fal fa-money-bill-alt', 'fal fa-moon', 'fal fa-motorcycle', 'fal fa-mouse-pointer', 'fal fa-music', 'fal fa-neuter',
  'fal fa-newspaper', 'fal fa-object-group', 'fal fa-object-ungroup', 'fal fa-octagon', 'fal fa-outdent',
  'fal fa-paint-brush', 'fal fa-paper-plane', 'fal fa-paperclip', 'fal fa-paragraph', 'fal fa-paste', 'fal fa-pause',
  'fal fa-pause-circle', 'fal fa-paw', 'fal fa-pen', 'fal fa-pen-alt', 'fal fa-pen-square', 'fal fa-pencil',
  'fal fa-pencil-alt', 'fal fa-percent', 'fal fa-phone', 'fal fa-phone-slash', 'fal fa-phone-square', 'fal fa-phone-volume',
  'fal fa-plane', 'fal fa-plane-alt', 'fal fa-play', 'fal fa-play-circle', 'fal fa-plug', 'fal fa-plus', 'fal fa-plus-circle',
  'fal fa-plus-hexagon', 'fal fa-plus-octagon', 'fal fa-plus-square', 'fal fa-podcast', 'fal fa-poo', 'fal fa-portrait',
  'fal fa-pound-sign', 'fal fa-power-off', 'fal fa-print', 'fal fa-puzzle-piece', 'fal fa-qrcode', 'fal fa-question',
  'fal fa-question-circle', 'fal fa-question-square', 'fal fa-quote-left', 'fal fa-quote-right', 'fal fa-random',
  'fal fa-rectangle-landscape', 'fal fa-rectangle-portrait', 'fal fa-rectangle-wide', 'fal fa-recycle', 'fal fa-redo',
  'fal fa-redo-alt', 'fal fa-registered', 'fal fa-repeat', 'fal fa-repeat-1', 'fal fa-repeat-1-alt', 'fal fa-repeat-alt',
  'fal fa-reply', 'fal fa-reply-all', 'fal fa-retweet', 'fal fa-retweet-alt', 'fal fa-road', 'fal fa-rocket', 'fal fa-rss',
  'fal fa-rss-square', 'fal fa-ruble-sign', 'fal fa-rupee-sign', 'fal fa-save', 'fal fa-scrubber', 'fal fa-search',
  'fal fa-search-minus', 'fal fa-search-plus', 'fal fa-server', 'fal fa-share', 'fal fa-share-all', 'fal fa-share-alt',
  'fal fa-share-alt-square', 'fal fa-share-square', 'fal fa-shekel-sign', 'fal fa-shield', 'fal fa-shield-alt',
  'fal fa-shield-check', 'fal fa-ship', 'fal fa-shopping-bag', 'fal fa-shopping-basket', 'fal fa-shopping-cart',
  'fal fa-shower', 'fal fa-sign-in', 'fal fa-sign-in-alt', 'fal fa-sign-language', 'fal fa-sign-out', 'fal fa-sign-out-alt',
  'fal fa-signal', 'fal fa-sitemap', 'fal fa-sliders-h', 'fal fa-sliders-h-square', 'fal fa-sliders-v',
  'fal fa-sliders-v-square', 'fal fa-smile', 'fal fa-snowflake', 'fal fa-sort', 'fal fa-sort-alpha-down',
  'fal fa-sort-alpha-up', 'fal fa-sort-amount-down', 'fal fa-sort-amount-up', 'fal fa-sort-down',
  'fal fa-sort-numeric-down', 'fal fa-sort-numeric-up', 'fal fa-sort-up', 'fal fa-space-shuttle', 'fal fa-spade',
  'fal fa-spinner', 'fal fa-spinner-third', 'fal fa-square', 'fal fa-star', 'fal fa-star-exclamation', 'fal fa-star-half',
  'fal fa-step-backward', 'fal fa-step-forward', 'fal fa-stethoscope', 'fal fa-sticky-note', 'fal fa-stop',
  'fal fa-stop-circle', 'fal fa-stopwatch', 'fal fa-street-view', 'fal fa-strikethrough', 'fal fa-subscript',
  'fal fa-subway', 'fal fa-suitcase', 'fal fa-sun', 'fal fa-superscript', 'fal fa-sync', 'fal fa-sync-alt', 'fal fa-table',
  'fal fa-tablet', 'fal fa-tablet-alt', 'fal fa-tablet-android', 'fal fa-tablet-android-alt', 'fal fa-tachometer',
  'fal fa-tachometer-alt', 'fal fa-tag', 'fal fa-tags', 'fal fa-tasks', 'fal fa-taxi', 'fal fa-terminal',
  'fal fa-text-height', 'fal fa-text-width', 'fal fa-th', 'fal fa-th-large', 'fal fa-th-list', 'fal fa-thermometer-empty',
  'fal fa-thermometer-full', 'fal fa-thermometer-half', 'fal fa-thermometer-quarter', 'fal fa-thermometer-three-quarters',
  'fal fa-thumbs-down', 'fal fa-thumbs-up', 'fal fa-thumbtack', 'fal fa-ticket', 'fal fa-ticket-alt', 'fal fa-times',
  'fal fa-times-circle', 'fal fa-times-hexagon', 'fal fa-times-octagon', 'fal fa-times-square', 'fal fa-tint',
  'fal fa-toggle-off', 'fal fa-toggle-on', 'fal fa-trademark', 'fal fa-train', 'fal fa-transgender',
  'fal fa-transgender-alt', 'fal fa-trash', 'fal fa-trash-alt', 'fal fa-tree', 'fal fa-tree-alt', 'fal fa-triangle',
  'fal fa-trophy', 'fal fa-trophy-alt', 'fal fa-truck', 'fal fa-tty', 'fal fa-tv', 'fal fa-tv-retro',
  'fal fa-umbrella', 'fal fa-underline', 'fal fa-undo', 'fal fa-undo-alt', 'fal fa-universal-access', 'fal fa-university',
  'fal fa-unlink', 'fal fa-unlock', 'fal fa-unlock-alt', 'fal fa-upload', 'fal fa-usd-circle', 'fal fa-usd-square',
  'fal fa-user', 'fal fa-user-alt', 'fal fa-user-circle', 'fal fa-user-md', 'fal fa-user-plus', 'fal fa-user-secret',
  'fal fa-user-times', 'fal fa-users', 'fal fa-utensil-fork', 'fal fa-utensil-knife', 'fal fa-utensil-spoon',
  'fal fa-utensils', 'fal fa-utensils-alt', 'fal fa-venus', 'fal fa-venus-double', 'fal fa-venus-mars', 'fal fa-video',
  'fal fa-volume-down', 'fal fa-volume-mute', 'fal fa-volume-off', 'fal fa-volume-up', 'fal fa-watch',
  'fal fa-wheelchair', 'fal fa-wifi', 'fal fa-window', 'fal fa-window-alt', 'fal fa-window-close', 'fal fa-window-maximize',
  'fal fa-window-minimize', 'fal fa-window-restore', 'fal fa-won-sign', 'fal fa-wrench', 'fal fa-yen-sign',

  'fab fa-500px', 'fab fa-accessible-icon', 'fab fa-adn', 'fab fa-adversal',
  'fab fa-affiliatetheme', 'fab fa-algolia', 'fab fa-amazon', 'fab fa-amilia', 'fab fa-android', 'fab fa-angellist',
  'fab fa-angrycreative', 'fab fa-app-store', 'fab fa-app-store-ios', 'fab fa-apper', 'fab fa-apple',
  'fab fa-asymmetrik', 'fab fa-audible', 'fab fa-avianex', 'fab fa-aws', 'fab fa-bandcamp', 'fab fa-behance',
  'fab fa-behance-square', 'fab fa-bimobject', 'fab fa-bitbucket', 'fab fa-bitbucket-square', 'fab fa-bitcoin',
  'fab fa-bity', 'fab fa-black-tie', 'fab fa-blackberry', 'fab fa-blogger', 'fab fa-blogger-b', 'fab fa-bluetooth',
  'fab fa-bluetooth-b', 'fab fa-btc', 'fab fa-buromobelexperte', 'fab fa-buysellads', 'fab fa-cc-amex',
  'fab fa-cc-diners-club', 'fab fa-cc-discover', 'fab fa-cc-jcb', 'fab fa-cc-mastercard', 'fab fa-cc-paypal',
  'fab fa-cc-stripe', 'fab fa-cc-visa', 'fab fa-centercode', 'fab fa-chrome', 'fab fa-cloudscale',
  'fab fa-cloudsmith', 'fab fa-cloudversify', 'fab fa-codepen', 'fab fa-codiepie', 'fab fa-connectdevelop',
  'fab fa-contao', 'fab fa-cpanel', 'fab fa-creative-commons', 'fab fa-css3', 'fab fa-cuttlefish', 'fab fa-d-and-d',
  'fab fa-dashcube', 'fab fa-delicious', 'fab fa-deploydog', 'fab fa-deskpro', 'fab fa-deviantart', 'fab fa-digg',
  'fab fa-digital-ocean', 'fab fa-discord', 'fab fa-discourse', 'fab fa-dochub', 'fab fa-docker',
  'fab fa-draft2digital', 'fab fa-dribbble', 'fab fa-dribbble-square', 'fab fa-dropbox', 'fab fa-dropbox-alt',
  'fab fa-drupal', 'fab fa-dyalog', 'fab fa-earlybirds', 'fab fa-edge', 'fab fa-empire', 'fab fa-envira',
  'fab fa-erlang', 'fab fa-etsy', 'fab fa-expeditedssl', 'fab fa-facebook', 'fab fa-facebook-f',
  'fab fa-facebook-messenger', 'fab fa-facebook-square', 'fab fa-firefox', 'fab fa-first-order',
  'fab fa-firstdraft', 'fab fa-flickr', 'fab fa-font-awesome', 'fab fa-font-awesome-alt', 'fab fa-fonticons',
  'fab fa-fonticons-fi', 'fab fa-fort-awesome', 'fab fa-fort-awesome-alt', 'fab fa-forumbee', 'fab fa-foursquare',
  'fab fa-free-code-camp', 'fab fa-freebsd', 'fab fa-get-pocket', 'fab fa-gg', 'fab fa-gg-circle', 'fab fa-git',
  'fab fa-git-square', 'fab fa-github', 'fab fa-github-alt', 'fab fa-github-square', 'fab fa-gitkraken',
  'fab fa-gitlab', 'fab fa-glide', 'fab fa-glide-g', 'fab fa-gofore', 'fab fa-goodreads', 'fab fa-goodreads-g',
  'fab fa-google', 'fab fa-google-drive', 'fab fa-google-play', 'fab fa-google-plus', 'fab fa-google-plus-g',
  'fab fa-google-plus-square', 'fab fa-google-wallet', 'fab fa-gratipay', 'fab fa-grav', 'fab fa-gripfire',
  'fab fa-grunt', 'fab fa-gulp', 'fab fa-hacker-news', 'fab fa-hacker-news-square', 'fab fa-hire-a-helper',
  'fab fa-hotjar', 'fab fa-houzz', 'fab fa-html5', 'fab fa-hubspot', 'fab fa-imdb', 'fab fa-instagram',
  'fab fa-internet-explorer', 'fab fa-ioxhost', 'fab fa-itunes', 'fab fa-itunes-note', 'fab fa-jenkins',
  'fab fa-joget', 'fab fa-joomla', 'fab fa-js', 'fab fa-js-square', 'fab fa-jsfiddle', 'fab fa-keycdn',
  'fab fa-kickstarter', 'fab fa-kickstarter-k', 'fab fa-laravel', 'fab fa-lastfm', 'fab fa-lastfm-square',
  'fab fa-leanpub', 'fab fa-line', 'fab fa-linkedin', 'fab fa-linkedin-in', 'fab fa-linode', 'fab fa-linux',
  'fab fa-lyft', 'fab fa-magento', 'fab fa-maxcdn', 'fab fa-medapps', 'fab fa-medium', 'fab fa-medium-m',
  'fab fa-medrt', 'fab fa-meetup', 'fab fa-mix', 'fab fa-mixcloud', 'fab fa-mizuni', 'fab fa-modx', 'fab fa-monero',
  'fab fa-napster', 'fab fa-nintendo-switch', 'fab fa-npm', 'fab fa-nutritionix', 'fab fa-odnoklassniki',
  'fab fa-odnoklassniki-square', 'fab fa-opencart', 'fab fa-openid', 'fab fa-opera', 'fab fa-optin-monster',
  'fab fa-page4', 'fab fa-pagelines', 'fab fa-palfed', 'fab fa-patreon', 'fab fa-paypal', 'fab fa-periscope',
  'fab fa-phabricator', 'fab fa-phoenix-framework', 'fab fa-pied-piper', 'fab fa-pied-piper-alt',
  'fab fa-pied-piper-pp', 'fab fa-pinterest', 'fab fa-pinterest-p', 'fab fa-pinterest-square',
  'fab fa-playstation', 'fab fa-product-hunt', 'fab fa-pushed', 'fab fa-python', 'fab fa-qq',
  'fab fa-quora', 'fab fa-ravelry', 'fab fa-rebel', 'fab fa-red-river', 'fab fa-reddit', 'fab fa-reddit-alien',
  'fab fa-reddit-square', 'fab fa-rendact', 'fab fa-renren', 'fab fa-replyd', 'fab fa-resolving', 'fab fa-rocketchat',
  'fab fa-rockrms', 'fab fa-safari', 'fab fa-schlix', 'fab fa-scribd', 'fab fa-searchengin', 'fab fa-sellcast',
  'fab fa-sellsy', 'fab fa-servicestack', 'fab fa-shirtsinbulk', 'fab fa-simplybuilt', 'fab fa-sistrix',
  'fab fa-skyatlas', 'fab fa-skype', 'fab fa-slack', 'fab fa-slack-hash', 'fab fa-slideshare', 'fab fa-snapchat',
  'fab fa-snapchat-ghost', 'fab fa-snapchat-square', 'fab fa-soundcloud', 'fab fa-speakap', 'fab fa-spotify',
  'fab fa-stack-exchange', 'fab fa-stack-overflow', 'fab fa-staylinked', 'fab fa-steam', 'fab fa-steam-square',
  'fab fa-steam-symbol', 'fab fa-sticker-mule', 'fab fa-studiovinari', 'fab fa-stumbleupon',
  'fab fa-stumbleupon-circle', 'fab fa-superpowers', 'fab fa-supple', 'fab fa-telegram', 'fab fa-telegram-plane',
  'fab fa-tencent-weibo', 'fab fa-themeisle', 'fab fa-trello', 'fab fa-tripadvisor', 'fab fa-tumblr',
  'fab fa-tumblr-square', 'fab fa-twitch', 'fab fa-twitter', 'fab fa-twitter-square', 'fab fa-uber', 'fab fa-uikit',
  'fab fa-untappd', 'fab fa-usb', 'fab fa-ussunnah', 'fab fa-vaadin', 'fab fa-viacoin', 'fab fa-viadeo',
  'fab fa-viadeo-square', 'fab fa-viber', 'fab fa-vimeo', 'fab fa-vimeo-square', 'fab fa-vimeo-v', 'fab fa-vine',
  'fab fa-vk', 'fab fa-vnv', 'fab fa-weibo', 'fab fa-weixin', 'fab fa-whatsapp', 'fab fa-whatsapp-square',
  'fab fa-whmcs', 'fab fa-wikipedia-w', 'fab fa-windows', 'fab fa-wordpress', 'fab fa-wordpress-simple',
  'fab fa-wpbeginner', 'fab fa-wpexplorer', 'fab fa-wpforms', 'fab fa-xbox', 'fab fa-xing', 'fab fa-xing-square',
  'fab fa-y-combinator', 'fab fa-yahoo', 'fab fa-yandex', 'fab fa-yandex-international', 'fab fa-yelp',
  'fab fa-yoast', 'fab fa-youtube', 'fab fa-youtube-play'];
