export const colors: string[] = [
  '#0000000', '#444444', '#666666', '#999999', '#cccccc', '#eeeeee', '#f3f3f3', '#ffffff',
  '#ff0000', '#ff9900', '#ffff00', '#00ff00', '#00ffff', '#0000ff', '#9900ff', '#ff00ff',
  '#f4cccc', '#fce5cd', '#fff2cc', '#d9ead3', '#d0e0e3', '#cfe2f3', '#d9d2e9', '#ead1dc',
  '#ea9999', '#f9cb9c', '#ffe599', '#b6d7a8', '#a2c4c9', '#9fc5e8', '#b4a7d6', '#d5a6bd',
  '#e06666', '#f6b26b', '#ffd966', '#93c47d', '#76a5af', '#6fa8dc', '#8e7cc3', '#c27ba0',
  '#cc0000', '#e69138', '#f1c232', '#6aa84f', '#45818e', '#3d85c6', '#674ea7', '#a64d79',
  '#990000', '#b45f06', '#bf9000', '#38761d', '#134f5c', '#0b5394', '#351c75', '#741b47',
  '#660000', '#783f04', '#7f6000', '#274e13', '#0c343d', '#073763', '#20124d', '#4c1130 '
];

export const icons: string[] = ['fa-address-book', 'fa-address-card', 'fa-adjust', 'fa-alarm-clock', 'fa-align-center', 'fa-align-justify',
  'fa-align-left', 'fa-align-right', 'fa-ambulance', 'fa-american-sign-language-interpreting', 'fa-anchor', 'fa-angle-double-down',
  'fa-angle-double-left', 'fa-angle-double-right', 'fa-angle-double-up', 'fa-angle-down', 'fa-angle-left', 'fa-angle-right', 'fa-angle-up',
  'fa-archive', 'fa-arrow-alt-circle-down', 'fa-arrow-alt-circle-left', 'fa-arrow-alt-circle-right', 'fa-arrow-alt-circle-up', 'fa-arrow-alt-down',
  'fa-arrow-alt-from-bottom', 'fa-arrow-alt-from-left', 'fa-arrow-alt-from-right', 'fa-arrow-alt-from-top', 'fa-arrow-alt-left', 'fa-arrow-alt-right',
  'fa-arrow-alt-square-down', 'fa-arrow-alt-square-left', 'fa-arrow-alt-square-right', 'fa-arrow-alt-square-up', 'fa-arrow-alt-to-bottom',
  'fa-arrow-alt-to-left', 'fa-arrow-alt-to-right', 'fa-arrow-alt-to-top', 'fa-arrow-alt-up', 'fa-arrow-circle-down', 'fa-arrow-circle-left',
  'fa-arrow-circle-right', 'fa-arrow-circle-up', 'fa-arrow-down', 'fa-arrow-from-bottom', 'fa-arrow-from-left', 'fa-arrow-from-right',
  'fa-arrow-from-top', 'fa-arrow-left', 'fa-arrow-right', 'fa-arrow-square-down', 'fa-arrow-square-left', 'fa-arrow-square-right',
  'fa-arrow-square-up', 'fa-arrow-to-bottom', 'fa-arrow-to-left', 'fa-arrow-to-right', 'fa-arrow-to-top', 'fa-arrow-up', 'fa-arrows',
  'fa-arrows-alt', 'fa-arrows-alt-h', 'fa-arrows-alt-v', 'fa-arrows-h', 'fa-arrows-v', 'fa-assistive-listening-systems', 'fa-asterisk',
  'fa-at', 'fa-audio-description', 'fa-backward', 'fa-badge', 'fa-badge-check', 'fa-balance-scale', 'fa-ban', 'fa-barcode', 'fa-bars',
  'fa-bath', 'fa-battery-bolt', 'fa-battery-empty', 'fa-battery-full', 'fa-battery-half', 'fa-battery-quarter', 'fa-battery-slash',
  'fa-battery-three-quarters', 'fa-bed', 'fa-beer', 'fa-bell', 'fa-bell-slash', 'fa-bicycle', 'fa-binoculars', 'fa-birthday-cake', 'fa-blind',
  'fa-bold', 'fa-bolt', 'fa-bomb', 'fa-book', 'fa-bookmark', 'fa-braille', 'fa-briefcase', 'fa-browser', 'fa-bug', 'fa-building', 'fa-bullhorn',
  'fa-bullseye', 'fa-bus', 'fa-calculator', 'fa-calendar', 'fa-calendar-alt', 'fa-calendar-check', 'fa-calendar-edit',
  'fa-calendar-exclamation', 'fa-calendar-minus', 'fa-calendar-plus', 'fa-calendar-times', 'fa-camera', 'fa-camera-alt', 'fa-camera-retro',
  'fa-car', 'fa-caret-circle-down', 'fa-caret-circle-left', 'fa-caret-circle-right', 'fa-caret-circle-up', 'fa-caret-down', 'fa-caret-left',
  'fa-caret-right', 'fa-caret-square-down', 'fa-caret-square-left', 'fa-caret-square-right', 'fa-caret-square-up', 'fa-caret-up',
  'fa-cart-arrow-down', 'fa-cart-plus', 'fa-certificate', 'fa-chart-area', 'fa-chart-bar', 'fa-chart-line', 'fa-chart-pie', 'fa-check',
  'fa-check-circle', 'fa-check-square', 'fa-chevron-circle-down', 'fa-chevron-circle-left', 'fa-chevron-circle-right', 'fa-chevron-circle-up',
  'fa-chevron-double-down', 'fa-chevron-double-left', 'fa-chevron-double-right', 'fa-chevron-double-up', 'fa-chevron-down', 'fa-chevron-left',
  'fa-chevron-right', 'fa-chevron-square-down', 'fa-chevron-square-left', 'fa-chevron-square-right', 'fa-chevron-square-up', 'fa-chevron-up',
  'fa-child', 'fa-circle', 'fa-circle-notch', 'fa-clipboard', 'fa-clock', 'fa-clone', 'fa-closed-captioning', 'fa-cloud', 'fa-cloud-download',
  'fa-cloud-download-alt', 'fa-cloud-upload', 'fa-cloud-upload-alt', 'fa-club', 'fa-code', 'fa-code-branch', 'fa-code-commit', 'fa-code-merge',
  'fa-coffee', 'fa-cog', 'fa-cogs', 'fa-columns', 'fa-comment', 'fa-comment-alt', 'fa-comments', 'fa-compass', 'fa-compress', 'fa-compress-wide',
  'fa-copy', 'fa-copyright', 'fa-credit-card', 'fa-credit-card-blank', 'fa-credit-card-front', 'fa-crop', 'fa-crosshairs', 'fa-cube', 'fa-cubes',
  'fa-cut', 'fa-database', 'fa-deaf', 'fa-desktop', 'fa-desktop-alt', 'fa-diamond', 'fa-dollar-sign', 'fa-dot-circle', 'fa-download', 'fa-edit',
  'fa-eject', 'fa-ellipsis-h', 'fa-ellipsis-h-alt', 'fa-ellipsis-v', 'fa-ellipsis-v-alt', 'fa-envelope', 'fa-envelope-open', 'fa-envelope-square',
  'fa-eraser', 'fa-euro-sign', 'fa-exchange', 'fa-exchange-alt', 'fa-exclamation', 'fa-exclamation-circle', 'fa-exclamation-square',
  'fa-exclamation-triangle', 'fa-expand', 'fa-expand-arrows', 'fa-expand-arrows-alt', 'fa-expand-wide', 'fa-external-link', 'fa-external-link-alt',
  'fa-external-link-square', 'fa-external-link-square-alt', 'fa-eye', 'fa-eye-dropper', 'fa-eye-slash', 'fa-fast-backward', 'fa-fast-forward',
  'fa-fax', 'fa-female', 'fa-fighter-jet', 'fa-file', 'fa-file-alt', 'fa-file-archive', 'fa-file-audio', 'fa-file-check', 'fa-file-code',
  'fa-file-edit', 'fa-file-excel', 'fa-file-exclamation', 'fa-file-image', 'fa-file-minus', 'fa-file-pdf', 'fa-file-plus', 'fa-file-powerpoint',
  'fa-file-times', 'fa-file-video', 'fa-file-word', 'fa-film', 'fa-filter', 'fa-fire', 'fa-fire-extinguisher', 'fa-flag', 'fa-flag-checkered',
  'fa-flask', 'fa-folder', 'fa-folder-open', 'fa-font', 'fa-forward', 'fa-frown', 'fa-futbol', 'fa-gamepad', 'fa-gavel', 'fa-gem',
  'fa-genderless', 'fa-gift', 'fa-glass-martini', 'fa-globe', 'fa-graduation-cap', 'fa-h-square', 'fa-h1', 'fa-h2', 'fa-h3', 'fa-hand-lizard',
  'fa-hand-paper', 'fa-hand-peace', 'fa-hand-point-down', 'fa-hand-point-left', 'fa-hand-point-right', 'fa-hand-point-up', 'fa-hand-pointer',
  'fa-hand-rock', 'fa-hand-scissors', 'fa-hand-spock', 'fa-handshake', 'fa-hashtag', 'fa-hdd', 'fa-heading', 'fa-headphones', 'fa-heart',
  'fa-heartbeat', 'fa-hexagon', 'fa-history', 'fa-home', 'fa-hospital', 'fa-hourglass', 'fa-hourglass-end', 'fa-hourglass-half',
  'fa-hourglass-start', 'fa-i-cursor', 'fa-id-badge', 'fa-id-card', 'fa-image', 'fa-images', 'fa-inbox', 'fa-inbox-in', 'fa-inbox-out',
  'fa-indent', 'fa-industry', 'fa-industry-alt', 'fa-info', 'fa-info-circle', 'fa-info-square', 'fa-italic', 'fa-jack-o-lantern',
  'fa-key', 'fa-keyboard', 'fa-language', 'fa-laptop', 'fa-leaf', 'fa-lemon', 'fa-level-down', 'fa-level-down-alt', 'fa-level-up',
  'fa-level-up-alt', 'fa-life-ring', 'fa-lightbulb', 'fa-link', 'fa-lira-sign', 'fa-list', 'fa-list-alt', 'fa-list-ol', 'fa-list-ul',
  'fa-location-arrow', 'fa-lock', 'fa-lock-alt', 'fa-lock-open', 'fa-lock-open-alt', 'fa-long-arrow-alt-down', 'fa-long-arrow-alt-left',
  'fa-long-arrow-alt-right', 'fa-long-arrow-alt-up', 'fa-long-arrow-down', 'fa-long-arrow-left', 'fa-long-arrow-right', 'fa-long-arrow-up',
  'fa-low-vision', 'fa-magic', 'fa-magnet', 'fa-male', 'fa-map', 'fa-map-marker', 'fa-map-marker-alt', 'fa-map-pin', 'fa-map-signs', 'fa-mars',
  'fa-mars-double', 'fa-mars-stroke', 'fa-mars-stroke-h', 'fa-mars-stroke-v', 'fa-medkit', 'fa-meh', 'fa-mercury', 'fa-microchip', 'fa-microphone',
  'fa-microphone-alt', 'fa-microphone-slash', 'fa-minus', 'fa-minus-circle', 'fa-minus-hexagon', 'fa-minus-octagon', 'fa-minus-square', 'fa-mobile',
  'fa-mobile-alt', 'fa-mobile-android', 'fa-mobile-android-alt', 'fa-money-bill', 'fa-money-bill-alt', 'fa-moon', 'fa-motorcycle',
  'fa-mouse-pointer', 'fa-music', 'fa-neuter', 'fa-newspaper', 'fa-object-group', 'fa-object-ungroup', 'fa-octagon', 'fa-outdent',
  'fa-paint-brush', 'fa-paper-plane', 'fa-paperclip', 'fa-paragraph', 'fa-paste', 'fa-pause', 'fa-pause-circle', 'fa-paw', 'fa-pen',
  'fa-pen-alt', 'fa-pen-square', 'fa-pencil', 'fa-pencil-alt', 'fa-percent', 'fa-phone', 'fa-phone-slash', 'fa-phone-square', 'fa-phone-volume',
  'fa-plane', 'fa-plane-alt', 'fa-play', 'fa-play-circle', 'fa-plug', 'fa-plus', 'fa-plus-circle', 'fa-plus-hexagon', 'fa-plus-octagon',
  'fa-plus-square', 'fa-podcast', 'fa-poo', 'fa-portrait', 'fa-pound-sign', 'fa-power-off', 'fa-print', 'fa-puzzle-piece', 'fa-qrcode',
  'fa-question', 'fa-question-circle', 'fa-question-square', 'fa-quote-left', 'fa-quote-right', 'fa-random', 'fa-rectangle-landscape',
  'fa-rectangle-portrait', 'fa-rectangle-wide', 'fa-recycle', 'fa-redo', 'fa-redo-alt', 'fa-registered', 'fa-repeat', 'fa-repeat-1',
  'fa-repeat-1-alt', 'fa-repeat-alt', 'fa-reply', 'fa-reply-all', 'fa-retweet', 'fa-retweet-alt', 'fa-road', 'fa-rocket', 'fa-rss',
  'fa-rss-square', 'fa-ruble-sign', 'fa-rupee-sign', 'fa-save', 'fa-scrubber', 'fa-search', 'fa-search-minus', 'fa-search-plus', 'fa-server',
  'fa-share', 'fa-share-all', 'fa-share-alt', 'fa-share-alt-square', 'fa-share-square', 'fa-shekel-sign', 'fa-shield', 'fa-shield-alt',
  'fa-shield-check', 'fa-ship', 'fa-shopping-bag', 'fa-shopping-basket', 'fa-shopping-cart', 'fa-shower', 'fa-sign-in', 'fa-sign-in-alt',
  'fa-sign-language', 'fa-sign-out', 'fa-sign-out-alt', 'fa-signal', 'fa-sitemap', 'fa-sliders-h', 'fa-sliders-h-square', 'fa-sliders-v',
  'fa-sliders-v-square', 'fa-smile', 'fa-snowflake', 'fa-sort', 'fa-sort-alpha-down', 'fa-sort-alpha-up', 'fa-sort-amount-down',
  'fa-sort-amount-up', 'fa-sort-down', 'fa-sort-numeric-down', 'fa-sort-numeric-up', 'fa-sort-up', 'fa-space-shuttle', 'fa-spade', 'fa-spinner',
  'fa-spinner-third', 'fa-square', 'fa-star', 'fa-star-exclamation', 'fa-star-half', 'fa-step-backward', 'fa-step-forward', 'fa-stethoscope',
  'fa-sticky-note', 'fa-stop', 'fa-stop-circle', 'fa-stopwatch', 'fa-street-view', 'fa-strikethrough', 'fa-subscript', 'fa-subway', 'fa-suitcase',
  'fa-sun', 'fa-superscript', 'fa-sync', 'fa-sync-alt', 'fa-table', 'fa-tablet', 'fa-tablet-alt', 'fa-tablet-android', 'fa-tablet-android-alt',
  'fa-tachometer', 'fa-tachometer-alt', 'fa-tag', 'fa-tags', 'fa-tasks', 'fa-taxi', 'fa-terminal', 'fa-text-height', 'fa-text-width', 'fa-th',
  'fa-th-large', 'fa-th-list', 'fa-thermometer-empty', 'fa-thermometer-full', 'fa-thermometer-half', 'fa-thermometer-quarter',
  'fa-thermometer-three-quarters', 'fa-thumbs-down', 'fa-thumbs-up', 'fa-thumbtack', 'fa-ticket', 'fa-ticket-alt', 'fa-times', 'fa-times-circle',
  'fa-times-hexagon', 'fa-times-octagon', 'fa-times-square', 'fa-tint', 'fa-toggle-off', 'fa-toggle-on', 'fa-trademark', 'fa-train',
  'fa-transgender', 'fa-transgender-alt', 'fa-trash', 'fa-trash-alt', 'fa-tree', 'fa-tree-alt', 'fa-triangle', 'fa-trophy', 'fa-trophy-alt',
  'fa-truck', 'fa-tty', 'fa-tv', 'fa-tv-retro', 'fa-umbrella', 'fa-underline', 'fa-undo', 'fa-undo-alt', 'fa-universal-access', 'fa-university',
  'fa-unlink', 'fa-unlock', 'fa-unlock-alt', 'fa-upload', 'fa-usd-circle', 'fa-usd-square', 'fa-user', 'fa-user-alt', 'fa-user-circle',
  'fa-user-md', 'fa-user-plus', 'fa-user-secret', 'fa-user-times', 'fa-users', 'fa-utensil-fork', 'fa-utensil-knife', 'fa-utensil-spoon',
  'fa-utensils', 'fa-utensils-alt', 'fa-venus', 'fa-venus-double', 'fa-venus-mars', 'fa-video', 'fa-volume-down', 'fa-volume-mute',
  'fa-volume-off', 'fa-volume-up', 'fa-watch', 'fa-wheelchair', 'fa-wifi', 'fa-window', 'fa-window-alt', 'fa-window-close', 'fa-window-maximize',
  'fa-window-minimize', 'fa-window-restore', 'fa-won-sign', 'fa-wrench', 'fa-yen-sign', 'fa-500px', 'fa-accessible-icon', 'fa-adn', 'fa-adversal',
  'fa-affiliatetheme', 'fa-algolia', 'fa-amazon', 'fa-amilia', 'fa-android', 'fa-angellist', 'fa-angrycreative', 'fa-app-store',
  'fa-app-store-ios', 'fa-apper', 'fa-apple', 'fa-asymmetrik', 'fa-audible', 'fa-avianex', 'fa-aws', 'fa-bandcamp', 'fa-behance',
  'fa-behance-square', 'fa-bimobject', 'fa-bitbucket', 'fa-bitbucket-square', 'fa-bitcoin', 'fa-bity', 'fa-black-tie', 'fa-blackberry',
  'fa-blogger', 'fa-blogger-b', 'fa-bluetooth', 'fa-bluetooth-b', 'fa-btc', 'fa-buromobelexperte', 'fa-buysellads', 'fa-cc-amex',
  'fa-cc-diners-club', 'fa-cc-discover', 'fa-cc-jcb', 'fa-cc-mastercard', 'fa-cc-paypal', 'fa-cc-stripe', 'fa-cc-visa', 'fa-centercode',
  'fa-chrome', 'fa-cloudscale', 'fa-cloudsmith', 'fa-cloudversify', 'fa-codepen', 'fa-codiepie', 'fa-connectdevelop', 'fa-contao', 'fa-cpanel',
  'fa-creative-commons', 'fa-css3', 'fa-cuttlefish', 'fa-d-and-d', 'fa-dashcube', 'fa-delicious', 'fa-deploydog', 'fa-deskpro', 'fa-deviantart',
  'fa-digg', 'fa-digital-ocean', 'fa-discord', 'fa-discourse', 'fa-dochub', 'fa-docker', 'fa-draft2digital', 'fa-dribbble', 'fa-dribbble-square',
  'fa-dropbox', 'fa-dropbox-alt', 'fa-drupal', 'fa-dyalog', 'fa-earlybirds', 'fa-edge', 'fa-empire', 'fa-envira', 'fa-erlang', 'fa-etsy',
  'fa-expeditedssl', 'fa-facebook', 'fa-facebook-f', 'fa-facebook-messenger', 'fa-facebook-square', 'fa-firefox', 'fa-first-order', 'fa-firstdraft',
  'fa-flickr', 'fa-font-awesome', 'fa-font-awesome-alt', 'fa-fonticons', 'fa-fonticons-fi', 'fa-fort-awesome', 'fa-fort-awesome-alt',
  'fa-forumbee', 'fa-foursquare', 'fa-free-code-camp', 'fa-freebsd', 'fa-get-pocket', 'fa-gg', 'fa-gg-circle', 'fa-git', 'fa-git-square',
  'fa-github', 'fa-github-alt', 'fa-github-square', 'fa-gitkraken', 'fa-gitlab', 'fa-glide', 'fa-glide-g', 'fa-gofore', 'fa-goodreads',
  'fa-goodreads-g', 'fa-google', 'fa-google-drive', 'fa-google-play', 'fa-google-plus', 'fa-google-plus-g', 'fa-google-plus-square',
  'fa-google-wallet', 'fa-gratipay', 'fa-grav', 'fa-gripfire', 'fa-grunt', 'fa-gulp', 'fa-hacker-news', 'fa-hacker-news-square',
  'fa-hire-a-helper', 'fa-hotjar', 'fa-houzz', 'fa-html5', 'fa-hubspot', 'fa-imdb', 'fa-instagram', 'fa-internet-explorer', 'fa-ioxhost',
  'fa-itunes', 'fa-itunes-note', 'fa-jenkins', 'fa-joget', 'fa-joomla', 'fa-js', 'fa-js-square', 'fa-jsfiddle', 'fa-keycdn', 'fa-kickstarter',
  'fa-kickstarter-k', 'fa-laravel', 'fa-lastfm', 'fa-lastfm-square', 'fa-leanpub', 'fa-line', 'fa-linkedin', 'fa-linkedin-in', 'fa-linode',
  'fa-linux', 'fa-lyft', 'fa-magento', 'fa-maxcdn', 'fa-medapps', 'fa-medium', 'fa-medium-m', 'fa-medrt', 'fa-meetup', 'fa-mix', 'fa-mixcloud',
  'fa-mizuni', 'fa-modx', 'fa-monero', 'fa-napster', 'fa-nintendo-switch', 'fa-npm', 'fa-nutritionix', 'fa-odnoklassniki', 'fa-odnoklassniki-square',
  'fa-opencart', 'fa-openid', 'fa-opera', 'fa-optin-monster', 'fa-page4', 'fa-pagelines', 'fa-palfed', 'fa-patreon', 'fa-paypal', 'fa-periscope',
  'fa-phabricator', 'fa-phoenix-framework', 'fa-pied-piper', 'fa-pied-piper-alt', 'fa-pied-piper-pp', 'fa-pinterest', 'fa-pinterest-p',
  'fa-pinterest-square', 'fa-playstation', 'fa-product-hunt', 'fa-pushed', 'fa-python', 'fa-qq', 'fa-quora', 'fa-ravelry', 'fa-rebel',
  'fa-red-river', 'fa-reddit', 'fa-reddit-alien', 'fa-reddit-square', 'fa-rendact', 'fa-renren', 'fa-replyd', 'fa-resolving', 'fa-rocketchat',
  'fa-rockrms', 'fa-safari', 'fa-schlix', 'fa-scribd', 'fa-searchengin', 'fa-sellcast', 'fa-sellsy', 'fa-servicestack', 'fa-shirtsinbulk',
  'fa-simplybuilt', 'fa-sistrix', 'fa-skyatlas', 'fa-skype', 'fa-slack', 'fa-slack-hash', 'fa-slideshare', 'fa-snapchat', 'fa-snapchat-ghost',
  'fa-snapchat-square', 'fa-soundcloud', 'fa-speakap', 'fa-spotify', 'fa-stack-exchange', 'fa-stack-overflow', 'fa-staylinked', 'fa-steam',
  'fa-steam-square', 'fa-steam-symbol', 'fa-sticker-mule', 'fa-studiovinari', 'fa-stumbleupon', 'fa-stumbleupon-circle', 'fa-superpowers',
  'fa-supple', 'fa-telegram', 'fa-telegram-plane', 'fa-tencent-weibo', 'fa-themeisle', 'fa-trello', 'fa-tripadvisor', 'fa-tumblr',
  'fa-tumblr-square', 'fa-twitch', 'fa-twitter', 'fa-twitter-square', 'fa-uber', 'fa-uikit', 'fa-untappd', 'fa-usb', 'fa-ussunnah',
  'fa-vaadin', 'fa-viacoin', 'fa-viadeo', 'fa-viadeo-square', 'fa-viber', 'fa-vimeo', 'fa-vimeo-square', 'fa-vimeo-v', 'fa-vine',
  'fa-vk', 'fa-vnv', 'fa-weibo', 'fa-weixin', 'fa-whatsapp', 'fa-whatsapp-square', 'fa-whmcs', 'fa-wikipedia-w', 'fa-windows', 'fa-wordpress',
  'fa-wordpress-simple', 'fa-wpbeginner', 'fa-wpexplorer', 'fa-wpforms', 'fa-xbox', 'fa-xing', 'fa-xing-square', 'fa-y-combinator', 'fa-yahoo',
  'fa-yandex', 'fa-yandex-international', 'fa-yelp', 'fa-yoast', 'fa-youtube', 'fa-youtube-play'];
