name: 'Run Playwright E2E tests'

on:
  pull_request:
  push:
    branches:
      - 'master'

env:
  TEST_USER_EMAIL: 'uitest-${{ github.run_id }}@lumeer.io'

jobs:
  run-tests:
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '23'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install libssl and libcrypto
        run: sudo chmod u+w /etc/apt/sources.list && sudo echo "deb http://security.ubuntu.com/ubuntu focal-security main" >> /etc/apt/sources.list && sudo apt-get update && sudo apt-get install libssl-dev=1.1.1f-1ubuntu2.24
      - name: Generate password to env variables
        run: echo "TEST_USER_PASSWORD=$(uuidgen)" >> "$GITHUB_ENV"
      - name: Build (mvn clean install)
        run: |
          chmod +x ./playwright-scripts/build.sh
          ./playwright-scripts/build.sh
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: |
          chmod +x ./playwright-scripts/playwright-tests.sh
          ./playwright-scripts/playwright-tests.sh
        shell: bash
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
